/**
 * ====================================================================
 * 📸 PHOTOGRAPHY PORTFOLIO - CORE APPLICATION LOGIC
 * ====================================================================
 */

let currentAlbumPhotos = [];
let currentPhotoIndex = 0;
let isCollabExpanded = false;
let isAwardsExpanded = false;

document.addEventListener('DOMContentLoaded', () => {
  initProtectImages();
  adaptLinksForEnvironment();
  initNavbarScroll();
  initMobileMenu();
  initMobileTouchHover();
  initLanguageSelector();
  
  // Determine current page and render appropriate section
  const currentPage = getCurrentPageName();
  
  if (currentPage === 'index' || currentPage === '') {
    renderHomePage();
  } else if (currentPage === 'contact') {
    renderContactPage();
  } else {
    // Render specific category gallery page
    renderCategoryPage(currentPage);
  }

  // Re-adapt links dynamically generated by JS
  adaptLinksForEnvironment();
});

// Helper: Adapt URLs based on environment (file:// vs http/https)
function adaptLinksForEnvironment() {
  if (window.location.protocol === 'file:') return;

  // Clean .html from address bar using history.replaceState on web server
  const path = window.location.pathname;
  if (path.endsWith('.html')) {
    let cleanPath = path.replace(/\.html$/, '');
    if (cleanPath.endsWith('/index') || cleanPath === 'index' || cleanPath === '/index') {
      cleanPath = cleanPath.replace(/\/index$/, '/').replace(/^index$/, './');
    }
    const newUrl = cleanPath + window.location.search + window.location.hash;
    window.history.replaceState(null, '', newUrl || './');
  }

  // Dynamically rewrite internal .html links to clean extensionless URLs for web server
  document.querySelectorAll('a[href]').forEach(a => {
    const href = a.getAttribute('href');
    if (!href) return;
    if (href === 'index.html') {
      a.setAttribute('href', './');
    } else if (href.startsWith('index.html#')) {
      a.setAttribute('href', './' + href.substring(10));
    } else if (href.endsWith('.html') && !href.includes('://')) {
      a.setAttribute('href', href.replace(/\.html$/, ''));
    }
  });
}

// Helper: Get Current Page Name
function getCurrentPageName() {
  const path = window.location.pathname;
  let page = path.split('/').filter(Boolean).pop() || 'index';
  return page.replace('.html', '');
}

// Helper: Get Custom Image Scale & Position Style
function getImageStyle(item) {
  if (!item) return '';
  const pos = item.position || 'center';
  const scale = item.scale !== undefined ? item.scale : (item.position ? 1.25 : 1);
  return `--img-pos: ${pos}; --img-origin: ${pos}; --img-scale: ${scale};`;
}

// Helper: Parse numerical target and suffix from stat value string (e.g. "6000+" -> { numericValue: 6000, suffix: "+", hasComma: false })
function parseStatValue(val) {
  if (typeof val !== 'string') val = String(val || '');
  const match = val.trim().match(/^([\d,]+)(.*)$/);
  if (match) {
    const rawNumStr = match[1];
    const hasComma = rawNumStr.includes(',');
    const numericValue = parseInt(rawNumStr.replace(/,/g, ''), 10);
    const suffix = match[2] || '';
    if (!isNaN(numericValue)) {
      return { numericValue, suffix, hasComma };
    }
  }
  return { numericValue: null, suffix: val, hasComma: false };
}

// Helper: Generate Slot Machine Reel HTML for a single digit or symbol (e.g. '+')
function createReelHtml(char) {
  const d = parseInt(char, 10);
  if (isNaN(d)) {
    // Suffix symbol (e.g. '+') has blank spaces in earlier reel slots, showing '+' ONLY ONCE at the end of the roll!
    const totalItems = 30;
    const targetIndex = 29;
    const symbolsArr = Array(totalItems).fill('&nbsp;');
    symbolsArr[targetIndex] = char; // Only the last slot contains '+', all preceding slots are blank
    const spansHtml = symbolsArr.map(s => `<span class="h-[1.1em] flex items-center justify-center shrink-0">${s}</span>`).join('');

    return `
      <span class="stat-reel stat-suffix inline-block overflow-hidden relative align-bottom h-[1.1em] leading-none text-center text-amber-400 ml-0.5" style="opacity: 0;">
        <span class="stat-strip flex flex-col transition-none" data-target-index="${targetIndex}" data-total-items="${totalItems}" style="transform: translateY(0%);">
          ${spansHtml}
        </span>
      </span>
    `;
  }

  // 3 sets of 0-9 for slot machine tumbling sequence (0..9, 0..9, 0..9)
  const digitsArr = [0,1,2,3,4,5,6,7,8,9, 0,1,2,3,4,5,6,7,8,9, 0,1,2,3,4,5,6,7,8,9];
  const targetIndex = 20 + d; // Target digit in the 3rd set for full slot machine roll
  const totalItems = digitsArr.length;

  const spansHtml = digitsArr.map(n => `<span class="h-[1.1em] flex items-center justify-center shrink-0">${n}</span>`).join('');

  return `
    <span class="stat-reel inline-block overflow-hidden relative align-bottom h-[1.1em] leading-none text-center">
      <span class="stat-strip flex flex-col transition-none" data-target-index="${targetIndex}" data-total-items="${totalItems}" style="transform: translateY(0%);">
        ${spansHtml}
      </span>
    </span>
  `;
}

// Function to animate About Me slot machine rolling counter
function initStatsCounter() {
  const statStrips = document.querySelectorAll('#stats-grid .stat-strip');
  if (!statStrips.length) return;

  const DURATION = 3000; // 3.0s total duration for all reels to finish simultaneously

  // Ease-Out Quint easing function: rapid initial slot tumble, smooth deceleration into slot
  const easeOutQuint = (t) => 1 - Math.pow(1 - t, 5);

  const startAnimation = () => {
    const startTime = performance.now();

    const animate = (currentTime) => {
      const elapsedTime = currentTime - startTime;
      const progress = Math.min(elapsedTime / DURATION, 1);
      const easedProgress = easeOutQuint(progress);

      statStrips.forEach(strip => {
        const targetIndex = parseFloat(strip.dataset.targetIndex);
        const totalItems = parseFloat(strip.dataset.totalItems);
        if (isNaN(targetIndex) || !totalItems) return;

        const currentTranslatePercent = (targetIndex * easedProgress / totalItems) * 100;
        strip.style.transform = `translateY(-${currentTranslatePercent}%)`;

        // If strip is inside a stat-suffix, gradually fade in opacity (0 -> 1) synchronously with the roll
        const parentSuffix = strip.closest('.stat-suffix');
        if (parentSuffix) {
          parentSuffix.style.opacity = easedProgress;
        }
      });

      if (progress < 1) {
        requestAnimationFrame(animate);
      } else {
        // Animation complete: lock exact target translateY and 100% opacity
        statStrips.forEach(strip => {
          const targetIndex = parseFloat(strip.dataset.targetIndex);
          const totalItems = parseFloat(strip.dataset.totalItems);
          if (!isNaN(targetIndex) && totalItems) {
            const finalPercent = (targetIndex / totalItems) * 100;
            strip.style.transform = `translateY(-${finalPercent}%)`;
          }
          const parentSuffix = strip.closest('.stat-suffix');
          if (parentSuffix) {
            parentSuffix.style.opacity = 1;
          }
        });
      }
    };

    requestAnimationFrame(animate);
  };

  // Trigger animation using IntersectionObserver when in view or immediately on load
  const statsGrid = document.getElementById('stats-grid');
  if (statsGrid && 'IntersectionObserver' in window) {
    const observer = new IntersectionObserver((entries) => {
      entries.forEach(entry => {
        if (entry.isIntersecting) {
          startAnimation();
          observer.unobserve(entry.target);
        }
      });
    }, { threshold: 0.1 });
    observer.observe(statsGrid);
  } else {
    startAnimation();
  }
}

// --------------------------------------------------------------------
// 1. Render Home Page
// --------------------------------------------------------------------
function renderHomePage() {
  const data = window.PORTFOLIO_DATA;
  if (!data) {
    console.error("PORTFOLIO_DATA is not defined. Please check js/portfolio-data.js for syntax errors.");
    const container = document.getElementById('hero-about-container');
    if (container) {
      container.innerHTML = `
        <div class="max-w-4xl mx-auto px-6 py-20 text-center">
          <div class="p-6 bg-red-500/10 border border-red-500/30 rounded-xl text-red-300 space-y-3">
            <h3 class="text-xl font-bold">⚠️ 資料讀取失敗 (Data Load Error)</h3>
            <p class="text-sm"><code>js/portfolio-data.js</code> 檔案中可能有語法錯誤（例如物件之間缺少逗號 <code>,</code> 或單雙引號未成對）。</p>
            <p class="text-xs text-gray-400">請開啟瀏覽器開發者工具 (F12) 的 Console 檢視詳細錯誤行數。</p>
          </div>
        </div>
      `;
    }
    return;
  }

  // Render About Me Hero Section
  const heroContainer = document.getElementById('hero-about-container');
  if (heroContainer && data.profile) {
    heroContainer.innerHTML = `
      <div class="max-w-6xl mx-auto px-6 py-16 lg:py-24 grid grid-cols-1 lg:grid-cols-12 gap-12 items-center">
        <!-- Photographer Portrait Avatar -->
        <div class="lg:col-span-5 flex justify-center">
          <div class="relative group cursor-pointer w-72 h-80 sm:w-80 sm:h-96 rounded-2xl overflow-hidden border border-amber-500/20 shadow-2xl">
            <img src="${data.profile.avatar || ''}" alt="${data.profile.name || ''}" draggable="false" class="w-full h-full object-cover transition-transform duration-700 group-hover:scale-105" />
            <div class="absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-transparent"></div>
            <div class="absolute bottom-6 left-6 right-6">
              <p class="text-xs uppercase tracking-widest text-amber-400 font-medium mb-1">${data.profile.tagline || ''}</p>
              <h3 class="text-2xl font-bold font-serif-title text-white">${data.profile.name || ''}</h3>
              ${data.profile.location ? `
                <p class="text-xs text-gray-400 flex items-center gap-1 mt-1">
                  <svg class="w-3.5 h-3.5 text-amber-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z"/><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 11a3 3 0 11-6 0 3 3 0 016 0z"/></svg>
                  ${data.profile.location}
                </p>
              ` : ''}
            </div>
          </div>
        </div>

        <!-- Photographer Bio & Stats -->
        <div class="lg:col-span-7 space-y-6">
          
          <h1 class="text-4xl sm:text-5xl font-bold font-serif-title leading-tight">
            About <span class="title-gradient-text">Me</span>
          </h1>

          <div class="space-y-4 text-gray-300 leading-relaxed text-base sm:text-lg">
            ${Array.isArray(data.profile.bio) ? data.profile.bio.map(p => `<p>${p}</p>`).join('') : ''}
          </div>

          <!-- Key Stats Grid -->
          ${Array.isArray(data.profile.stats) ? `
            <div id="stats-grid" class="grid grid-cols-2 sm:grid-cols-4 gap-4 py-4 border-y border-[#ffffff1a]">
              ${data.profile.stats.map(stat => {
                const parsed = parseStatValue(stat.value || '');
                if (parsed.numericValue !== null) {
                  const numStr = parsed.hasComma ? parsed.numericValue.toLocaleString() : String(parsed.numericValue);
                  const digits = numStr.split('');
                  return `
                    <div class="text-center sm:text-left">
                      <div class="text-3xl sm:text-4xl font-bold font-cinzel text-amber-400 flex items-baseline justify-center sm:justify-start">
                        <div class="inline-flex items-baseline tracking-tight">
                          ${digits.map(d => createReelHtml(d)).join('')}
                          ${parsed.suffix ? createReelHtml(parsed.suffix) : ''}
                        </div>
                      </div>
                      <div class="text-xs text-gray-400 mt-1 uppercase tracking-wider font-medium">${stat.label || ''}</div>
                    </div>
                  `;
                } else {
                  return `
                    <div class="text-center sm:text-left">
                      <div class="text-3xl sm:text-4xl font-bold font-cinzel text-amber-400">${stat.value || ''}</div>
                      <div class="text-xs text-gray-400 mt-1 uppercase tracking-wider font-medium">${stat.label || ''}</div>
                    </div>
                  `;
                }
              }).join('')}
            </div>
          ` : ''}

          <!-- CTA Actions -->
          <div class="flex flex-wrap items-center gap-4 pt-2">
            <a href="#categories-section" class="btn-gold">
              瀏覽攝影作品
            </a>
            <a href="contact" class="btn-outline">
              預約與合作諮詢
            </a>
          </div>
        </div>
      </div>
    `;

    // Trigger animated stats counter for About Me
    initStatsCounter();
  }

  // Render Collaborations & Experience Section
  const collabContainer = document.getElementById('collaborations-container');
  if (collabContainer && Array.isArray(data.collaborations)) {
    const collabs = data.collaborations;
    const hasMoreCollabs = collabs.length > 3;

    collabContainer.innerHTML = `
      <div class="max-w-6xl mx-auto px-6 py-16">
        <div class="text-center max-w-2xl mx-auto mb-12 space-y-3">
          <h2 class="text-3xl sm:text-4xl font-bold font-serif-title">
            歷年品牌與活動合作紀錄
          </h2>
        </div>

        <!-- Collapsible Wrapper with Smooth Fade-out Mask -->
        <div class="relative">
          <div id="collab-grid-wrapper" class="overflow-hidden transition-all duration-700 ease-in-out ${hasMoreCollabs ? 'max-h-[340px]' : ''} relative">
            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 pt-4 pb-6 px-1">
              ${collabs.map(collab => `
                <div class="luxury-card p-6 flex flex-col justify-between group">
                  <div>
                    <div class="flex items-center justify-between mb-3">
                      <span class="text-2xl font-black font-cinzel text-amber-400 tracking-wider group-hover:text-amber-300 transition-colors">
                        ${collab.logoText || collab.brand || ''}
                      </span>
                      ${collab.year ? `
                        <span class="text-xs px-2.5 py-1 rounded bg-white/5 border border-white/10 text-gray-400">
                          ${collab.year}
                        </span>
                      ` : ''}
                    </div>
                    ${collab.role ? `<p class="text-sm sm:text-base text-white font-semibold mb-3">${collab.role}</p>` : ''}
                    ${collab.description ? `
                      <p class="text-xs sm:text-sm text-gray-400 leading-relaxed">
                        ${collab.description}
                      </p>
                    ` : ''}
                  </div>
                  ${collab.category ? `
                    <div class="mt-5 pt-4 border-t border-white/5 flex items-center justify-between text-xs text-gray-500">
                      <span>類型</span>
                      <span class="text-gray-300 font-medium">${collab.category}</span>
                    </div>
                  ` : ''}
                </div>
              `).join('')}
            </div>
          </div>

          <!-- Bottom Fade-out Gradient Mask -->
          ${hasMoreCollabs ? `
            <div id="collab-gradient-overlay" class="absolute bottom-0 left-0 right-0 h-40 bg-gradient-to-t from-[#0e0f14] via-[#0e0f14]/80 to-transparent pointer-events-none transition-opacity duration-500"></div>
          ` : ''}
        </div>

        <!-- Show More Toggle Button -->
        ${hasMoreCollabs ? `
          <div class="flex justify-center pt-4 relative z-10">
            <button id="toggle-collab-btn" onclick="toggleCollaborations()" class="btn-outline flex items-center gap-2 group">
              <span id="collab-btn-text">顯示更多經歷 (${collabs.length})</span>
              <svg id="collab-btn-icon" class="w-4 h-4 text-amber-400 transition-transform duration-300" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"/>
              </svg>
            </button>
          </div>
        ` : ''}
      </div>
    `;
  }

  // Render Awards & Honors Section
  const awardsContainer = document.getElementById('awards-container');
  if (awardsContainer && Array.isArray(data.awards)) {
    const awards = data.awards;
    const hasMoreAwards = awards.length > 2;

    awardsContainer.innerHTML = `
      <div class="max-w-6xl mx-auto px-6 py-16">
        <div class="text-center max-w-2xl mx-auto mb-14 space-y-3">
          <h2 class="text-3xl sm:text-4xl font-bold font-serif-title">
            攝影獎項
          </h2>
        </div>

        <!-- Collapsible Wrapper with Smooth Fade-out Mask -->
        <div class="relative">
          <div id="awards-grid-wrapper" class="overflow-hidden transition-all duration-700 ease-in-out ${hasMoreAwards ? 'max-h-[330px]' : ''} relative">
            <div class="grid grid-cols-1 md:grid-cols-2 gap-6 pt-4 pb-6 px-1">
              ${awards.map(award => `
                <div class="luxury-card p-6 sm:p-8 flex flex-col justify-between group">
                  <div class="space-y-3">
                    <div class="flex items-center justify-between">
                      ${award.year ? `
                        <span class="text-xs font-mono px-3 py-1 rounded-full bg-amber-500/10 border border-amber-500/30 text-amber-400 font-semibold">
                          ${award.year}
                        </span>
                      ` : '<span></span>'}
                      ${award.result ? `
                        <span class="px-3 py-1 rounded-full bg-gradient-to-r from-amber-500/20 to-amber-300/10 border border-amber-400/40 text-amber-300 font-bold text-xs flex items-center gap-1.5 shadow-sm">
                          <svg class="w-3.5 h-3.5 text-amber-400" fill="currentColor" viewBox="0 0 24 24"><path d="M12 2l2.4 7.4h7.6l-6.2 4.5 2.4 7.4-6.2-4.5-6.2 4.5 2.4-7.4-6.2-4.5h7.6z"/></svg>
                          ${award.result}
                        </span>
                      ` : ''}
                    </div>

                    ${award.title ? `
                      <h3 class="text-xl font-bold text-white font-serif-title group-hover:text-amber-400 transition-colors pt-1">
                        ${award.title}
                      </h3>
                    ` : ''}

                    ${award.category ? `
                      <p class="text-xs text-amber-400/80 font-medium uppercase tracking-wider">
                        ${award.category}
                      </p>
                    ` : ''}

                    ${award.description ? `
                      <p class="text-xs sm:text-sm text-gray-400 leading-relaxed pt-1">
                        ${award.description}
                      </p>
                    ` : ''}
                  </div>
                </div>
              `).join('')}
            </div>
          </div>

          <!-- Bottom Fade-out Gradient Mask -->
          ${hasMoreAwards ? `
            <div id="awards-gradient-overlay" class="absolute bottom-0 left-0 right-0 h-40 bg-gradient-to-t from-[#0a0a0c] via-[#0a0a0c]/80 to-transparent pointer-events-none transition-opacity duration-500"></div>
          ` : ''}
        </div>

        <!-- Show More Toggle Button -->
        ${hasMoreAwards ? `
          <div class="flex justify-center pt-4 relative z-10">
            <button id="toggle-awards-btn" onclick="toggleAwards()" class="btn-outline flex items-center gap-2 group">
              <span id="awards-btn-text">顯示更多獲獎紀錄 (${awards.length})</span>
              <svg id="awards-btn-icon" class="w-4 h-4 text-amber-400 transition-transform duration-300" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"/>
              </svg>
            </button>
          </div>
        ` : ''}
      </div>
    `;
  }

  // Render 7 Categories Gateway Cards
  const categoriesContainer = document.getElementById('categories-container');
  if (categoriesContainer && Array.isArray(data.categories)) {
    categoriesContainer.innerHTML = `
      <div class="max-w-6xl mx-auto px-6 py-16">
        <div class="text-center max-w-2xl mx-auto mb-14 space-y-3">
          <h2 class="text-3xl sm:text-4xl font-bold font-serif-title">
            探索不同攝影類型作品
          </h2>
        </div>

        <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8">
          ${data.categories.map(cat => `
            <a href="${cat.pageUrl}" class="luxury-card group block no-underline text-white">
              <div class="image-hover-zoom h-64 sm:h-72 w-full">
                <img src="${cat.cover}" alt="${cat.title}" draggable="false" style="${getImageStyle(cat)}" />
                <div class="absolute inset-0 bg-gradient-to-t from-black via-black/30 to-transparent"></div>
                <div class="absolute top-4 right-4">
                  <span class="category-badge">${cat.badge}</span>
                </div>
              </div>
              <div class="p-6 space-y-2">
                <div class="flex items-center justify-between">
                  <h3 class="text-2xl font-bold font-serif-title text-white group-hover:text-amber-400 transition-colors">
                    ${cat.title}
                  </h3>
                  <svg class="w-5 h-5 text-gray-500 group-hover:text-amber-400 group-hover:translate-x-1 transition-all" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M14 5l7 7m0 0l-7 7m7-7H3"/></svg>
                </div>
                <p class="text-xs text-amber-400/80 uppercase tracking-widest font-cinzel">${cat.titleEn}</p>
                <p class="text-xs sm:text-sm text-gray-400 leading-relaxed pt-1">
                  ${cat.description}
                </p>
              </div>
            </a>
          `).join('')}
        </div>
      </div>
    `;
  }
}

// Toggle Collaborations Unfold/Fold Function
function toggleCollaborations() {
  const wrapper = document.getElementById('collab-grid-wrapper');
  const overlay = document.getElementById('collab-gradient-overlay');
  const btnText = document.getElementById('collab-btn-text');
  const btnIcon = document.getElementById('collab-btn-icon');

  if (!wrapper) return;

  isCollabExpanded = !isCollabExpanded;

  if (isCollabExpanded) {
    wrapper.style.maxHeight = (wrapper.scrollHeight + 40) + 'px';
    if (overlay) overlay.classList.add('opacity-0');
    if (btnText) btnText.innerText = '收起經歷';
    if (btnIcon) btnIcon.classList.add('rotate-180');
  } else {
    wrapper.style.maxHeight = '340px';
    if (overlay) overlay.classList.remove('opacity-0');
    if (btnText) {
      const count = window.PORTFOLIO_DATA?.collaborations?.length || '';
      btnText.innerText = count ? `顯示更多經歷 (${count})` : '顯示更多經歷';
    }
    if (btnIcon) btnIcon.classList.remove('rotate-180');
    
    // Smooth scroll back to collaborations section top
    const collabSection = document.getElementById('collaborations-section');
    if (collabSection) {
      collabSection.scrollIntoView({ behavior: 'smooth' });
    }
  }
}

// Toggle Awards Unfold/Fold Function
function toggleAwards() {
  const wrapper = document.getElementById('awards-grid-wrapper');
  const overlay = document.getElementById('awards-gradient-overlay');
  const btnText = document.getElementById('awards-btn-text');
  const btnIcon = document.getElementById('awards-btn-icon');

  if (!wrapper) return;

  isAwardsExpanded = !isAwardsExpanded;

  if (isAwardsExpanded) {
    wrapper.style.maxHeight = (wrapper.scrollHeight + 40) + 'px';
    if (overlay) overlay.classList.add('opacity-0');
    if (btnText) btnText.innerText = '收起獲獎紀錄';
    if (btnIcon) btnIcon.classList.add('rotate-180');
  } else {
    wrapper.style.maxHeight = '330px';
    if (overlay) overlay.classList.remove('opacity-0');
    if (btnText) {
      const count = window.PORTFOLIO_DATA?.awards?.length || '';
      btnText.innerText = count ? `顯示更多獲獎紀錄 (${count})` : '顯示更多獲獎紀錄';
    }
    if (btnIcon) btnIcon.classList.remove('rotate-180');

    // Smooth scroll back to awards section top
    const awardsSection = document.getElementById('awards-section');
    if (awardsSection) {
      awardsSection.scrollIntoView({ behavior: 'smooth' });
    }
  }
}

// --------------------------------------------------------------------
// 2. Render Category Gallery Page
// --------------------------------------------------------------------
function renderCategoryPage(categoryId) {
  const data = window.PORTFOLIO_DATA;
  if (!data) {
    console.error("PORTFOLIO_DATA is not defined. Please check js/portfolio-data.js for syntax errors.");
    const galleryGrid = document.getElementById('gallery-grid');
    if (galleryGrid) {
      galleryGrid.innerHTML = `
        <div class="col-span-full max-w-4xl mx-auto px-6 py-20 text-center">
          <div class="p-6 bg-red-500/10 border border-red-500/30 rounded-xl text-red-300 space-y-3">
            <h3 class="text-xl font-bold">⚠️ 資料讀取失敗 (Data Load Error)</h3>
            <p class="text-sm"><code>js/portfolio-data.js</code> 檔案中可能有語法錯誤（例如新增相簿時物件之間缺少逗號 <code>,</code> 或單雙引號未成對）。</p>
            <p class="text-xs text-gray-400">請開啟瀏覽器開發者工具 (F12) 的 Console 檢視詳細錯誤行數。</p>
          </div>
        </div>
      `;
    }
    return;
  }

  const categoryObj = data.categories.find(c => c.id === categoryId);
  const projects = data.galleries[categoryId] || [];

  // Category Header Banner
  const headerContainer = document.getElementById('category-header-container');
  if (headerContainer && categoryObj) {
    headerContainer.innerHTML = `
      <div class="max-w-6xl mx-auto px-6 pt-24 pb-10 text-center space-y-4">
        <p class="text-amber-400 text-xs sm:text-sm font-semibold tracking-widest uppercase">
          ${categoryObj.badge}
        </p>
        <h1 class="text-4xl sm:text-5xl font-bold font-serif-title title-gradient-text">
          ${categoryObj.title}
        </h1>
        <p class="text-gray-400 text-sm sm:text-base max-w-xl mx-auto">
          ${categoryObj.description}
        </p>

        <!-- Category Switching Bar -->
        <div class="pt-6 max-w-4xl mx-auto">
          <div class="category-tab-wrapper">
            <div class="category-tab-bar">
              <a href="index.html" class="category-tab-item">首頁</a>
              ${data.categories.map(cat => `
                <a href="${cat.pageUrl}" class="category-tab-item ${cat.id === categoryId ? 'active' : ''}">
                  ${cat.title}
                </a>
              `).join('')}
            </div>
          </div>
        </div>
      </div>
    `;

    // Auto-scroll active category tab into center view on mobile/desktop
    const activeTab = headerContainer.querySelector('.category-tab-item.active');
    const tabBar = headerContainer.querySelector('.category-tab-bar');
    if (activeTab && tabBar) {
      setTimeout(() => {
        activeTab.scrollIntoView({ behavior: 'smooth', block: 'nearest', inline: 'center' });
      }, 50);
    }
  }

  // Gallery Projects Grid
  const galleryGrid = document.getElementById('gallery-grid');
  if (galleryGrid) {
    if (projects.length === 0) {
      galleryGrid.innerHTML = `
        <div class="col-span-full text-center py-20 text-gray-500">
          <p class="text-lg">目前尚無此分類照片</p>
        </div>
      `;
      return;
    }

    galleryGrid.innerHTML = projects.map(proj => {
      const coverImg = proj.cover || (proj.photos && proj.photos[0]) || proj.image;
      const photoCount = (proj.photos && proj.photos.length) ? proj.photos.length : 1;
      const imgStyle = getImageStyle(proj);
      
      return `
        <div class="gallery-item group" onclick="openProjectAlbum('${proj.id}', '${categoryId}')">
          <div class="image-hover-zoom w-full h-80 sm:h-96">
            <img src="${coverImg}" alt="${proj.title}" draggable="false" style="${imgStyle}" />
          </div>
          <div class="gallery-item-overlay">
            <div class="gallery-item-info space-y-1">
              <div class="flex items-center justify-between text-xs text-amber-400 font-semibold tracking-wider">
                <span>${proj.client ? proj.client : categoryObj?.title}</span>
                <span class="px-2 py-0.5 rounded bg-black/60 border border-amber-500/30 text-[10px] flex items-center gap-1">
                  <svg class="w-3 h-3 text-amber-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z"/></svg>
                  ${photoCount} 張照片
                </span>
              </div>
              <h3 class="text-xl font-bold text-white font-serif-title">${proj.title}</h3>
              ${proj.description ? `<p class="text-xs text-gray-300 line-clamp-2">${proj.description}</p>` : ''}
            </div>
          </div>
        </div>
      `;
    }).join('');
  }
}

// --------------------------------------------------------------------
// 3. Render Contact Page
// --------------------------------------------------------------------
function renderContactPage() {
  const data = window.PORTFOLIO_DATA;
  const container = document.getElementById('contact-content');
  if (!container || !data) return;

  container.innerHTML = `
    <div class="max-w-4xl mx-auto px-6 pt-32 sm:pt-40 pb-20 grid grid-cols-1 lg:grid-cols-12 gap-12">
      <!-- Contact Info -->
      <div class="lg:col-span-5 space-y-6">
        <h1 class="text-4xl font-bold font-serif-title title-gradient-text">
          預約與聯絡
        </h1>
        <p class="text-gray-400 text-sm leading-relaxed">
          歡迎商業廣告合作、演唱會紀錄、個人寫真與活動拍攝預約。請填寫右側表單或透過下方管道直接聯繫。
        </p>

        <!-- Contact Links (IG and Email icons identical to footer icons, Location removed) -->
        <div class="space-y-5 pt-4 border-t border-white/10 text-sm">
          <!-- Email Row -->
          <div class="flex items-center gap-4">
            <a href="mailto:weipic2023@gmail.com" class="text-gray-300 hover:text-amber-400 transition-colors p-1 flex items-center justify-center shrink-0" aria-label="Email Me">
              <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="2.5 5.3 19 12.4">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.8" d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z"/>
              </svg>
            </a>
            <div>
              <p class="text-xs text-gray-500 uppercase tracking-wider">EMAIL</p>
              <a href="mailto:weipic2023@gmail.com" class="font-medium text-white hover:text-amber-400 transition-colors">weipic2023@gmail.com</a>
            </div>
          </div>

          <!-- Instagram Row -->
          <div class="flex items-center gap-4">
            <a href="https://www.instagram.com/wei.pictures/" target="_blank" rel="noopener noreferrer" class="text-gray-300 hover:text-amber-400 transition-colors p-1 flex items-center justify-center shrink-0" aria-label="Instagram">
              <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 24 24">
                <path d="M12 2.163c3.204 0 3.584.012 4.85.07 3.252.148 4.771 1.691 4.919 4.919.058 1.265.069 1.645.069 4.849 0 3.205-.012 3.584-.069 4.849-.149 3.225-1.664 4.771-4.919 4.919-1.266.058-1.644.07-4.85.07-3.204 0-3.584-.012-4.849-.07-3.26-.149-4.771-1.699-4.919-4.92-.058-1.265-.07-1.644-.07-4.849 0-3.204.013-3.583.07-4.849.149-3.227 1.664-4.771 4.919-4.919 1.266-.057 1.645-.069 4.849-.069zm0-2.163c-3.259 0-3.667.014-4.947.072-4.358.2-6.78 2.618-6.98 6.98-.059 1.281-.073 1.689-.073 4.948 0 3.259.014 3.668.072 4.948.2 4.358 2.618 6.78 6.98 6.98 1.281.058 1.689.072 4.948.072 3.259 0 3.668-.014 4.948-.072 4.354-.2 6.782-2.618 6.979-6.98.059-1.28.073-1.689.073-4.948 0-3.259-.014-3.667-.072-4.947-.196-4.354-2.617-6.78-6.979-6.98-1.281-.059-1.69-.073-4.949-.073zm0 5.838c-3.403 0-6.162 2.759-6.162 6.162s2.759 6.163 6.162 6.163 6.162-2.759 6.162-6.163c0-3.403-2.759-6.162-6.162-6.162zm0 10.162c-2.209 0-4-1.79-4-4 0-2.209 1.791-4 4-4s4 1.791 4 4c0 2.21-1.791 4-4 4zm6.406-11.845c-.796 0-1.441.645-1.441 1.44s.645 1.44 1.441 1.44c.795 0 1.439-.645 1.439-1.44s-.644-1.44-1.439-1.44z"/>
              </svg>
            </a>
            <div>
              <p class="text-xs text-gray-500 uppercase tracking-wider">INSTAGRAM</p>
              <a href="https://www.instagram.com/wei.pictures/" target="_blank" rel="noopener noreferrer" class="font-medium text-white hover:text-amber-400 transition-colors">@wei.pictures</a>
            </div>
          </div>
        </div>
      </div>

      <!-- Form -->
      <div class="lg:col-span-7 luxury-card p-8">
        <form id="contact-form" onsubmit="handleFormSubmit(event)" class="space-y-5">
          <div>
            <label class="block text-xs text-gray-400 uppercase tracking-wider mb-2 font-medium">您的姓名 *</label>
            <input type="text" id="contact-name" name="name" required placeholder="例如：陳小姐" class="w-full bg-black/50 border border-white/10 rounded-lg px-4 py-3 text-white text-sm focus:outline-none focus:border-amber-400 transition-colors" />
          </div>

          <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label class="block text-xs text-gray-400 uppercase tracking-wider mb-2 font-medium">聯絡信箱 *</label>
              <input type="email" id="contact-email" name="email" required placeholder="name@example.com" class="w-full bg-black/50 border border-white/10 rounded-lg px-4 py-3 text-white text-sm focus:outline-none focus:border-amber-400 transition-colors" />
            </div>
            <div>
              <label class="block text-xs text-gray-400 uppercase tracking-wider mb-2 font-medium">拍攝類別</label>
              <select id="contact-category" name="category" class="w-full bg-black/50 border border-white/10 rounded-lg px-4 py-3 text-white text-sm focus:outline-none focus:border-amber-400 transition-colors">
                ${data.categories.map(c => `<option value="${c.title}">${c.title}</option>`).join('')}
              </select>
            </div>
          </div>

          <div>
            <label class="block text-xs text-gray-400 uppercase tracking-wider mb-2 font-medium">專案細節與預算需求 *</label>
            <textarea id="contact-message" name="message" rows="5" required placeholder="請簡述您的拍攝需求、預計日期與地點..." class="w-full bg-black/50 border border-white/10 rounded-lg px-4 py-3 text-white text-sm focus:outline-none focus:border-amber-400 transition-colors"></textarea>
          </div>

          <div id="form-status-msg" class="hidden text-xs py-2 px-3 rounded-lg"></div>

          <button type="submit" id="contact-submit-btn" class="w-full btn-gold flex items-center justify-center gap-2">
            <span>送出預約表單</span>
          </button>
        </form>
      </div>
    </div>
  `;
}

async function handleFormSubmit(e) {
  e.preventDefault();
  
  const submitBtn = document.getElementById('contact-submit-btn');
  const statusMsg = document.getElementById('form-status-msg');
  const form = e.target;

  const name = document.getElementById('contact-name').value;
  const email = document.getElementById('contact-email').value;
  const category = document.getElementById('contact-category').value;
  const message = document.getElementById('contact-message').value;

  if (submitBtn) {
    submitBtn.disabled = true;
    submitBtn.innerHTML = `
      <svg class="animate-spin h-4 w-4 text-black" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
        <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
        <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
      </svg>
      <span>傳送中...</span>
    `;
  }

  try {
    const response = await fetch('https://formsubmit.co/ajax/weipic2023@gmail.com', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Accept': 'application/json'
      },
      body: JSON.stringify({
        _subject: `【Wei's Portfolio】新攝影預約詢問 - ${name}`,
        姓名: name,
        電子信箱: email,
        預約類別: category,
        需求與細節: message
      })
    });

    const data = await response.json();

    if (response.ok || data.success === "true") {
      if (statusMsg) {
        statusMsg.className = 'text-xs py-3 px-4 rounded-lg bg-emerald-500/20 border border-emerald-500/40 text-emerald-300 font-medium block';
        statusMsg.innerText = '✅ 預約訊息已成功送出！將會於 24 小時內與您聯繫。';
      }
      form.reset();
    } else {
      throw new Error(data.message || '發送失敗');
    }
  } catch (error) {
    console.error('Form submission error:', error);
    if (statusMsg) {
      statusMsg.className = 'text-xs py-3 px-4 rounded-lg bg-red-500/20 border border-red-500/40 text-red-300 font-medium block';
      statusMsg.innerText = '⚠️ 送出失敗，請再試一次或直接寄信至 weipic2023@gmail.com';
    }
  } finally {
    if (submitBtn) {
      submitBtn.disabled = false;
      submitBtn.innerHTML = `<span>送出預約表單</span>`;
    }
  }
}

// --------------------------------------------------------------------
// 4. Multi-photo Project Album & Lightbox Modal with < > Nav Arrows
// --------------------------------------------------------------------
function openProjectAlbum(projectId, categoryId) {
  const data = window.PORTFOLIO_DATA;
  if (!data || !data.galleries[categoryId]) return;

  const project = data.galleries[categoryId].find(p => p.id === projectId);
  if (!project) return;

  currentAlbumPhotos = (project.photos && project.photos.length) ? project.photos : [project.cover || project.image];
  currentPhotoIndex = 0;

  let modal = document.getElementById('lightbox-modal');
  if (!modal) {
    modal = document.createElement('div');
    modal.id = 'lightbox-modal';
    modal.className = 'fixed inset-0 z-[999] bg-black/95 backdrop-blur-md flex items-center justify-center p-3 sm:p-6 transition-opacity duration-300 opacity-0 pointer-events-none';
    document.body.appendChild(modal);
  }

  renderModalContent(project);

  modal.classList.remove('opacity-0', 'pointer-events-none');
  modal.classList.add('opacity-100');

  window.addEventListener('keydown', handleLightboxKeyboard);
}

function renderModalContent(project) {
  const modal = document.getElementById('lightbox-modal');
  if (!modal) return;

  const total = currentAlbumPhotos.length;
  const currentPhotoSrc = currentAlbumPhotos[currentPhotoIndex];
  const customPos = project.position ? `object-position: ${project.position};` : '';

  modal.innerHTML = `
    <div class="relative max-w-6xl w-full max-h-[92vh] sm:max-h-[90vh] bg-[#101116] border border-white/10 rounded-2xl overflow-hidden shadow-2xl flex flex-col md:flex-row">
      
      <!-- Top Right Floating Fixed Close Button (Ensures X is NEVER blocked on mobile) -->
      <button onclick="closeLightbox()" class="absolute top-3 right-3 z-50 w-9 h-9 sm:w-10 sm:h-10 rounded-full bg-black/75 border border-white/20 text-gray-200 hover:text-amber-400 hover:border-amber-400 flex items-center justify-center text-xl transition-all shadow-xl" aria-label="Close Lightbox">
        &times;
      </button>

      <!-- Main Photo Display Area with Previous/Next Arrows -->
      <div class="md:w-3/4 bg-black flex items-center justify-center p-3 sm:p-5 relative min-h-[280px] sm:min-h-[400px] md:min-h-[550px] overflow-hidden group">
        
        <!-- Main Image (Supports custom object-position & vertical image boundaries on mobile) -->
        <img id="modal-main-img" src="${currentPhotoSrc}" alt="${project.title}" draggable="false" style="${customPos}" class="max-h-[48vh] sm:max-h-[65vh] md:max-h-[76vh] w-auto max-w-full object-contain rounded-lg shadow-xl transition-all duration-300" />

        <!-- Left Nav Arrow (<) -->
        ${total > 1 ? `
          <button onclick="navigatePhoto(-1)" class="modal-nav-btn absolute left-3 sm:left-4 top-1/2" aria-label="Previous Photo">
            <svg class="w-5 h-5 sm:w-6 sm:h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2.5" d="M15 19l-7-7 7-7"/></svg>
          </button>
        ` : ''}

        <!-- Right Nav Arrow (>) -->
        ${total > 1 ? `
          <button onclick="navigatePhoto(1)" class="modal-nav-btn absolute right-3 sm:right-4 top-1/2" aria-label="Next Photo">
            <svg class="w-5 h-5 sm:w-6 sm:h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2.5" d="M9 5l7 7-7 7"/></svg>
          </button>
        ` : ''}

        <!-- Photo Counter Badge -->
        ${total > 1 ? `
          <div class="absolute bottom-3 left-3 sm:bottom-4 sm:left-4 bg-black/70 border border-white/15 px-3 py-1 rounded-full text-xs font-mono text-amber-400">
            <span id="photo-counter">${currentPhotoIndex + 1}</span> / ${total}
          </div>
        ` : ''}
      </div>

      <!-- Detail Sidebar & Scrollable Multi-Photo List -->
      <div class="md:w-1/4 p-5 sm:p-6 flex flex-col justify-between border-t md:border-t-0 md:border-l border-white/10 bg-[#0d0e12] overflow-y-auto max-h-[42vh] md:max-h-[88vh]">
        <div class="space-y-4">
          <div class="flex items-center justify-between">
            <span class="text-xs font-semibold text-amber-400 tracking-wider uppercase">${project.client || 'FEATURED WORK'} · ${project.year || ''}</span>
          </div>

          <h2 class="text-xl sm:text-2xl font-bold font-serif-title text-white">${project.title}</h2>
          ${project.description ? `<p class="text-xs text-gray-300 leading-relaxed">${project.description}</p>` : ''}

          <!-- Multi-photo Series List (向下滑動看本作品所有照片) -->
          ${total > 1 ? `
            <div class="pt-3 border-t border-white/10 space-y-2">
              <p class="text-xs text-amber-400 font-medium tracking-wider uppercase">照片輯 (點擊切換 / 向下滑動)</p>
              <div class="grid grid-cols-3 gap-2 pt-1 max-h-[22vh] overflow-y-auto pr-1">
                ${currentAlbumPhotos.map((src, idx) => `
                  <button onclick="switchPhotoIndex(${idx})" class="w-full h-14 sm:h-16 rounded-md overflow-hidden image-hover-zoom border ${idx === currentPhotoIndex ? 'border-amber-400 ring-2 ring-amber-400/30' : 'border-white/10 opacity-70 hover:opacity-100'} transition-all">
                    <img src="${src}" draggable="false" style="${getImageStyle(project)}" />
                  </button>
                `).join('')}
              </div>
            </div>
          ` : ''}

          <!-- Custom Link Buttons (可自訂顯示名稱並導向指定網址) -->
          ${(Array.isArray(project.links) && project.links.length > 0) ? `
            <div class="pt-3 border-t border-white/10 space-y-2">
              <p class="text-xs text-amber-400 font-medium tracking-wider uppercase">相關連結</p>
              <div class="flex flex-col gap-2 pt-1">
                ${project.links.map(link => `
                  <a href="${link.url}" target="_blank" rel="noopener noreferrer" class="flex items-center justify-between px-3 py-2 text-xs text-amber-400 hover:text-black bg-amber-500/10 hover:bg-amber-400 border border-amber-500/30 rounded-lg transition-all font-medium no-underline group">
                    <span class="truncate">${link.label || '觀看相關連結'}</span>
                    <svg class="w-3.5 h-3.5 flex-shrink-0 transition-transform group-hover:translate-x-0.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14"/></svg>
                  </a>
                `).join('')}
              </div>
            </div>
          ` : (project.link ? `
            <div class="pt-3 border-t border-white/10 space-y-2">
              <p class="text-xs text-amber-400 font-medium tracking-wider uppercase">相關連結</p>
              <div class="pt-1">
                <a href="${project.link}" target="_blank" rel="noopener noreferrer" class="flex items-center justify-between px-3 py-2 text-xs text-amber-400 hover:text-black bg-amber-500/10 hover:bg-amber-400 border border-amber-500/30 rounded-lg transition-all font-medium no-underline group">
                  <span class="truncate">${project.linkLabel || '觀看相關連結'}</span>
                  <svg class="w-3.5 h-3.5 flex-shrink-0 transition-transform group-hover:translate-x-0.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14"/></svg>
                </a>
              </div>
            </div>
          ` : '')}
        </div>

        <div class="pt-4">
          <button onclick="closeLightbox()" class="w-full btn-outline text-xs">
            關閉檢視
          </button>
        </div>
      </div>

    </div>
  `;
}

function navigatePhoto(direction) {
  if (currentAlbumPhotos.length <= 1) return;
  currentPhotoIndex = (currentPhotoIndex + direction + currentAlbumPhotos.length) % currentAlbumPhotos.length;

  const mainImg = document.getElementById('modal-main-img');
  const counter = document.getElementById('photo-counter');

  if (mainImg) mainImg.src = currentAlbumPhotos[currentPhotoIndex];
  if (counter) counter.innerText = currentPhotoIndex + 1;

  // Highlight thumbnail
  updateActiveThumbnail();
}

function switchPhotoIndex(idx) {
  if (idx < 0 || idx >= currentAlbumPhotos.length) return;
  currentPhotoIndex = idx;

  const mainImg = document.getElementById('modal-main-img');
  const counter = document.getElementById('photo-counter');

  if (mainImg) mainImg.src = currentAlbumPhotos[currentPhotoIndex];
  if (counter) counter.innerText = currentPhotoIndex + 1;

  updateActiveThumbnail();
}

function updateActiveThumbnail() {
  const thumbs = document.querySelectorAll('#lightbox-modal button[onclick^="switchPhotoIndex"]');
  thumbs.forEach((btn, idx) => {
    if (idx === currentPhotoIndex) {
      btn.className = 'w-full h-14 sm:h-16 rounded-md overflow-hidden border border-amber-400 ring-2 ring-amber-400/30 transition-all';
    } else {
      btn.className = 'w-full h-14 sm:h-16 rounded-md overflow-hidden border border-white/10 opacity-70 hover:opacity-100 transition-all';
    }
  });
}

function closeLightbox() {
  const modal = document.getElementById('lightbox-modal');
  if (modal) {
    modal.classList.add('opacity-0', 'pointer-events-none');
    modal.classList.remove('opacity-100');
  }
  window.removeEventListener('keydown', handleLightboxKeyboard);
}

function handleLightboxKeyboard(e) {
  if (e.key === 'Escape') closeLightbox();
  if (e.key === 'ArrowLeft') navigatePhoto(-1);
  if (e.key === 'ArrowRight') navigatePhoto(1);
}

function initNavbarScroll() {
  const header = document.querySelector('header');
  if (!header) return;

  window.addEventListener('scroll', () => {
    if (window.scrollY > 50) {
      header.classList.add('py-3');
      header.classList.remove('py-5');
    } else {
      header.classList.add('py-5');
      header.classList.remove('py-3');
    }
  });
}

function initMobileMenu() {
  const btn = document.getElementById('mobile-menu-btn');
  const menu = document.getElementById('mobile-menu');
  if (btn && menu) {
    btn.addEventListener('click', () => {
      menu.classList.toggle('hidden');
    });
  }
}

/* ====================================================================
   📱 MOBILE TOUCH HOVER & TAP INTERACTION LOGIC
   ==================================================================== */
function initMobileTouchHover() {
  let activeCard = null;
  let startX = 0;
  let startY = 0;
  let isScrolling = false;
  let fadeTimeout = null;

  function clearActiveCard() {
    if (activeCard) {
      activeCard.classList.remove('touch-active');
      activeCard = null;
    }
  }

  function getCardFromTouch(touch) {
    if (!touch) return null;
    const target = document.elementFromPoint(touch.clientX, touch.clientY);
    return target ? target.closest('.luxury-card, .gallery-item') : null;
  }

  document.addEventListener('touchstart', (e) => {
    if (e.touches.length !== 1) return;
    const touch = e.touches[0];
    startX = touch.clientX;
    startY = touch.clientY;
    isScrolling = false;

    if (fadeTimeout) {
      clearTimeout(fadeTimeout);
      fadeTimeout = null;
    }

    const card = getCardFromTouch(touch);
    if (card) {
      if (activeCard && activeCard !== card) {
        activeCard.classList.remove('touch-active');
      }
      activeCard = card;
      activeCard.classList.add('touch-active');
    }
  }, { passive: true });

  document.addEventListener('touchmove', (e) => {
    if (e.touches.length !== 1) return;
    const touch = e.touches[0];
    const dx = Math.abs(touch.clientX - startX);
    const dy = Math.abs(touch.clientY - startY);

    if (dx > 8 || dy > 8) {
      isScrolling = true;
    }

    const card = getCardFromTouch(touch);
    if (card) {
      if (activeCard && activeCard !== card) {
        activeCard.classList.remove('touch-active');
      }
      activeCard = card;
      activeCard.classList.add('touch-active');
    } else {
      if (activeCard) {
        activeCard.classList.remove('touch-active');
        activeCard = null;
      }
    }
  }, { passive: true });

  document.addEventListener('touchend', () => {
    if (isScrolling) {
      fadeTimeout = setTimeout(() => {
        clearActiveCard();
      }, 400);
    } else {
      fadeTimeout = setTimeout(() => {
        clearActiveCard();
      }, 300);
    }
  }, { passive: true });

  document.addEventListener('touchcancel', () => {
    clearActiveCard();
  }, { passive: true });

  document.addEventListener('click', (e) => {
    if (isScrolling) {
      e.preventDefault();
      e.stopPropagation();
      isScrolling = false;
    }
  }, true);
}

/* ====================================================================
   🌐 GOOGLE TRANSLATE & MULTI-LANGUAGE LOGIC
   ==================================================================== */
window.googleTranslateElementInit = function() {
  new google.translate.TranslateElement({
    pageLanguage: 'zh-TW',
    includedLanguages: 'zh-TW,en,ja',
    layout: google.translate.TranslateElement.InlineLayout.SIMPLE,
    autoDisplay: false
  }, 'google_translate_element');
};

window.setLanguage = function(langCode) {
  const currentDomain = window.location.hostname;
  
  if (langCode === 'zh-TW') {
    document.cookie = "googtrans=; expires=Thu, 01 Jan 1970 00:00:00 UTC; path=/;";
    document.cookie = "googtrans=/zh-TW/zh-TW; path=/;";
    if (currentDomain) {
      document.cookie = `googtrans=; expires=Thu, 01 Jan 1970 00:00:00 UTC; domain=${currentDomain}; path=/;`;
      document.cookie = `googtrans=; expires=Thu, 01 Jan 1970 00:00:00 UTC; domain=.${currentDomain}; path=/;`;
    }
  } else {
    const val = `/zh-TW/${langCode}`;
    document.cookie = `googtrans=${val}; path=/;`;
    if (currentDomain) {
      document.cookie = `googtrans=${val}; domain=${currentDomain}; path=/;`;
      document.cookie = `googtrans=${val}; domain=.${currentDomain}; path=/;`;
    }
  }
  
  localStorage.setItem('selected_lang', langCode);

  const triggerChange = () => {
    const selectElem = document.querySelector('.goog-te-combo');
    if (selectElem) {
      selectElem.value = langCode;
      selectElem.dispatchEvent(new Event('change'));
      return true;
    }
    return false;
  };

  if (!triggerChange()) {
    setTimeout(triggerChange, 300);
    setTimeout(triggerChange, 800);
  }

  updateLanguageUIState(langCode);
  window.location.reload();
};

function updateLanguageUIState(langCode) {
  const activeLang = langCode || localStorage.getItem('selected_lang') || 'zh-TW';
  const allLangBtns = document.querySelectorAll('.lang-opt-btn');
  
  allLangBtns.forEach(btn => {
    const targetLang = btn.getAttribute('data-lang');
    if (targetLang === activeLang) {
      btn.classList.add('text-amber-400', 'font-semibold');
      btn.classList.remove('text-gray-300');
    } else {
      btn.classList.remove('text-amber-400', 'font-semibold');
      btn.classList.add('text-gray-300');
    }
  });
}

function initLanguageSelector() {
  if (!document.getElementById('google_translate_element')) {
    const div = document.createElement('div');
    div.id = 'google_translate_element';
    div.style.display = 'none';
    document.body.appendChild(div);
  }

  if (!document.getElementById('google-translate-script')) {
    const script = document.createElement('script');
    script.id = 'google-translate-script';
    script.src = 'https://translate.google.com/translate_a/element.js?cb=googleTranslateElementInit';
    document.body.appendChild(script);
  }

  const langBtn = document.getElementById('lang-btn');
  const langMenu = document.getElementById('lang-dropdown-menu');

  if (langBtn && langMenu) {
    langBtn.addEventListener('click', (e) => {
      e.stopPropagation();
      langMenu.classList.toggle('show');
    });

    document.addEventListener('click', (e) => {
      if (!langBtn.contains(e.target) && !langMenu.contains(e.target)) {
        langMenu.classList.remove('show');
      }
    });
  }

  const storedLang = localStorage.getItem('selected_lang') || 'zh-TW';
  updateLanguageUIState(storedLang);
}

// --------------------------------------------------------------------
// Image Protection: Prevent right-click, dragging & long-press download
// --------------------------------------------------------------------
function initProtectImages() {
  // 1. Prevent right-click context menu (Desktop right-click & Mobile long-press)
  document.addEventListener('contextmenu', (e) => {
    if (e.target.tagName === 'IMG' || e.target.closest('img') || e.target.closest('.image-hover-zoom') || e.target.closest('#lightbox-modal')) {
      e.preventDefault();
      return false;
    }
  }, { capture: true });

  // 2. Prevent dragging images to save or open in new tab
  document.addEventListener('dragstart', (e) => {
    if (e.target.tagName === 'IMG' || e.target.closest('img') || e.target.closest('.image-hover-zoom') || e.target.closest('#lightbox-modal')) {
      e.preventDefault();
      return false;
    }
  }, { capture: true });

  // 3. Ensure draggable="false" on all img elements (current & dynamically appended)
  const applyNoDrag = (rootNode = document) => {
    if (!rootNode) return;
    if (rootNode.tagName === 'IMG') {
      rootNode.setAttribute('draggable', 'false');
    }
    if (rootNode.querySelectorAll) {
      rootNode.querySelectorAll('img').forEach(img => {
        img.setAttribute('draggable', 'false');
      });
    }
  };

  applyNoDrag(document);

  // Observer to catch any dynamically added image elements (like Lightbox modal)
  const observer = new MutationObserver((mutations) => {
    mutations.forEach(mutation => {
      mutation.addedNodes.forEach(node => {
        if (node.nodeType === 1) {
          applyNoDrag(node);
        }
      });
    });
  });

  observer.observe(document.body || document.documentElement, { childList: true, subtree: true });
}

