/* Generated by scripts/build-locales.mjs. */
window.PORTFOLIO_DATA = {
  "profile": {
    "name": "WEI",
    "subTitle": "フリーランスフォトグラファー",
    "tagline": "",
    "avatar": "../assets/images/profile/avatar.webp",
    "location": "台湾・台北",
    "email": "weipic2023@gmail.com",
    "instagram": "https://www.instagram.com/wei.pictures/",
    "instagramHandle": "@wei.pictures",
    "experienceYears": "2+",
    "stats": [
      {
        "label": "Instagram フォロワー",
        "value": "7000+"
      },
      {
        "label": "撮影歴",
        "value": "2+"
      },
      {
        "label": "合作実績",
        "value": "20+"
      },
      {
        "label": "写真賞",
        "value": "7+"
      }
    ],
    "bio": [
      "Weiと申します。18歳、撮影歴は約2年です。さまざまな題材に挑戦しながら、光と影、そして物語の可能性を探っています。",
      "ポートレート、風景、ストリート、スポーツ、ドキュメンタリーを幅広く撮影し、日常の一瞬一瞬を記録しています。",
      "ぜひフォローしてご覧ください。撮影のご依頼・ご相談は、メールまたは予約フォームからお気軽にお問い合わせください。",
      "<a href=\"mailto:weipic2023@gmail.com\">weipic2023@gmail.com</a>"
    ],
    "skills": [
      "商業写真",
      "ポートレート",
      "コンサートドキュメンタリー",
      "ブランド・イベント記録",
      "スポーツ写真",
      "卒業写真",
      "風景ビジュアル"
    ]
  },
  "collaborations": [
    {
      "id": "collab-23",
      "brand": "CEWE",
      "role": "CEWE Photo Award 2027 ヤングタレント賞",
      "year": "2026-2027",
      "category": "国際写真賞",
      "description": "公式サイトカバー写真｜商業コラボレーション",
      "logoText": "CEWE",
      "photos": [
        "../assets/images/collaboration/cewe.webp"
      ],
      "links": [
        {
          "label": "CEWE Photo Award",
          "url": "https://contest.cewe.co.uk/cewephotoaward2027/en_gb/youngtalentaward"
        }
      ]
    },
    {
      "id": "collab-22",
      "brand": "Gogoro",
      "role": "2026 オーナーイベント「ポップアップ・スペースシティ」",
      "year": "2026",
      "category": "ブランドコラボレーション",
      "description": "KOC SNSプロモーション・限定特典告知｜商業コラボレーション",
      "logoText": "Gogoro",
      "photos": [
        "../assets/images/collaboration/gogoro_story.webp"
      ],
      "links": [
        {
          "label": "Gogoro 2026「百 GO ナイトライド」",
          "url": "https://gogoro2026.oen.tw/events/3FD6X11DEssBRUmforgCWj1wVou"
        }
      ]
    },
    {
      "id": "collab-21",
      "brand": "TAMRON",
      "role": "25-200mm f/2.8-5.6 Di III VXD G2",
      "year": "2026",
      "category": "商業",
      "description": "レンズレビュー",
      "logoText": "TAMRON",
      "galleryId": "comm-9"
    },
    {
      "id": "collab-20",
      "brand": "青年写真賞",
      "role": "第13回全国大学ユースフォトアワード",
      "year": "2026",
      "category": "コンテスト",
      "description": "学生審査員、廖文瑄先生 @ontheay.today と参加",
      "logoText": "青年写真賞",
      "photos": [
        "../assets/images/collaboration/ntutphotoclub.webp"
      ]
    },
    {
      "id": "collab-19",
      "brand": "SITCON",
      "role": "SITCON 2026",
      "year": "2026",
      "category": "イベント記録",
      "description": "中央研究院｜イベント記録",
      "logoText": "SITCON",
      "galleryId": "ev-5"
    },
    {
      "id": "collab-18",
      "brand": "CyberCube",
      "role": "2026 台北市高校進学・キャリアフェア",
      "year": "2026",
      "category": "イベント記録",
      "description": "CyberCube｜イベント記録",
      "logoText": "CyberCube",
      "galleryId": "ev-7"
    },
    {
      "id": "collab-17",
      "brand": "LiFUNd",
      "role": "LiFUNd 第3回「夢の出航」",
      "year": "2026",
      "category": "イベント記録",
      "description": "ソーシャルイノベーションラボ｜イベント記録",
      "logoText": "LiFUNd",
      "galleryId": "ev-4"
    },
    {
      "id": "collab-16",
      "brand": "Gaston Luga",
      "role": "Spläsh 2.0 - 16, Sage",
      "year": "2026",
      "category": "商業",
      "description": "ブランドコラボレーション",
      "logoText": "Gaston Luga",
      "galleryId": "comm-2"
    },
    {
      "id": "collab-15",
      "brand": "Threads",
      "role": "第1回アメリカンスタイル卒業プロム＆春のガラディナー",
      "year": "2026",
      "category": "イベント記録",
      "description": "2026 Threads' Party｜イベント記録",
      "logoText": "Threads",
      "galleryId": "ev-6"
    },
    {
      "id": "collab-14",
      "brand": "国立台北科技大学",
      "role": "台北科技大学創立114周年記念式典",
      "year": "2025",
      "category": "イベント記録",
      "description": "卓越した貢献を称える同窓生表彰｜イベント記録",
      "logoText": "国立台北科技大学",
      "galleryId": "ev-2"
    },
    {
      "id": "collab-13",
      "brand": "NTUT COLAZ",
      "role": "クラシック・スタジアムジャケット",
      "year": "2025",
      "category": "商業",
      "description": "商業コラボレーション",
      "logoText": "NTUT COLAZ",
      "galleryId": "comm-3"
    },
    {
      "id": "collab-12",
      "brand": "HOKKI",
      "role": "No. 3 フレグランス",
      "year": "2025",
      "category": "商業",
      "description": "商業コラボレーション",
      "logoText": "HOKKI",
      "galleryId": "comm-4"
    },
    {
      "id": "collab-11",
      "brand": "Gaston Luga",
      "role": "Spläsh Utility Backpack 16, Latte",
      "year": "2025",
      "category": "商業",
      "description": "ブランドコラボレーション",
      "logoText": "Gaston Luga",
      "galleryId": "comm-1"
    },
    {
      "id": "collab-10",
      "brand": "シルホイールアーティスト・楊世豪",
      "role": "「舞極 X 唯一」｜奇美博物館",
      "year": "2025",
      "category": "大型商業公演",
      "description": "フォトグラファー",
      "logoText": "シルホイールアーティスト・楊世豪",
      "galleryId": "ev-8"
    },
    {
      "id": "collab-9",
      "brand": "TAMRON",
      "role": "20-40mm f/2.8 Di III VXD",
      "year": "2025",
      "category": "商業",
      "description": "レンズレビュー",
      "logoText": "TAMRON",
      "galleryId": "comm-8"
    },
    {
      "id": "collab-7",
      "brand": "MAHIRU",
      "role": "2025  茉ひる ASIA TOUR 『SeRendipity』in TAIPEI",
      "year": "2025",
      "category": "コンサート",
      "description": "日本の人気歌手・茉ひるアジアツアー台北公演フォトグラファー",
      "logoText": "MAHIRU",
      "galleryId": "conc-6"
    },
    {
      "id": "collab-6",
      "brand": "国立台北科技大学 Aliyan 原住民文化研究会",
      "role": "『Patikol 帰巣—Torik部落創作音楽舞踊劇』",
      "year": "2025",
      "category": "イベント記録",
      "description": "イベント記録",
      "logoText": "NTUT Aliyan",
      "galleryId": "ev-11"
    },
    {
      "id": "collab-5",
      "brand": "PNGL",
      "role": "LIGHTZIP 27–32L ロールトップバックパック",
      "year": "2025",
      "category": "商業",
      "description": "ブランドコラボレーション",
      "logoText": "PNGL",
      "galleryId": "comm-7"
    },
    {
      "id": "collab-3",
      "brand": "KASE",
      "role": "CPL III 偏光フィルターレビュー",
      "year": "2025",
      "category": "商業",
      "description": "機材レビュー",
      "logoText": "KASE"
    },
    {
      "id": "collab-2",
      "brand": "PENTAX",
      "role": "Pentax 17 フィルムカメラ",
      "year": "2024",
      "category": "商業",
      "description": "機材レビュー",
      "logoText": "PENTAX",
      "galleryId": "comm-10"
    },
    {
      "id": "collab-1",
      "brand": "Gaston Luga",
      "role": "GL × Nikon コラボバックパック",
      "year": "2024",
      "category": "商業",
      "description": "ブランドコラボレーション",
      "logoText": "Gaston Luga"
    }
  ],
  "awards": [
    {
      "id": "award-7",
      "year": "2025",
      "title": "ナショナル ジオグラフィック台湾写真コンテスト",
      "category": "ユース部門",
      "result": "ファイナリスト",
      "description": "2025 ナショナル ジオグラフィック台湾写真コンテスト・ユース部門ファイナリスト",
      "photos": [
        "../assets/images/award/國家地理台灣青年入圍.webp"
      ],
      "links": [
        {
          "label": "Instagram 投稿",
          "url": "https://www.instagram.com/p/DNqclZphgC4/"
        }
      ]
    },
    {
      "id": "award-6",
      "year": "2025",
      "title": "全国学生写真コンテスト",
      "category": "学生コンテスト",
      "result": "銅賞",
      "description": "2025 全国学生写真コンテスト銅賞",
      "photos": [
        "../assets/images/award/全國學生攝影銅獎 (1).webp",
        "../assets/images/award/全國學生攝影銅獎 (2).webp",
        "../assets/images/award/全國學生攝影銅獎 (3).webp",
        "../assets/images/award/全國學生攝影銅獎 (4).webp",
        "../assets/images/award/全國學生攝影銅獎 (5).webp"
      ],
      "links": [
        {
          "label": "Instagram 投稿",
          "url": "https://www.instagram.com/p/DJ-_kXTJV9s/?img_index=1"
        }
      ]
    },
    {
      "id": "award-5",
      "year": "2025",
      "title": "全国学生写真コンテスト",
      "category": "学生コンテスト",
      "result": "特別賞",
      "description": "2025 全国学生写真コンテスト特別賞",
      "photos": [
        "../assets/images/award/全國學生攝影特別獎 (1).webp",
        "../assets/images/award/全國學生攝影特別獎 (2).webp",
        "../assets/images/award/全國學生攝影特別獎 (3).webp",
        "../assets/images/award/全國學生攝影特別獎 (4).webp",
        "../assets/images/award/全國學生攝影特別獎 (5).webp"
      ],
      "links": [
        {
          "label": "Instagram 投稿",
          "url": "https://www.instagram.com/p/DJtfuj9hZH6/?img_index=1"
        }
      ]
    },
    {
      "id": "award-4",
      "year": "2025",
      "title": "Canon Taiwan 第6期キャンパスアンバサダー",
      "category": "キャンパスアンバサダー",
      "result": "最終選考選出",
      "description": "Canon Taiwan 第6期キャンパスフォトアンバサダー最終選考に選出"
    },
    {
      "id": "award-3",
      "year": "2025",
      "title": "全国大学ユースフォトアワード",
      "category": "大学コンテスト",
      "result": "ファイナリスト",
      "description": "2025 第12回全国大学ユースフォトアワード・ファイナリスト"
    },
    {
      "id": "award-2",
      "year": "2025",
      "title": "日本高校生写真コンテスト",
      "category": "単写真部門",
      "result": "入選",
      "description": "第12回日本高校生写真コンテスト・単写真部門入選"
    },
    {
      "id": "award-1",
      "year": "2024",
      "title": "日本高校生写真コンテスト",
      "category": "単写真部門",
      "result": "入選",
      "description": "第11回日本高校生写真コンテスト・単写真部門入選"
    }
  ],
  "categories": [
    {
      "id": "commercial",
      "title": "商業写真",
      "titleEn": "Commercial Photography",
      "description": "商品とブランドの魅力を引き出し、印象的なビジュアルを作り上げます。",
      "cover": "../assets/images/commercial/Gastonluga2 (2).webp",
      "pageUrl": "commercial.html",
      "badge": "Commercial"
    },
    {
      "id": "portrait",
      "title": "ポートレート",
      "titleEn": "Portrait Photography",
      "description": "自然な表情とその人らしさを引き出すポートレート撮影です。",
      "cover": "../assets/images/portrait/passerby (3).webp",
      "pageUrl": "portrait.html",
      "badge": "Portrait",
      "position": "40% 70%",
      "scale": 1.1
    },
    {
      "id": "concert",
      "title": "コンサート写真",
      "titleEn": "Concert Photography",
      "description": "ステージ照明、パフォーマーの迫力、会場の熱気を写し取ります。",
      "cover": "../assets/images/concert/911 (1).webp",
      "pageUrl": "concert.html",
      "badge": "Concert",
      "position": "bottom center",
      "scale": 1.3
    },
    {
      "id": "event",
      "title": "イベント写真",
      "titleEn": "Event Photography",
      "description": "イベント、発表会、企業行事の大切な瞬間を丁寧に記録します。",
      "cover": "../assets/images/event/Lulu (1).webp",
      "pageUrl": "event.html",
      "badge": "Event"
    },
    {
      "id": "sports",
      "title": "スポーツ写真",
      "titleEn": "Sports Photography",
      "description": "決定的瞬間を切り取り、競技のスピードと迫力を表現します。",
      "cover": "../assets/images/sports/WDragons0526 (1).webp",
      "pageUrl": "sports.html",
      "badge": "Sports",
      "position": "bottom center",
      "scale": 1.2
    },
    {
      "id": "graduation",
      "title": "卒業写真",
      "titleEn": "Graduation Photography",
      "description": "キャンパスや友人との写真で、青春の大切な節目を残します。",
      "cover": "../assets/images/graduation/NYCU (6).webp",
      "pageUrl": "graduation.html",
      "badge": "Graduation"
    },
    {
      "id": "landscape",
      "title": "風景写真",
      "titleEn": "Landscape Photography",
      "description": "自然の大景、壮大な山河、都市の風景を描きます。",
      "cover": "../assets/images/landscape/landscape1.webp",
      "pageUrl": "landscape.html",
      "badge": "Landscape"
    }
  ],
  "galleries": {
    "commercial": [
      {
        "id": "comm-1",
        "title": "Gaston Luga Spläsh Utility Backpack 16, Latte",
        "client": "Gaston Luga",
        "year": "2025",
        "cover": "../assets/images/commercial/Gastonluga2 (10).webp",
        "position": "center 65%",
        "links": [
          {
            "label": "ブランド公式サイト",
            "url": "https://gastonluga.com/tw"
          },
          {
            "label": "Instagram 投稿",
            "url": "https://www.instagram.com/p/DTDKdk0EnQE/?img_index=1"
          }
        ],
        "photos": [
          "../assets/images/commercial/Gastonluga2 (1).webp",
          "../assets/images/commercial/Gastonluga2 (2).webp",
          "../assets/images/commercial/Gastonluga2 (3).webp",
          "../assets/images/commercial/Gastonluga2 (4).webp",
          "../assets/images/commercial/Gastonluga2 (5).webp",
          "../assets/images/commercial/Gastonluga2 (6).webp",
          "../assets/images/commercial/Gastonluga2 (7).webp",
          "../assets/images/commercial/Gastonluga2 (8).webp",
          "../assets/images/commercial/Gastonluga2 (9).webp",
          "../assets/images/commercial/Gastonluga2 (10).webp"
        ],
        "description": "自然なラテカラーと落ち着いた陰影が織りなす北欧ミニマリズム。大容量の収納力と繊細なクラフトマンシップを引き立てます。"
      },
      {
        "id": "comm-2",
        "title": "Gaston Luga Spläsh 2.0-16, Sage",
        "client": "Gaston Luga",
        "year": "2026",
        "cover": "../assets/images/commercial/Gastonluga3 (1).webp",
        "position": "center center",
        "links": [
          {
            "label": "ブランド公式サイト",
            "url": "https://gastonluga.com/tw"
          },
          {
            "label": "Instagram 投稿",
            "url": "https://www.instagram.com/p/DVF_g4PE7zV/?img_index=1"
          }
        ],
        "photos": [
          "../assets/images/commercial/Gastonluga3 (1).webp",
          "../assets/images/commercial/Gastonluga3 (2).webp",
          "../assets/images/commercial/Gastonluga3 (3).webp",
          "../assets/images/commercial/Gastonluga3 (4).webp",
          "../assets/images/commercial/Gastonluga3 (5).webp",
          "../assets/images/commercial/Gastonluga3 (6).webp",
          "../assets/images/commercial/Gastonluga3 (7).webp",
          "../assets/images/commercial/Gastonluga3 (8).webp",
          "../assets/images/commercial/Gastonluga3 (9).webp",
          "../assets/images/commercial/Gastonluga3 (10).webp"
        ],
        "description": "機能性と品格を兼ね備えた都会的なバッグ。セージグリーンとマットブラックのディテールが、シンプルで実用的な日常のクラフト感を演出します。"
      },
      {
        "id": "comm-3",
        "title": "NTUT Colaz クラシックスタジアムジャケット",
        "client": "Colaz",
        "year": "2025",
        "cover": "../assets/images/commercial/NtutColaz (1).webp",
        "position": "center 25%",
        "links": [
          {
            "label": "Instagram 投稿",
            "url": "https://www.instagram.com/p/DRUP44EkvxO/?igsh=Z25xcWlmd2d2OXdo"
          }
        ],
        "photos": [
          "../assets/images/commercial/NtutColaz (1).webp",
          "../assets/images/commercial/NtutColaz (2).webp",
          "../assets/images/commercial/NtutColaz (3).webp",
          "../assets/images/commercial/NtutColaz (4).webp",
          "../assets/images/commercial/NtutColaz (5).webp",
          "../assets/images/commercial/NtutColaz (6).webp",
          "../assets/images/commercial/NtutColaz (7).webp",
          "../assets/images/commercial/NtutColaz (8).webp"
        ],
        "description": "台北科技大学野球部 × NTUT Colaz"
      },
      {
        "id": "comm-4",
        "title": "HOKKI No. 3 フレグランス",
        "client": "Hokki",
        "year": "2025",
        "cover": "../assets/images/commercial/Hokki (3).webp",
        "position": "center center",
        "links": [
          {
            "label": "ブランド公式サイト",
            "url": "https://hokki.shoplineapp.com/"
          },
          {
            "label": "Instagram 投稿",
            "url": "https://www.instagram.com/p/DRtAixbEgbt/?img_index=1"
          }
        ],
        "photos": [
          "../assets/images/commercial/Hokki (1).webp",
          "../assets/images/commercial/Hokki (2).webp",
          "../assets/images/commercial/Hokki (3).webp",
          "../assets/images/commercial/Hokki (4).webp",
          "../assets/images/commercial/Hokki (5).webp",
          "../assets/images/commercial/Hokki (6).webp"
        ],
        "description": "深く落ち着いたトーンで描く、ミニマルなフレグランスの美学。"
      },
      {
        "id": "comm-7",
        "title": "LIGHTZIP 27–32L 軽量ロールトップバックパック",
        "client": "PNGL",
        "year": "2025",
        "cover": "../assets/images/commercial/PNGL (3).webp",
        "position": "center 20%",
        "links": [
          {
            "label": "Instagram 投稿",
            "url": "https://www.instagram.com/p/DJloNuMpnxU/?img_index=1"
          }
        ],
        "photos": [
          "../assets/images/commercial/PNGL (1).webp",
          "../assets/images/commercial/PNGL (2).webp",
          "../assets/images/commercial/PNGL (3).webp",
          "../assets/images/commercial/PNGL (4).webp",
          "../assets/images/commercial/PNGL (5).webp"
        ],
        "description": "テクニカルバッグを日常に。超軽量で防水性も備えています。"
      },
      {
        "id": "comm-8",
        "title": "20-40mm f/2.8 Di III VXD",
        "client": "Tamron",
        "year": "2025",
        "cover": "../assets/images/commercial/TamronA062 (1).webp",
        "position": "50% 0%",
        "links": [
          {
            "label": "Instagram 投稿",
            "url": "https://www.instagram.com/p/DNmro31hpW_/?img_index=1"
          }
        ],
        "photos": [
          "../assets/images/commercial/TamronA062 (1).webp",
          "../assets/images/commercial/TamronA062 (2).webp",
          "../assets/images/commercial/TamronA062 (3).webp"
        ],
        "description": "レンズレビュー"
      },
      {
        "id": "comm-9",
        "title": "25-200mm f/2.8-5.6 DiIII VXD G2",
        "client": "Tamron",
        "year": "2026",
        "cover": "../assets/images/commercial/TamronA075 (2).webp",
        "links": [
          {
            "label": "Instagram 投稿",
            "url": "https://www.instagram.com/p/DaT-NJVGcDO/?img_index=1"
          }
        ],
        "photos": [
          "../assets/images/commercial/TamronA075 (1).webp",
          "../assets/images/commercial/TamronA075 (2).webp",
          "../assets/images/commercial/TamronA075 (3).webp",
          "../assets/images/commercial/TamronA075 (4).webp",
          "../assets/images/commercial/TamronA075 (5).webp",
          "../assets/images/commercial/TamronA075 (6).webp"
        ],
        "description": "レンズレビュー"
      },
      {
        "id": "comm-10",
        "title": "Pentax 17 フィルムカメラ",
        "client": "PENTAX",
        "year": "2024",
        "cover": "../assets/images/commercial/PENTAX17 (1).webp",
        "links": [
          {
            "label": "Instagram 投稿",
            "url": "https://www.instagram.com/p/DDEi4Tmv7TO/?img_index=1"
          }
        ],
        "photos": [
          "../assets/images/commercial/PENTAX17 (1).webp",
          "../assets/images/commercial/PENTAX17 (2).webp",
          "../assets/images/commercial/PENTAX17 (3).webp",
          "../assets/images/commercial/PENTAX17 (4).webp",
          "../assets/images/commercial/PENTAX17 (5).webp",
          "../assets/images/commercial/PENTAX17 (6).webp",
          "../assets/images/commercial/PENTAX17 (7).webp",
          "../assets/images/commercial/PENTAX17 (8).webp",
          "../assets/images/commercial/PENTAX17 (9).webp",
          "../assets/images/commercial/PENTAX17 (10).webp"
        ],
        "description": "機材レビュー"
      }
    ],
    "portrait": [
      {
        "id": "port-2",
        "title": "昭和ロマン—梓曦",
        "client": "Zixic",
        "year": "2025",
        "cover": "../assets/images/portrait/Zixic (6).webp",
        "position": "10% 65%",
        "links": [
          {
            "label": "Instagram 投稿",
            "url": "https://www.instagram.com/p/DPwUtZOjo0c/?img_index=1"
          }
        ],
        "photos": [
          "../assets/images/portrait/Zixic (1).webp",
          "../assets/images/portrait/Zixic (2).webp",
          "../assets/images/portrait/Zixic (3).webp",
          "../assets/images/portrait/Zixic (4).webp",
          "../assets/images/portrait/Zixic (5).webp",
          "../assets/images/portrait/Zixic (6).webp",
          "../assets/images/portrait/Zixic (7).webp",
          "../assets/images/portrait/Zixic (8).webp",
          "../assets/images/portrait/Zixic (9).webp",
          "../assets/images/portrait/Zixic (10).webp",
          "../assets/images/portrait/Zixic (11).webp",
          "../assets/images/portrait/Zixic (12).webp",
          "../assets/images/portrait/Zixic (13).webp"
        ],
        "description": "昭和の街角で過ごす午後。"
      },
      {
        "id": "port-3",
        "title": "台湾エモーション",
        "client": "Farah",
        "year": "2026",
        "cover": "../assets/images/portrait/Farah (2).webp",
        "position": "center 65%",
        "photos": [
          "../assets/images/portrait/Farah (1).webp",
          "../assets/images/portrait/Farah (2).webp",
          "../assets/images/portrait/Farah (3).webp",
          "../assets/images/portrait/Farah (4).webp",
          "../assets/images/portrait/Farah (5).webp",
          "../assets/images/portrait/Farah (6).webp",
          "../assets/images/portrait/Farah (7).webp",
          "../assets/images/portrait/Farah (8).webp"
        ],
        "description": "台湾の古い路地を巡る光と影の物語。"
      },
      {
        "id": "port-4",
        "title": "眷村ポートレート",
        "client": "陳小羊",
        "year": "2025",
        "cover": "../assets/images/portrait/陳小羊 (9).webp",
        "photos": [
          "../assets/images/portrait/陳小羊 (1).webp",
          "../assets/images/portrait/陳小羊 (2).webp",
          "../assets/images/portrait/陳小羊 (3).webp",
          "../assets/images/portrait/陳小羊 (4).webp",
          "../assets/images/portrait/陳小羊 (5).webp",
          "../assets/images/portrait/陳小羊 (6).webp",
          "../assets/images/portrait/陳小羊 (7).webp",
          "../assets/images/portrait/陳小羊 (8).webp",
          "../assets/images/portrait/陳小羊 (9).webp",
          "../assets/images/portrait/陳小羊 (10).webp"
        ],
        "description": "時間が巻き戻るような眷村の記憶。"
      },
      {
        "id": "port-5",
        "title": "あの頃の青春と、その後の私たち",
        "client": "みに",
        "year": "2025",
        "cover": "../assets/images/portrait/Mini (2).webp",
        "position": "center 60%",
        "photos": [
          "../assets/images/portrait/Mini (1).webp",
          "../assets/images/portrait/Mini (2).webp",
          "../assets/images/portrait/Mini (3).webp",
          "../assets/images/portrait/Mini (4).webp",
          "../assets/images/portrait/Mini (5).webp",
          "../assets/images/portrait/Mini (6).webp",
          "../assets/images/portrait/Mini (7).webp",
          "../assets/images/portrait/Mini (8).webp"
        ],
        "description": "制服を着て、あの日の私たちと再会する。"
      },
      {
        "id": "port-6",
        "title": "迪化街、時をめぐる散歩",
        "client": "Peggy",
        "year": "2025",
        "cover": "../assets/images/portrait/Peggy (1).webp",
        "position": "55% 90%",
        "photos": [
          "../assets/images/portrait/Peggy (1).webp",
          "../assets/images/portrait/Peggy (2).webp",
          "../assets/images/portrait/Peggy (3).webp",
          "../assets/images/portrait/Peggy (4).webp",
          "../assets/images/portrait/Peggy (5).webp",
          "../assets/images/portrait/Peggy (6).webp",
          "../assets/images/portrait/Peggy (7).webp",
          "../assets/images/portrait/Peggy (8).webp",
          "../assets/images/portrait/Peggy (9).webp",
          "../assets/images/portrait/Peggy (10).webp"
        ],
        "description": "時の痕跡に残る旧市街の記憶を辿る。"
      },
      {
        "id": "port-7",
        "title": "泰崗の桜と古風漢服",
        "client": "飄逸",
        "year": "2025",
        "cover": "../assets/images/portrait/飄逸 (3).webp",
        "position": "60% 50%",
        "photos": [
          "../assets/images/portrait/飄逸 (1).webp",
          "../assets/images/portrait/飄逸 (2).webp",
          "../assets/images/portrait/飄逸 (3).webp"
        ],
        "description": "東洋ならではのロマンと胸の高鳴り。"
      },
      {
        "id": "port-8",
        "title": "クリスマス・ファミリーポートレート",
        "client": "Christmas",
        "year": "2024",
        "cover": "../assets/images/portrait/CH1218 (2).webp",
        "position": "50% 50%",
        "photos": [
          "../assets/images/portrait/CH1218 (4).webp",
          "../assets/images/portrait/CH1218 (5).webp",
          "../assets/images/portrait/CH1218 (3).webp",
          "../assets/images/portrait/CH1218 (2).webp",
          "../assets/images/portrait/CH1218 (1).webp"
        ],
        "description": "冬の夜を照らす、幸せなひととき。"
      },
      {
        "id": "port-9",
        "title": "都会の小さな幸せ",
        "client": "Passerby",
        "year": "2024-2025",
        "cover": "../assets/images/portrait/passerby (3).webp",
        "position": "30% 70%",
        "photos": [
          "../assets/images/portrait/passerby (3).webp",
          "../assets/images/portrait/passerby (9).webp",
          "../assets/images/portrait/passerby (7).webp",
          "../assets/images/portrait/passerby (10).webp",
          "../assets/images/portrait/passerby (8).webp",
          "../assets/images/portrait/passerby (2).webp"
        ],
        "description": "私たちだけが知っている、いつもの風景。"
      },
      {
        "id": "port-10",
        "title": "街角の人間模様",
        "client": "Passerby",
        "year": "2025",
        "cover": "../assets/images/portrait/passerby (4).webp",
        "position": "25% 70%",
        "photos": [
          "../assets/images/portrait/passerby (1).webp",
          "../assets/images/portrait/passerby (4).webp",
          "../assets/images/portrait/passerby (5).webp",
          "../assets/images/portrait/passerby (6).webp"
        ],
        "description": "忙しい都会のリズムの中で、自然さと真実を切り取る。"
      }
    ],
    "concert": [
      {
        "id": "conc-1",
        "title": "ジョンソンヘルステック50周年記念チャリティーコンサート",
        "client": "台北ドーム",
        "year": "2026",
        "cover": "../assets/images/concert/911 (1).webp",
        "position": "center center",
        "photos": [
          "../assets/images/concert/911 (1).webp",
          "../assets/images/concert/911 (2).webp",
          "../assets/images/concert/911 (3).webp",
          "../assets/images/concert/911 (4).webp",
          "../assets/images/concert/911 (5).webp",
          "../assets/images/concert/911 (6).webp",
          "../assets/images/concert/911 (7).webp"
        ],
        "description": "feat. Nine One One"
      },
      {
        "id": "conc-2",
        "title": "ジョンソンヘルステック50周年記念チャリティーコンサート",
        "client": "台北ドーム",
        "year": "2026",
        "cover": "../assets/images/concert/ALin (2).webp",
        "position": "center center",
        "photos": [
          "../assets/images/concert/ALin (1).webp",
          "../assets/images/concert/ALin (2).webp",
          "../assets/images/concert/ALin (3).webp",
          "../assets/images/concert/ALin (4).webp",
          "../assets/images/concert/ALin (5).webp",
          "../assets/images/concert/ALin (6).webp",
          "../assets/images/concert/ALin (7).webp",
          "../assets/images/concert/ALin (8).webp"
        ],
        "description": "feat. A-Lin"
      },
      {
        "id": "conc-3",
        "title": "ジョンソンヘルステック50周年記念チャリティーコンサート",
        "client": "台北ドーム",
        "year": "2026",
        "cover": "../assets/images/concert/EricChou (4).webp",
        "position": "bottom center",
        "scale": 1.3,
        "photos": [
          "../assets/images/concert/EricChou (1).webp",
          "../assets/images/concert/EricChou (2).webp",
          "../assets/images/concert/EricChou (3).webp",
          "../assets/images/concert/EricChou (4).webp",
          "../assets/images/concert/EricChou (5).webp",
          "../assets/images/concert/EricChou (6).webp"
        ],
        "description": "feat. エリック・チョウ"
      },
      {
        "id": "conc-4",
        "title": "ジョンソンヘルステック50周年記念チャリティーコンサート",
        "client": "台北ドーム",
        "year": "2026",
        "cover": "../assets/images/concert/CrowdLu (8).webp",
        "position": "35% 60%",
        "photos": [
          "../assets/images/concert/CrowdLu (1).webp",
          "../assets/images/concert/CrowdLu (2).webp",
          "../assets/images/concert/CrowdLu (3).webp",
          "../assets/images/concert/CrowdLu (4).webp",
          "../assets/images/concert/CrowdLu (5).webp",
          "../assets/images/concert/CrowdLu (6).webp",
          "../assets/images/concert/CrowdLu (7).webp",
          "../assets/images/concert/CrowdLu (8).webp"
        ],
        "description": "feat. ルー・グァンチョン"
      },
      {
        "id": "conc-5",
        "title": "ジョンソンヘルステック50周年記念チャリティーコンサート",
        "client": "台北ドーム",
        "year": "2026",
        "cover": "../assets/images/concert/AccuseFive (2).webp",
        "position": "center center",
        "photos": [
          "../assets/images/concert/AccuseFive (1).webp",
          "../assets/images/concert/AccuseFive (2).webp",
          "../assets/images/concert/AccuseFive (3).webp",
          "../assets/images/concert/AccuseFive (4).webp",
          "../assets/images/concert/AccuseFive (5).webp",
          "../assets/images/concert/AccuseFive (6).webp",
          "../assets/images/concert/AccuseFive (7).webp",
          "../assets/images/concert/AccuseFive (8).webp"
        ],
        "description": "feat. Accusefive"
      },
      {
        "id": "conc-6",
        "title": "2025 茉ひる ASIA TOUR『SeRendipity』in TAIPEI",
        "client": "Legacy Tera",
        "year": "2025",
        "cover": "../assets/images/concert/Mahiru (1).webp",
        "position": "bottom center",
        "scale": 1.1,
        "photos": [
          "../assets/images/concert/Mahiru (1).webp",
          "../assets/images/concert/Mahiru (2).webp",
          "../assets/images/concert/Mahiru (3).webp",
          "../assets/images/concert/Mahiru (4).webp",
          "../assets/images/concert/Mahiru (5).webp",
          "../assets/images/concert/Mahiru (6).webp",
          "../assets/images/concert/Mahiru (7).webp",
          "../assets/images/concert/Mahiru (8).webp",
          "../assets/images/concert/Mahiru (9).webp",
          "../assets/images/concert/Mahiru (10).webp"
        ],
        "description": "2025.05.31｜feat. Rinzo、Patrick Brasca"
      },
      {
        "id": "conc-7",
        "title": "2025 茉ひる ASIA TOUR 『SeRendipity』",
        "client": "MAHIRU",
        "year": "2025",
        "cover": "../assets/images/concert/MahiruGoods (1).webp",
        "photos": [
          "../assets/images/concert/MahiruGoods (1).webp",
          "../assets/images/concert/MahiruGoods (2).webp",
          "../assets/images/concert/MahiruGoods (3).webp"
        ],
        "description": "香港・バンコク・大阪・東京・高雄・台北｜ツアーグッズ"
      },
      {
        "id": "conc-8",
        "title": "Pika Chiu 2024 クリスマスイブ・ポップアップライブ",
        "client": "Pika Chiu",
        "year": "2024",
        "cover": "../assets/images/concert/PikaChiu1224 (1).webp",
        "position": "50% 90%",
        "scale": 1,
        "photos": [
          "../assets/images/concert/PikaChiu1224 (1).webp",
          "../assets/images/concert/PikaChiu1224 (2).webp",
          "../assets/images/concert/PikaChiu1224 (3).webp",
          "../assets/images/concert/PikaChiu1224 (4).webp",
          "../assets/images/concert/PikaChiu1224 (5).webp",
          "../assets/images/concert/PikaChiu1224 (6).webp",
          "../assets/images/concert/PikaChiu1224 (7).webp",
          "../assets/images/concert/PikaChiu1224 (8).webp",
          "../assets/images/concert/PikaChiu1224 (9).webp",
          "../assets/images/concert/PikaChiu1224 (10).webp"
        ],
        "description": "誠品生活武昌・西門町"
      }
    ],
    "event": [
      {
        "id": "ev-1",
        "title": "ジョンソンヘルステック50周年記念チャリティーコンサート",
        "client": "台北ドーム",
        "year": "2026",
        "cover": "../assets/images/event/Lulu (2).webp",
        "position": "40% 85%",
        "scale": 1.2,
        "links": [
          {
            "label": "Lulu Instagram 投稿",
            "url": "https://www.instagram.com/p/DTyASBCEj_b/"
          }
        ],
        "photos": [
          "../assets/images/event/Lulu (1).webp",
          "../assets/images/event/Lulu (2).webp",
          "../assets/images/event/Lulu (3).webp",
          "../assets/images/event/Lulu (4).webp",
          "../assets/images/event/Lulu (5).webp",
          "../assets/images/event/Lulu (6).webp",
          "../assets/images/event/Lulu (7).webp",
          "../assets/images/event/Lulu (8).webp"
        ],
        "description": "feat. 陳漢典、Lulu"
      },
      {
        "id": "ev-2",
        "title": "台北科技大学創立114周年記念式典",
        "client": "NTUT",
        "year": "2025",
        "cover": "../assets/images/event/NTUT114 (3).webp",
        "links": [
          {
            "label": "工商時報",
            "url": "https://www.ctee.com.tw/news/20251101700632-431204"
          },
          {
            "label": "自由時報",
            "url": "https://news.ltn.com.tw/news/Taipei/breakingnews/5231061"
          },
          {
            "label": "経済日報",
            "url": "https://money.udn.com/money/story/5723/9111589"
          },
          {
            "label": "中央通信社",
            "url": "https://www.cna.com.tw/news/ahel/202511010121.aspx"
          },
          {
            "label": "台北科技大学ニュース",
            "url": "https://news.ntut.edu.tw/p/406-1000-149442,r11.php?Lang=zh-tw"
          },
          {
            "label": "NOWNEWS",
            "url": "https://www.nownews.com/news/6749187"
          },
          {
            "label": "Yahoo Taiwan",
            "url": "https://tw.news.yahoo.com/%E7%8E%8B%E4%B8%96%E5%A0%85%EF%BC%9A%E5%BE%9E%E6%94%BF20%E5%B9%B4%E4%BE%86%E6%9C%80%E5%85%89%E6%A6%AE%E7%9A%84%E4%B8%80%E5%A4%A9%EF%BC%81%E7%8D%B2%E9%A0%92%E5%8C%97%E7%A7%91%E5%A4%A7%E5%90%8D%E8%AD%BD%E5%8D%9A%E5%A3%AB-%E5%9B%9E%E6%86%B6%E5%B9%B4%E5%B0%91%E8%88%8A%E6%9B%B8%E6%94%A4%E6%84%9F%E5%8B%95-072253911.html"
          }
        ],
        "photos": [
          "../assets/images/event/NTUT114 (1).webp",
          "../assets/images/event/NTUT114 (2).webp",
          "../assets/images/event/NTUT114 (3).webp",
          "../assets/images/event/NTUT114 (4).webp",
          "../assets/images/event/NTUT114 (5).webp",
          "../assets/images/event/NTUT114 (6).webp",
          "../assets/images/event/NTUT114 (7).webp",
          "../assets/images/event/NTUT114 (8).webp",
          "../assets/images/event/NTUT114 (9).webp",
          "../assets/images/event/NTUT114 (10).webp",
          "../assets/images/event/NTUT114 (11).webp",
          "../assets/images/event/NTUT114 (12).webp",
          "../assets/images/event/NTUT114 (13).webp",
          "../assets/images/event/NTUT114 (14).webp",
          "../assets/images/event/NTUT114 (15).webp"
        ],
        "description": "卓越した同窓生を表彰し、顏志發、王世堅、林添茂の各氏に名誉博士号を授与。"
      },
      {
        "id": "ev-3",
        "title": "『空白に織り上げる』",
        "client": "AEUST",
        "year": "2026",
        "cover": "../assets/images/event/EspaceLibre (1).webp",
        "position": "50% 35%",
        "scale": 1.4,
        "photos": [
          "../assets/images/event/EspaceLibre (1).webp",
          "../assets/images/event/EspaceLibre (2).webp",
          "../assets/images/event/EspaceLibre (3).webp",
          "../assets/images/event/EspaceLibre (4).webp",
          "../assets/images/event/EspaceLibre (5).webp",
          "../assets/images/event/EspaceLibre (6).webp",
          "../assets/images/event/EspaceLibre (7).webp",
          "../assets/images/event/EspaceLibre (8).webp",
          "../assets/images/event/EspaceLibre (9).webp",
          "../assets/images/event/EspaceLibre (10).webp",
          "../assets/images/event/EspaceLibre (11).webp",
          "../assets/images/event/EspaceLibre (12).webp",
          "../assets/images/event/EspaceLibre (13).webp",
          "../assets/images/event/EspaceLibre (14).webp",
          "../assets/images/event/EspaceLibre (15).webp"
        ],
        "description": "亜東科技大学 材料・テキスタイル・服飾学科 第12回卒業制作展"
      },
      {
        "id": "ev-4",
        "title": "LiFUNd 第3回「夢の出航」",
        "client": "LiFUNd",
        "year": "2026",
        "cover": "../assets/images/event/1.webp",
        "links": [
          {
            "label": "経済日報",
            "url": "https://money.udn.com/money/story/5635/9386900"
          }
        ],
        "photos": [
          "../assets/images/event/1.webp",
          "../assets/images/event/2.webp",
          "../assets/images/event/3.webp",
          "../assets/images/event/4.webp",
          "../assets/images/event/5.webp"
        ],
        "description": "2026.03.06"
      },
      {
        "id": "ev-5",
        "title": "SITCON 2026 学生コンピューティングカンファレンス",
        "client": "SITCON",
        "year": "2026",
        "cover": "../assets/images/event/10.webp",
        "position": "40% 70%",
        "photos": [
          "../assets/images/event/6.webp",
          "../assets/images/event/7.webp",
          "../assets/images/event/8.webp",
          "../assets/images/event/9.webp",
          "../assets/images/event/10.webp"
        ],
        "description": "中央研究院"
      },
      {
        "id": "ev-6",
        "title": "2026 Threads’ Party",
        "client": "Treads",
        "year": "2026",
        "cover": "../assets/images/event/15.webp",
        "photos": [
          "../assets/images/event/11.webp",
          "../assets/images/event/12.webp",
          "../assets/images/event/13.webp",
          "../assets/images/event/14.webp",
          "../assets/images/event/15.webp"
        ],
        "description": "第1回アメリカンスタイル卒業プロム＆春のガラディナー"
      },
      {
        "id": "ev-7",
        "title": "CyberCube",
        "client": "CyberCube",
        "year": "2026",
        "cover": "../assets/images/event/16.webp",
        "photos": [
          "../assets/images/event/16.webp",
          "../assets/images/event/17.webp",
          "../assets/images/event/18.webp",
          "../assets/images/event/19.webp",
          "../assets/images/event/20.webp"
        ],
        "description": "2026 台北市高校進学・キャリアフェア"
      },
      {
        "id": "ev-8",
        "title": "Asia’s Got Talent シルホイールショー—楊世豪",
        "client": "奇美博物館",
        "year": "2025",
        "cover": "../assets/images/event/22.webp",
        "position": "50% 60%",
        "photos": [
          "../assets/images/event/21.webp",
          "../assets/images/event/22.webp",
          "../assets/images/event/23.webp",
          "../assets/images/event/24.webp",
          "../assets/images/event/25.webp"
        ],
        "description": "許耀中ダンススタジオ「舞極X唯一」社交ダンス・ガラ"
      },
      {
        "id": "ev-9",
        "title": "Nine One One × 楊世豪",
        "client": "台北ドーム",
        "year": "2026",
        "cover": "../assets/images/event/ShihhaoDome (1).webp",
        "photos": [
          "../assets/images/event/ShihhaoDome (1).webp",
          "../assets/images/event/ShihhaoDome (2).webp",
          "../assets/images/event/ShihhaoDome (3).webp",
          "../assets/images/event/ShihhaoDome (4).webp",
          "../assets/images/event/ShihhaoDome (5).webp",
          "../assets/images/event/ShihhaoDome (6).webp",
          "../assets/images/event/ShihhaoDome (7).webp",
          "../assets/images/event/ShihhaoDome (8).webp"
        ],
        "description": "ジョンソンヘルステック50周年記念チャリティーコンサート"
      },
      {
        "id": "ev-10",
        "title": "CIRCUS GATE 2025 年間公演『カーニバル・ボール』",
        "client": "CIRCUS GATE",
        "year": "2025",
        "cover": "../assets/images/event/28.webp",
        "position": "60% 50%",
        "photos": [
          "../assets/images/event/26.webp",
          "../assets/images/event/27.webp",
          "../assets/images/event/28.webp",
          "../assets/images/event/29.webp",
          "../assets/images/event/30.webp"
        ],
        "description": "誠品ブラックボックス"
      },
      {
        "id": "ev-11",
        "title": "『Patikol 帰巣—Torik部落創作音楽舞踊劇』",
        "client": "NTUT Aliyan",
        "year": "2025",
        "cover": "../assets/images/event/31.webp",
        "position": "50% 90%",
        "scale": 1.2,
        "photos": [
          "../assets/images/event/31.webp",
          "../assets/images/event/32.webp",
          "../assets/images/event/33.webp",
          "../assets/images/event/34.webp",
          "../assets/images/event/35.webp"
        ],
        "description": "国立台北科技大学 Aliyan 原住民文化研究会"
      },
      {
        "id": "ev-12",
        "title": "台北科技大学国際事務処 2025 秋季留学生ミッドターム交流会",
        "client": "NTUT OIA",
        "year": "2025",
        "cover": "../assets/images/event/38.webp",
        "photos": [
          "../assets/images/event/36.webp",
          "../assets/images/event/37.webp",
          "../assets/images/event/38.webp",
          "../assets/images/event/39.webp",
          "../assets/images/event/40.webp"
        ],
        "description": "2025.10.29"
      },
      {
        "id": "ev-13",
        "title": "グリーンパワー・ライフフェスティバル",
        "client": "TFG X Taipei 101",
        "year": "2025",
        "cover": "../assets/images/event/42.webp",
        "position": "70% 50%",
        "photos": [
          "../assets/images/event/41.webp",
          "../assets/images/event/42.webp",
          "../assets/images/event/43.webp",
          "../assets/images/event/44.webp",
          "../assets/images/event/45.webp"
        ],
        "description": "台北101 × 台北市立第一女子高級中学"
      },
      {
        "id": "ev-14",
        "title": "2025 北海岸きらめく夜—潮と炎",
        "client": "NTPC",
        "year": "2025",
        "cover": "../assets/images/event/50.webp",
        "photos": [
          "../assets/images/event/46.webp",
          "../assets/images/event/47.webp",
          "../assets/images/event/48.webp",
          "../assets/images/event/49.webp",
          "../assets/images/event/50.webp"
        ],
        "description": "2025.08.24"
      },
      {
        "id": "ev-15",
        "title": "2024 Computex Taipei",
        "client": "Computex",
        "year": "2024",
        "cover": "../assets/images/event/53.webp",
        "photos": [
          "../assets/images/event/51.webp",
          "../assets/images/event/52.webp",
          "../assets/images/event/53.webp",
          "../assets/images/event/54.webp",
          "../assets/images/event/55.webp"
        ],
        "description": "COMPUTEX TAIPEI"
      },
      {
        "id": "ev-16",
        "title": "甲辰龍年・頭份永貞宮から台北池合宮への参香",
        "client": "TOUFEN",
        "year": "2024",
        "cover": "../assets/images/event/20241208 (5).webp",
        "photos": [
          "../assets/images/event/20241208 (1).webp",
          "../assets/images/event/20241208 (2).webp",
          "../assets/images/event/20241208 (3).webp",
          "../assets/images/event/20241208 (4).webp",
          "../assets/images/event/20241208 (5).webp",
          "../assets/images/event/20241208 (6).webp",
          "../assets/images/event/20241208 (7).webp",
          "../assets/images/event/20241208 (8).webp",
          "../assets/images/event/20241208 (9).webp",
          "../assets/images/event/20241208 (10).webp",
          "../assets/images/event/20241208 (11).webp",
          "../assets/images/event/20241208 (12).webp",
          "../assets/images/event/20241208 (13).webp",
          "../assets/images/event/20241208 (14).webp"
        ],
        "description": "2024.12.08"
      },
      {
        "id": "ev-17",
        "title": "2024 苗栗県客家文芸協会 端午節ちまき作り・省エネ啓発イベント",
        "client": "TOUFEN",
        "year": "2024",
        "cover": "../assets/images/event/20240608 (5).webp",
        "position": "0% 5%",
        "photos": [
          "../assets/images/event/20240608 (1).webp",
          "../assets/images/event/20240608 (2).webp",
          "../assets/images/event/20240608 (3).webp",
          "../assets/images/event/20240608 (4).webp",
          "../assets/images/event/20240608 (5).webp",
          "../assets/images/event/20240608 (6).webp",
          "../assets/images/event/20240608 (7).webp",
          "../assets/images/event/20240608 (8).webp",
          "../assets/images/event/20240608 (9).webp"
        ],
        "description": "ちまき作りの準備工程を記録。"
      },
      {
        "id": "ev-18",
        "title": "2026 中元節祭典｜手作り客家新丁粄の記録",
        "client": "TOUFEN",
        "year": "2025",
        "cover": "../assets/images/event/20250830 (5).webp",
        "photos": [
          "../assets/images/event/20250830 (1).webp",
          "../assets/images/event/20250830 (2).webp",
          "../assets/images/event/20250830 (3).webp",
          "../assets/images/event/20250830 (4).webp",
          "../assets/images/event/20250830 (5).webp",
          "../assets/images/event/20250830 (6).webp"
        ],
        "description": "頭份永貞宮｜中元普渡大法会"
      }
    ],
    "sports": [
      {
        "id": "sp-1",
        "title": "LG TWINS × 味全ドラゴンズ コラボテーマデー",
        "client": "台北ドーム",
        "year": "2026",
        "cover": "../assets/images/sports/WDragons0526 (1).webp",
        "position": "50% 85%",
        "photos": [
          "../assets/images/sports/WDragons0526 (1).webp",
          "../assets/images/sports/WDragons0526 (2).webp",
          "../assets/images/sports/WDragons0526 (3).webp",
          "../assets/images/sports/WDragons0526 (4).webp",
          "../assets/images/sports/WDragons0526 (5).webp",
          "../assets/images/sports/WDragons0526 (6).webp",
          "../assets/images/sports/WDragons0526 (7).webp",
          "../assets/images/sports/WDragons0526 (8).webp",
          "../assets/images/sports/WDragons0526 (9).webp",
          "../assets/images/sports/WDragons0526 (10).webp",
          "../assets/images/sports/WDragons0526 (11).webp",
          "../assets/images/sports/WDragons0526 (12).webp",
          "../assets/images/sports/WDragons0526 (13).webp",
          "../assets/images/sports/WDragons0526 (14).webp",
          "../assets/images/sports/WDragons0526 (15).webp",
          "../assets/images/sports/WDragons0526 (16).webp",
          "../assets/images/sports/WDragons0526 (17).webp",
          "../assets/images/sports/WDragons0526 (18).webp"
        ],
        "description": "2026.05.26"
      },
      {
        "id": "sp-2",
        "title": "P. LEAGUE+ 台北富邦ブレーブス 2025–26 ホーム開幕戦",
        "client": "台北和平バスケットボール体育館",
        "year": "2025",
        "cover": "../assets/images/sports/FubonBraves1109 (9).webp",
        "position": "bottom center",
        "photos": [
          "../assets/images/sports/FubonBraves1109 (1).webp",
          "../assets/images/sports/FubonBraves1109 (2).webp",
          "../assets/images/sports/FubonBraves1109 (3).webp",
          "../assets/images/sports/FubonBraves1109 (4).webp",
          "../assets/images/sports/FubonBraves1109 (5).webp",
          "../assets/images/sports/FubonBraves1109 (6).webp",
          "../assets/images/sports/FubonBraves1109 (7).webp",
          "../assets/images/sports/FubonBraves1109 (8).webp",
          "../assets/images/sports/FubonBraves1109 (9).webp",
          "../assets/images/sports/FubonBraves1109 (10).webp"
        ],
        "description": "2025.11.09"
      },
      {
        "id": "sp-3",
        "title": "CPBL 35年シーズン公式戦 — 9月15日",
        "client": "台北ドーム",
        "year": "2024",
        "cover": "../assets/images/sports/WDragons (1).webp",
        "position": "60% 60%",
        "photos": [
          "../assets/images/sports/WDragons (1).webp",
          "../assets/images/sports/WDragons (2).webp",
          "../assets/images/sports/WDragons (3).webp",
          "../assets/images/sports/WDragons (4).webp",
          "../assets/images/sports/WDragons (5).webp",
          "../assets/images/sports/WDragons (6).webp",
          "../assets/images/sports/WDragons (7).webp",
          "../assets/images/sports/WDragons (8).webp"
        ],
        "description": "2024.09.15"
      },
      {
        "id": "sp-4",
        "title": "2025 台北市学生野球秋季リーグ",
        "client": "迎風河浜野球場",
        "year": "2025",
        "cover": "../assets/images/sports/NtutBaseball0930 (1).webp",
        "position": "50% 70%",
        "links": [
          {
            "label": "台北科技大学野球部 Instagram 投稿",
            "url": "https://www.instagram.com/p/DPTwKx_ktBt/?img_index=1"
          }
        ],
        "photos": [
          "../assets/images/sports/NtutBaseball0930 (1).webp",
          "../assets/images/sports/NtutBaseball0930 (2).webp",
          "../assets/images/sports/NtutBaseball0930 (3).webp",
          "../assets/images/sports/NtutBaseball0930 (4).webp",
          "../assets/images/sports/NtutBaseball0930 (5).webp",
          "../assets/images/sports/NtutBaseball0930 (6).webp",
          "../assets/images/sports/NtutBaseball0930 (7).webp",
          "../assets/images/sports/NtutBaseball0930 (8).webp",
          "../assets/images/sports/NtutBaseball0930 (9).webp",
          "../assets/images/sports/NtutBaseball0930 (10).webp",
          "../assets/images/sports/NtutBaseball0930 (11).webp",
          "../assets/images/sports/NtutBaseball0930 (12).webp",
          "../assets/images/sports/NtutBaseball0930 (13).webp",
          "../assets/images/sports/NtutBaseball0930 (14).webp",
          "../assets/images/sports/NtutBaseball0930 (15).webp",
          "../assets/images/sports/NtutBaseball0930 (16).webp",
          "../assets/images/sports/NtutBaseball0930 (17).webp",
          "../assets/images/sports/NtutBaseball0930 (18).webp",
          "../assets/images/sports/NtutBaseball0930 (19).webp"
        ],
        "description": "2025.10.02"
      },
      {
        "id": "sp-5",
        "title": "ギリギラウ・コンクアン",
        "client": "台北ドーム",
        "year": "2024",
        "cover": "../assets/images/sports/Giljegiljaw (1).webp",
        "position": "50% 50%",
        "links": [
          {
            "label": "ギリギラウ・コンクアン Instagram 投稿",
            "url": "https://www.instagram.com/p/DADMdyUS6-u/"
          }
        ],
        "photos": [
          "../assets/images/sports/Giljegiljaw (1).webp",
          "../assets/images/sports/Giljegiljaw (2).webp",
          "../assets/images/sports/Giljegiljaw (3).webp"
        ],
        "description": "2024.09.15"
      },
      {
        "id": "sp-6",
        "title": "エンダーソン・フランコ",
        "client": "新荘野球場",
        "year": "2025",
        "cover": "../assets/images/sports/Franco.webp",
        "position": "50% 60%",
        "links": [
          {
            "label": "エンダーソン・フランコ Instagram 投稿",
            "url": "https://www.instagram.com/p/DJHPCBzynVJ/"
          }
        ],
        "photos": [
          "../assets/images/sports/Franco.webp"
        ],
        "description": "2025.04.22"
      },
      {
        "id": "sp-8",
        "title": "2026 全国大学体育大会・一般部門 北部バドミントン予選",
        "client": "台北体育館",
        "year": "2026",
        "cover": "../assets/images/sports/NtutBadminton (3).webp",
        "position": "60% 50%",
        "links": [
          {
            "label": "台北科技大学バドミントン部 Instagram 投稿",
            "url": "https://www.instagram.com/p/DW6O8WdFECu/?img_index=9"
          }
        ],
        "photos": [
          "../assets/images/sports/NtutBadminton (1).webp",
          "../assets/images/sports/NtutBadminton (2).webp",
          "../assets/images/sports/NtutBadminton (3).webp"
        ],
        "description": "2026.03.25"
      },
      {
        "id": "sp-9",
        "title": "2024 Rising Star RG 国際招待大会",
        "client": "Rising Star RG",
        "year": "2024",
        "cover": "../assets/images/sports/20240705 (7).webp",
        "photos": [
          "../assets/images/sports/20240705 (1).webp",
          "../assets/images/sports/20240705 (2).webp",
          "../assets/images/sports/20240705 (3).webp",
          "../assets/images/sports/20240705 (4).webp",
          "../assets/images/sports/20240705 (5).webp",
          "../assets/images/sports/20240705 (6).webp",
          "../assets/images/sports/20240705 (7).webp"
        ],
        "description": "2024.07.05"
      }
    ],
    "graduation": [
      {
        "id": "grad-1",
        "title": "国立陽明交通大学",
        "client": "NYCU",
        "year": "2025",
        "cover": "../assets/images/graduation/NYCU (1).webp",
        "position": "35% 50%",
        "photos": [
          "../assets/images/graduation/NYCU (1).webp",
          "../assets/images/graduation/NYCU (2).webp",
          "../assets/images/graduation/NYCU (3).webp",
          "../assets/images/graduation/NYCU (4).webp",
          "../assets/images/graduation/NYCU (5).webp",
          "../assets/images/graduation/NYCU (6).webp"
        ],
        "description": "博士課程卒業写真"
      },
      {
        "id": "grad-2",
        "title": "国立台北科技大学",
        "client": "NTUT",
        "year": "2025",
        "cover": "../assets/images/graduation/NTUT (4).webp",
        "position": "50% 60%",
        "photos": [
          "../assets/images/graduation/NTUT (1).webp",
          "../assets/images/graduation/NTUT (2).webp",
          "../assets/images/graduation/NTUT (3).webp",
          "../assets/images/graduation/NTUT (4).webp",
          "../assets/images/graduation/NTUT (5).webp",
          "../assets/images/graduation/NTUT (6).webp",
          "../assets/images/graduation/NTUT (7).webp",
          "../assets/images/graduation/NTUT (8).webp"
        ],
        "description": "修士課程卒業写真"
      },
      {
        "id": "grad-3",
        "title": "国立台北護理健康大学",
        "client": "NTUNHS",
        "year": "2025",
        "cover": "../assets/images/graduation/NTUNHS (7).webp",
        "position": "50% 80%",
        "photos": [
          "../assets/images/graduation/NTUNHS (1).webp",
          "../assets/images/graduation/NTUNHS (2).webp",
          "../assets/images/graduation/NTUNHS (3).webp",
          "../assets/images/graduation/NTUNHS (4).webp",
          "../assets/images/graduation/NTUNHS (5).webp",
          "../assets/images/graduation/NTUNHS (6).webp",
          "../assets/images/graduation/NTUNHS (7).webp",
          "../assets/images/graduation/NTUNHS (8).webp"
        ],
        "description": "学士課程卒業写真"
      }
    ],
    "landscape": [
      {
        "id": "land26",
        "title": "閉合前夜—世紀の約束",
        "client": "Danjiang Bridge",
        "year": "2026",
        "cover": "../assets/images/landscape/landscape1.webp",
        "position": "60% 60%",
        "scale": 1.5,
        "links": [
          {
            "label": "Instagram 投稿",
            "url": "https://www.instagram.com/p/DYCL2foGb-e/?img_index=1"
          }
        ],
        "photos": [
          "../assets/images/landscape/landscape1.webp"
        ],
        "description": "淡水河口で、世界的ランドマークが構想から現実へと姿を現す過程を見届ける。"
      },
      {
        "id": "land-25",
        "title": "真夏の喧騒と静寂",
        "client": "Dadaocheng Fireworks",
        "year": "2026",
        "cover": "../assets/images/landscape/landscape (1).webp",
        "position": "50% 50%",
        "scale": 1,
        "links": [
          {
            "label": "Instagram 投稿",
            "url": "https://www.instagram.com/p/DbqMEVsAeG0/"
          }
        ],
        "photos": [
          "../assets/images/landscape/landscape (1).webp"
        ],
        "description": "旧市街の屋上から、無数の灯りと夜空の花火が同時に咲く。"
      },
      {
        "id": "land-24",
        "title": "極東、潮の時間",
        "client": "Magang Fishing Village",
        "year": "2026",
        "cover": "../assets/images/landscape/landscape (2).webp",
        "position": "50% 50%",
        "scale": 1,
        "links": [
          {
            "label": "Instagram 投稿",
            "url": "https://www.instagram.com/p/Da4SD_FmVwc/?img_index=1"
          }
        ],
        "photos": [
          "../assets/images/landscape/landscape (2).webp",
          "../assets/images/landscape/landscape (3).webp",
          "../assets/images/landscape/landscape (4).webp"
        ],
        "description": "石造りの家と海食台が交差し、台湾東端の静かな歳月を閉じ込める。"
      },
      {
        "id": "land-23",
        "title": "風車と夕暮れの境界",
        "client": "Itoshima Kuroiso Coast",
        "year": "2025",
        "cover": "../assets/images/landscape/landscape (5).webp",
        "position": "50% 50%",
        "scale": 1,
        "links": [
          {
            "label": "Instagram 投稿",
            "url": "https://www.instagram.com/p/DVGMI28kx7l/?img_index=1"
          }
        ],
        "photos": [
          "../assets/images/landscape/landscape (5).webp",
          "../assets/images/landscape/landscape (6).webp",
          "../assets/images/landscape/landscape (7).webp",
          "../assets/images/landscape/landscape (8).webp",
          "../assets/images/landscape/landscape (9).webp",
          "../assets/images/landscape/landscape (10).webp"
        ],
        "description": "幾重にも重なる山影の中、潮を聴きながら回るシルエットが立つ。"
      },
      {
        "id": "land-22",
        "title": "広い世界で、小さな自分に出会う",
        "client": "Aso",
        "year": "2025",
        "cover": "../assets/images/landscape/landscape (11).webp",
        "position": "50% 50%",
        "scale": 1,
        "links": [
          {
            "label": "Instagram 投稿",
            "url": "https://www.instagram.com/p/DWdqAQ5GZnk/?img_index=1"
          }
        ],
        "photos": [
          "../assets/images/landscape/landscape (11).webp",
          "../assets/images/landscape/landscape (12).webp",
          "../assets/images/landscape/landscape (13).webp",
          "../assets/images/landscape/landscape (14).webp",
          "../assets/images/landscape/landscape (15).webp"
        ],
        "description": "黄金の草原のひだを歩き、万物を包む火山の鼓動を感じる。"
      },
      {
        "id": "land-21",
        "title": "南国の海岸、変わらぬ日々",
        "client": "Aoshima",
        "year": "2025",
        "cover": "../assets/images/landscape/landscape (16).webp",
        "position": "50% 50%",
        "scale": 1,
        "links": [
          {
            "label": "Instagram 投稿",
            "url": "https://www.instagram.com/p/DTg7ahdk6bq/?img_index=1"
          }
        ],
        "photos": [
          "../assets/images/landscape/landscape (16).webp"
        ],
        "description": "陽光とそよ風が降りる場所に、素朴な日常の風景が留まる。"
      },
      {
        "id": "land-20",
        "title": "光が海に触れるとき",
        "client": "Hyuga Cape",
        "year": "2025",
        "cover": "../assets/images/landscape/landscape (17).webp",
        "position": "50% 50%",
        "scale": 1,
        "links": [
          {
            "label": "Instagram 投稿",
            "url": "https://www.instagram.com/p/DR2Dn8EE7yH/?img_index=1"
          }
        ],
        "photos": [
          "../assets/images/landscape/landscape (17).webp",
          "../assets/images/landscape/landscape (18).webp",
          "../assets/images/landscape/landscape (19).webp",
          "../assets/images/landscape/landscape (20).webp",
          "../assets/images/landscape/landscape (21).webp",
          "../assets/images/landscape/landscape (22).webp",
          "../assets/images/landscape/landscape (23).webp",
          "../assets/images/landscape/landscape (24).webp"
        ],
        "description": "ススキが風に揺れ、青い海のきらめきを映し出す。"
      },
      {
        "id": "land-19",
        "title": "歳月と神々の祝福",
        "client": "Kato Shrine",
        "year": "2025",
        "cover": "../assets/images/landscape/landscape (25).webp",
        "position": "50% 50%",
        "scale": 1,
        "links": [
          {
            "label": "熊本市公式投稿",
            "url": "https://www.instagram.com/p/DU9r74YD2oA/?img_index=1"
          }
        ],
        "photos": [
          "../assets/images/landscape/landscape (25).webp",
          "../assets/images/landscape/landscape (26).webp",
          "../assets/images/landscape/landscape (27).webp",
          "../assets/images/landscape/landscape (28).webp",
          "../assets/images/landscape/landscape (29).webp",
          "../assets/images/landscape/landscape (30).webp"
        ],
        "description": "銀杏と木造社殿が重なり、神前式の厳かな誓いを記録する。"
      },
      {
        "id": "land-18",
        "title": "子ども時代の地平線",
        "client": "Qingtiangang",
        "year": "2025",
        "cover": "../assets/images/landscape/landscape (31).webp",
        "position": "50% 50%",
        "scale": 1.2,
        "links": [
          {
            "label": "Instagram 投稿",
            "url": "https://www.instagram.com/p/DOVsSC4k1bE/?img_index=1"
          }
        ],
        "photos": [
          "../assets/images/landscape/landscape (31).webp",
          "../assets/images/landscape/landscape (32).webp",
          "../assets/images/landscape/landscape (33).webp",
          "../assets/images/landscape/landscape (34).webp",
          "../assets/images/landscape/landscape (35).webp"
        ],
        "description": "そよ風の木柵のそば、無邪気な喜びが駆け回る。"
      },
      {
        "id": "land-17",
        "title": "夕暮れへ帰る道",
        "client": "Qingtiangang",
        "year": "2025",
        "cover": "../assets/images/landscape/landscape (36).webp",
        "position": "50% 50%",
        "scale": 1.2,
        "links": [
          {
            "label": "Instagram 投稿",
            "url": "https://www.instagram.com/p/DPRcXKnEwv0/?img_index=1"
          }
        ],
        "photos": [
          "../assets/images/landscape/landscape (36).webp",
          "../assets/images/landscape/landscape (37).webp",
          "../assets/images/landscape/landscape (38).webp",
          "../assets/images/landscape/landscape (39).webp",
          "../assets/images/landscape/landscape (40).webp",
          "../assets/images/landscape/landscape (41).webp"
        ],
        "description": "夕焼けの桃色の空に、遠い飛行機と巣へ帰る鳥を見つめる。"
      },
      {
        "id": "land-16",
        "title": "大地に共生する楽章",
        "client": "Qingtiangang",
        "year": "2025",
        "cover": "../assets/images/landscape/landscape (42).webp",
        "position": "50% 50%",
        "scale": 1.2,
        "links": [
          {
            "label": "Instagram 投稿",
            "url": "https://www.instagram.com/p/DOqbzSukxJq/?img_index=1"
          }
        ],
        "photos": [
          "../assets/images/landscape/landscape (42).webp",
          "../assets/images/landscape/landscape (43).webp",
          "../assets/images/landscape/landscape (44).webp",
          "../assets/images/landscape/landscape (45).webp",
          "../assets/images/landscape/landscape (46).webp",
          "../assets/images/landscape/landscape (47).webp"
        ],
        "description": "草原で水牛とシラサギが共に生き、自然の美しい均衡を奏でる。"
      },
      {
        "id": "land-15",
        "title": "潮の間に残る幼い記憶",
        "client": "Laomei",
        "year": "2025",
        "cover": "../assets/images/landscape/landscape (48).webp",
        "position": "50% 50%",
        "scale": 1,
        "links": [
          {
            "label": "Instagram 投稿",
            "url": "https://www.instagram.com/p/DPYsaWekx0h/?img_index=1"
          }
        ],
        "photos": [
          "../assets/images/landscape/landscape (48).webp",
          "../assets/images/landscape/landscape (49).webp",
          "../assets/images/landscape/landscape (50).webp"
        ],
        "description": "緑の海食台で、水遊びとカニ捕りを楽しむ子どもたちの無垢な時間。"
      },
      {
        "id": "land-14",
        "title": "幾何学の都市を見下ろす",
        "client": "Urban Geometry",
        "year": "2026",
        "cover": "../assets/images/landscape/landscape (51).webp",
        "position": "50% 50%",
        "scale": 1,
        "links": [
          {
            "label": "Instagram 投稿",
            "url": "https://www.instagram.com/p/DVp3LzlGS4t/"
          }
        ],
        "photos": [
          "../assets/images/landscape/landscape (51).webp"
        ],
        "description": "空から街路の脈絡を切り取り、日常の平行線を織り上げる。"
      },
      {
        "id": "land-13",
        "title": "秋風の中の孤独な背中",
        "client": "Lengshuikeng",
        "year": "2025",
        "cover": "../assets/images/landscape/landscape (52).webp",
        "position": "50% 50%",
        "scale": 1,
        "links": [
          {
            "label": "Instagram 投稿",
            "url": "https://www.instagram.com/p/DQkq2Llk3O5/?img_index=1"
          }
        ],
        "photos": [
          "../assets/images/landscape/landscape (52).webp",
          "../assets/images/landscape/landscape (53).webp",
          "../assets/images/landscape/landscape (54).webp",
          "../assets/images/landscape/landscape (55).webp",
          "../assets/images/landscape/landscape (56).webp"
        ],
        "description": "階段をたどり銀白のススキへ、秋そのものと出会う。"
      },
      {
        "id": "land-12",
        "title": "年の瀬の賑わいと老街の歳月",
        "client": "Dihua Street New Year Market",
        "year": "2025",
        "cover": "../assets/images/landscape/landscape (57).webp",
        "position": "50% 50%",
        "scale": 1,
        "links": [
          {
            "label": "Instagram 投稿",
            "url": "https://www.instagram.com/p/DUp_axzE2T6/?img_index=1"
          }
        ],
        "photos": [
          "../assets/images/landscape/landscape (57).webp",
          "../assets/images/landscape/landscape (58).webp",
          "../assets/images/landscape/landscape (59).webp",
          "../assets/images/landscape/landscape (60).webp",
          "../assets/images/landscape/landscape (61).webp",
          "../assets/images/landscape/landscape (62).webp",
          "../assets/images/landscape/landscape (63).webp",
          "../assets/images/landscape/landscape (64).webp",
          "../assets/images/landscape/landscape (65).webp",
          "../assets/images/landscape/landscape (66).webp"
        ],
        "description": "赤提灯と行き交う人々が、旧市街の濃密な暮らしを映す。"
      },
      {
        "id": "land-11",
        "title": "夜を走る血脈",
        "client": "National Highway",
        "year": "2025",
        "cover": "../assets/images/landscape/landscape (67).webp",
        "position": "50% 50%",
        "scale": 1,
        "links": [
          {
            "label": "Instagram 投稿",
            "url": "https://www.instagram.com/p/DN1kb2LBhkD/"
          }
        ],
        "photos": [
          "../assets/images/landscape/landscape (67).webp"
        ],
        "description": "流れる光跡が静かな夜を裂き、眠らない都市の呼吸をつなぐ。"
      },
      {
        "id": "land-10",
        "title": "雲霧の稜線",
        "client": "Keelung Mountain",
        "year": "2025",
        "cover": "../assets/images/landscape/landscape (68).webp",
        "position": "50% 50%",
        "scale": 1,
        "links": [
          {
            "label": "Instagram 投稿",
            "url": "https://www.instagram.com/p/DMFLMjKhfAW/?img_index=1"
          }
        ],
        "photos": [
          "../assets/images/landscape/landscape (68).webp"
        ],
        "description": "石段を頂へ登り、緑の山と海の間に風の痕跡を探す。"
      },
      {
        "id": "land-9",
        "title": "灯り始める山城の夜",
        "client": "Jiufen",
        "year": "2025",
        "cover": "../assets/images/landscape/landscape (69).webp",
        "position": "50% 50%",
        "scale": 1,
        "links": [
          {
            "label": "Instagram 投稿",
            "url": "https://www.instagram.com/p/DLmSPiwhtVz/?img_index=1"
          }
        ],
        "photos": [
          "../assets/images/landscape/landscape (69).webp"
        ],
        "description": "淡い光が赤提灯を灯し、夕映えの茶楼に長い歳月が重なる。"
      },
      {
        "id": "land-8",
        "title": "御神木の参道の日常",
        "client": "Kengun Shrine",
        "year": "2024",
        "cover": "../assets/images/landscape/landscape (70).webp",
        "position": "50% 50%",
        "scale": 1,
        "links": [
          {
            "label": "Instagram 投稿",
            "url": "https://www.instagram.com/p/DKj9Eg5Bv9Z/"
          }
        ],
        "photos": [
          "../assets/images/landscape/landscape (70).webp"
        ],
        "description": "緑に覆われた古社殿と参道を一人歩き、静謐な朝の光を感じる。"
      },
      {
        "id": "land-7",
        "title": "渓谷の緑の銀河",
        "client": "Jinping Creek",
        "year": "2025",
        "cover": "../assets/images/landscape/landscape (71).webp",
        "position": "50% 50%",
        "scale": 1,
        "links": [
          {
            "label": "Instagram 投稿",
            "url": "https://www.instagram.com/p/DLITEgpBBgD/"
          }
        ],
        "photos": [
          "../assets/images/landscape/landscape (71).webp"
        ],
        "description": "夜が降り、蛍の光が清流と深い森の間を舞う。"
      },
      {
        "id": "land-6",
        "title": "水墨の連山を望む",
        "client": "Jianshi",
        "year": "2025",
        "cover": "../assets/images/landscape/landscape (72).webp",
        "position": "50% 50%",
        "scale": 1,
        "links": [
          {
            "label": "Instagram 投稿",
            "url": "https://www.instagram.com/p/DJtfuj9hZH6/?img_index=1"
          }
        ],
        "photos": [
          "../assets/images/landscape/landscape (72).webp",
          "../assets/images/landscape/landscape (73).webp",
          "../assets/images/landscape/landscape (74).webp",
          "../assets/images/landscape/landscape (75).webp",
          "../assets/images/landscape/landscape (76).webp"
        ],
        "description": "モノクロームが荒々しい山稜を描き、遠い連峰を霧が包む。"
      },
      {
        "id": "land-5",
        "title": "太陽が沈む軌跡",
        "client": "Manhattanhenge",
        "year": "2025",
        "cover": "../assets/images/landscape/landscape (77).webp",
        "position": "50% 50%",
        "scale": 1,
        "links": [
          {
            "label": "Instagram 投稿",
            "url": "https://www.instagram.com/p/DJJlsShBbE_/?img_index=1"
          }
        ],
        "photos": [
          "../assets/images/landscape/landscape (77).webp"
        ],
        "description": "烈日が地平の軌道を降り、ビルの街を温かな金色に染める。"
      },
      {
        "id": "land-4",
        "title": "海に寄り添う日常",
        "client": "Jinshan",
        "year": "2025",
        "cover": "../assets/images/landscape/landscape (78).webp",
        "position": "50% 50%",
        "scale": 1,
        "links": [
          {
            "label": "Instagram 投稿",
            "url": "https://www.instagram.com/p/DIqz6uLBAbj/?img_index=1"
          }
        ],
        "photos": [
          "../assets/images/landscape/landscape (78).webp",
          "../assets/images/landscape/landscape (79).webp",
          "../assets/images/landscape/landscape (80).webp",
          "../assets/images/landscape/landscape (81).webp",
          "../assets/images/landscape/landscape (82).webp"
        ],
        "description": "防波堤の古いバイクと釣り人が、北海岸の海と共にある穏やかな暮らしを描く。"
      },
      {
        "id": "land-3",
        "title": "雲間の光と航路",
        "client": "Sunset",
        "year": "2025",
        "cover": "../assets/images/landscape/landscape (83).webp",
        "position": "50% 50%",
        "scale": 1.2,
        "links": [
          {
            "label": "Instagram 投稿",
            "url": "https://www.instagram.com/p/DIQx_9GJcn_/?img_index=1"
          }
        ],
        "photos": [
          "../assets/images/landscape/landscape (83).webp"
        ],
        "description": "夕雲から光芒が差し、小さな飛行機が夜の彼方へ向かう。"
      },
      {
        "id": "land-2",
        "title": "回転する宇宙の年輪",
        "client": "Star Trails",
        "year": "2025",
        "cover": "../assets/images/landscape/landscape (84).webp",
        "position": "50% 50%",
        "scale": 1,
        "links": [
          {
            "label": "Instagram 投稿",
            "url": "https://www.instagram.com/p/DGsJRsOJGjf/?img_index=1"
          }
        ],
        "photos": [
          "../assets/images/landscape/landscape (84).webp"
        ],
        "description": "時間が夜空で静かに回り、山稜の上に星の軌跡を刻む。"
      },
      {
        "id": "land-1",
        "title": "森の小径の蛍光",
        "client": "Shiding",
        "year": "2026",
        "cover": "../assets/images/landscape/landscape (85).webp",
        "position": "50% 50%",
        "scale": 1,
        "links": [
          {
            "label": "Instagram 投稿",
            "url": "https://www.instagram.com/p/DW_f7LEGaPN/?img_index=1"
          }
        ],
        "photos": [
          "../assets/images/landscape/landscape (85).webp",
          "../assets/images/landscape/landscape (86).webp"
        ],
        "description": "静かな小径を歩き、黄緑の蛍が森の夜をそっと照らす。"
      }
    ]
  },
  "workerApiEndpoint": "https://api.wei.pictures/",
  "clientGalleries": []
};
