/* Generated by scripts/build-locales.mjs. */
window.PORTFOLIO_DATA = {
  "profile": {
    "name": "WEI",
    "subTitle": "Freelance Photographer",
    "tagline": "",
    "avatar": "../assets/images/profile/avatar.webp",
    "location": "Taipei, Taiwan",
    "email": "weipic2023@gmail.com",
    "instagram": "https://www.instagram.com/wei.pictures/",
    "instagramHandle": "@wei.pictures",
    "experienceYears": "2+",
    "stats": [
      {
        "label": "Instagram Followers",
        "value": "7000+"
      },
      {
        "label": "Years of Experience",
        "value": "2+"
      },
      {
        "label": "Collaborations",
        "value": "20+"
      },
      {
        "label": "Photography Awards",
        "value": "7+"
      }
    ],
    "bio": [
      "I'm Wei, an 18-year-old photographer with around two years of experience. I continue to explore new subjects and the stories shaped by light and shadow.",
      "My work spans portraits, landscapes, street photography, sports, and documentary imagery, preserving meaningful moments from everyday life.",
      "Follow along, share your feedback, or get in touch by email or the booking form for photography collaborations.",
      "<a href=\"mailto:weipic2023@gmail.com\">weipic2023@gmail.com</a>"
    ],
    "skills": [
      "Commercial Photography",
      "Portraits",
      "Concert Documentary",
      "Brand & Event Coverage",
      "Sports Photography",
      "Graduation Portraits",
      "Landscape Imagery"
    ]
  },
  "collaborations": [
    {
      "id": "collab-23",
      "brand": "CEWE",
      "role": "CEWE Photo Award 2027 Young Talent Award",
      "year": "2026-2027",
      "category": "International Photography Award",
      "description": "Official Website Cover | Commercial Collaboration",
      "logoText": "CEWE",
      "photos": [
        "../assets/images/collaboration/cewe.webp"
      ],
      "links": [
        {
          "label": "CEWE Photo Award",
          "url": "https://contest.cewe.co.uk/cewephotoaward2027/en_gb/youngtalentaward"
        }
      ]
    },
    {
      "id": "collab-22",
      "brand": "Gogoro",
      "role": "2026 Owner Event: Pop-Up Space City",
      "year": "2026",
      "category": "Brand Collaboration",
      "description": "KOC Social Promotion & Exclusive Offer Campaign | Commercial Collaboration",
      "logoText": "Gogoro",
      "photos": [
        "../assets/images/collaboration/gogoro_story.webp"
      ],
      "links": [
        {
          "label": "Gogoro 2026 Hundred GO Night Ride",
          "url": "https://gogoro2026.oen.tw/events/3FD6X11DEssBRUmforgCWj1wVou"
        }
      ]
    },
    {
      "id": "collab-21",
      "brand": "TAMRON",
      "role": "25-200mm f/2.8-5.6 Di III VXD G2",
      "year": "2026",
      "category": "Commercial",
      "description": "Lens Review",
      "logoText": "TAMRON",
      "galleryId": "comm-9"
    },
    {
      "id": "collab-20",
      "brand": "Youth Photography Award",
      "role": "13th National University Youth Photography Award",
      "year": "2026",
      "category": "Competition",
      "description": "Student Juror with photographer Liao Wen-Hsuan @ontheay.today",
      "logoText": "Youth Photography Award",
      "photos": [
        "../assets/images/collaboration/ntutphotoclub.webp"
      ]
    },
    {
      "id": "collab-19",
      "brand": "SITCON",
      "role": "SITCON 2026",
      "year": "2026",
      "category": "Event Coverage",
      "description": "Academia Sinica | Event Coverage",
      "logoText": "SITCON",
      "galleryId": "ev-5"
    },
    {
      "id": "collab-18",
      "brand": "CyberCube",
      "role": "2026 Taipei Senior High School Education Expo",
      "year": "2026",
      "category": "Event Coverage",
      "description": "CyberCube | Event Coverage",
      "logoText": "CyberCube",
      "galleryId": "ev-7"
    },
    {
      "id": "collab-17",
      "brand": "LiFUNd",
      "role": "LiFUNd 3rd Dream Launch",
      "year": "2026",
      "category": "Event Coverage",
      "description": "Social Innovation Lab | Event Coverage",
      "logoText": "LiFUNd",
      "galleryId": "ev-4"
    },
    {
      "id": "collab-16",
      "brand": "Gaston Luga",
      "role": "Spläsh 2.0 - 16, Sage",
      "year": "2026",
      "category": "Commercial",
      "description": "Brand Collaboration",
      "logoText": "Gaston Luga",
      "galleryId": "comm-2"
    },
    {
      "id": "collab-15",
      "brand": "Threads",
      "role": "First American-Style Graduation Prom & Spring Gala",
      "year": "2026",
      "category": "Event Coverage",
      "description": "2026 Threads' Party | Event Coverage",
      "logoText": "Threads",
      "galleryId": "ev-6"
    },
    {
      "id": "collab-14",
      "brand": "National Taipei University of Technology",
      "role": "NTUT 114th Anniversary",
      "year": "2025",
      "category": "Event Coverage",
      "description": "Honoring Distinguished Alumni | Event Coverage",
      "logoText": "National Taipei University of Technology",
      "galleryId": "ev-2"
    },
    {
      "id": "collab-13",
      "brand": "NTUT COLAZ",
      "role": "Classic American Varsity Jacket",
      "year": "2025",
      "category": "Commercial",
      "description": "Commercial Collaboration",
      "logoText": "NTUT COLAZ",
      "galleryId": "comm-3"
    },
    {
      "id": "collab-12",
      "brand": "HOKKI",
      "role": "No. 3 Perfume",
      "year": "2025",
      "category": "Commercial",
      "description": "Commercial Collaboration",
      "logoText": "HOKKI",
      "galleryId": "comm-4"
    },
    {
      "id": "collab-11",
      "brand": "Gaston Luga",
      "role": "Spläsh Utility Backpack 16, Latte",
      "year": "2025",
      "category": "Commercial",
      "description": "Brand Collaboration",
      "logoText": "Gaston Luga",
      "galleryId": "comm-1"
    },
    {
      "id": "collab-10",
      "brand": "Cyr Wheel Artist Yang Shih-Hao",
      "role": "Dance to the Extreme X The One | Chimei Museum",
      "year": "2025",
      "category": "Large-Scale Performance",
      "description": "Photographer",
      "logoText": "Cyr Wheel Artist Yang Shih-Hao",
      "galleryId": "ev-8"
    },
    {
      "id": "collab-9",
      "brand": "TAMRON",
      "role": "20-40mm f/2.8 Di III VXD",
      "year": "2025",
      "category": "Commercial",
      "description": "Lens Review",
      "logoText": "TAMRON",
      "galleryId": "comm-8"
    },
    {
      "id": "collab-7",
      "brand": "MAHIRU",
      "role": "2025  茉ひる ASIA TOUR 『SeRendipity』in TAIPEI",
      "year": "2025",
      "category": "Concert",
      "description": "Photographer for Japanese singer Mahiru's Asia Tour in Taipei",
      "logoText": "MAHIRU",
      "galleryId": "conc-6"
    },
    {
      "id": "collab-6",
      "brand": "NTUT Aliyan Indigenous Culture Society",
      "role": "Patikol: Returning to the Nest — Torik Tribal Music & Dance Theatre",
      "year": "2025",
      "category": "Event Coverage",
      "description": "Event Coverage",
      "logoText": "NTUT Aliyan",
      "galleryId": "ev-11"
    },
    {
      "id": "collab-5",
      "brand": "PNGL",
      "role": "LIGHTZIP 27–32L Roll-Top Backpack",
      "year": "2025",
      "category": "Commercial",
      "description": "Brand Collaboration",
      "logoText": "PNGL",
      "galleryId": "comm-7"
    },
    {
      "id": "collab-3",
      "brand": "KASE",
      "role": "CPL III Polarizing Filter Review",
      "year": "2025",
      "category": "Commercial",
      "description": "Gear Review",
      "logoText": "KASE"
    },
    {
      "id": "collab-2",
      "brand": "PENTAX",
      "role": "Pentax 17 Film Camera",
      "year": "2024",
      "category": "Commercial",
      "description": "Gear Review",
      "logoText": "PENTAX",
      "galleryId": "comm-10"
    },
    {
      "id": "collab-1",
      "brand": "Gaston Luga",
      "role": "GL x Nikon Collaboration Backpack",
      "year": "2024",
      "category": "Commercial",
      "description": "Brand Collaboration",
      "logoText": "Gaston Luga"
    }
  ],
  "awards": [
    {
      "id": "award-7",
      "year": "2025",
      "title": "National Geographic Taiwan Photography Contest",
      "category": "Youth Category",
      "result": "Finalist",
      "description": "Finalist in the Youth Category of the 2025 National Geographic Taiwan Photography Contest",
      "photos": [
        "../assets/images/award/國家地理台灣青年入圍.webp"
      ],
      "links": [
        {
          "label": "Instagram Post",
          "url": "https://www.instagram.com/p/DNqclZphgC4/"
        }
      ]
    },
    {
      "id": "award-6",
      "year": "2025",
      "title": "National Student Photography Competition",
      "category": "Student Competition",
      "result": "Bronze Award",
      "description": "Bronze Award, 2025 National Student Photography Competition",
      "photos": [
        "../assets/images/award/全國學生攝影銅獎 (1).webp",
        "../assets/images/award/全國學生攝影銅獎 (2).webp",
        "../assets/images/award/全國學生攝影銅獎 (3).webp",
        "../assets/images/award/全國學生攝影銅獎 (4).webp",
        "../assets/images/award/全國學生攝影銅獎 (5).webp"
      ],
      "links": [
        {
          "label": "Instagram Post",
          "url": "https://www.instagram.com/p/DJ-_kXTJV9s/?img_index=1"
        }
      ]
    },
    {
      "id": "award-5",
      "year": "2025",
      "title": "National Student Photography Competition",
      "category": "Student Competition",
      "result": "Special Award",
      "description": "Special Award, 2025 National Student Photography Competition",
      "photos": [
        "../assets/images/award/全國學生攝影特別獎 (1).webp",
        "../assets/images/award/全國學生攝影特別獎 (2).webp",
        "../assets/images/award/全國學生攝影特別獎 (3).webp",
        "../assets/images/award/全國學生攝影特別獎 (4).webp",
        "../assets/images/award/全國學生攝影特別獎 (5).webp"
      ],
      "links": [
        {
          "label": "Instagram Post",
          "url": "https://www.instagram.com/p/DJtfuj9hZH6/?img_index=1"
        }
      ]
    },
    {
      "id": "award-4",
      "year": "2025",
      "title": "Canon Taiwan 6th Campus Ambassador",
      "category": "Campus Ambassador",
      "result": "Final-Round Selection",
      "description": "Selected as a finalist for the 6th Canon Taiwan Campus Photography Ambassador program"
    },
    {
      "id": "award-3",
      "year": "2025",
      "title": "National University Youth Photography Award",
      "category": "University Competition",
      "result": "Finalist",
      "description": "Finalist, 12th National University Youth Photography Award (2025)"
    },
    {
      "id": "award-2",
      "year": "2025",
      "title": "Japan High School Student Photography Contest",
      "category": "Single Photo Category",
      "result": "Selected Work",
      "description": "Selected Work, 12th Japan High School Student Photography Contest — Single Photo Category"
    },
    {
      "id": "award-1",
      "year": "2024",
      "title": "Japan High School Student Photography Contest",
      "category": "Single Photo Category",
      "result": "Selected Work",
      "description": "Selected Work, 11th Japan High School Student Photography Contest — Single Photo Category"
    }
  ],
  "categories": [
    {
      "id": "commercial",
      "title": "Commercial Photography",
      "titleEn": "Commercial Photography",
      "description": "Product and brand imagery crafted to express a distinctive visual identity.",
      "cover": "../assets/images/commercial/Gastonluga2 (2).webp",
      "pageUrl": "commercial.html",
      "badge": "Commercial"
    },
    {
      "id": "portrait",
      "title": "Portrait Photography",
      "titleEn": "Portrait Photography",
      "description": "Personal portraits and profile photography that reveal individual character.",
      "cover": "../assets/images/portrait/passerby (3).webp",
      "pageUrl": "portrait.html",
      "badge": "Portrait",
      "position": "40% 70%",
      "scale": 1.1
    },
    {
      "id": "concert",
      "title": "Concert Photography",
      "titleEn": "Concert Photography",
      "description": "Capturing stage light, performance intensity, and the energy of the crowd.",
      "cover": "../assets/images/concert/911 (1).webp",
      "pageUrl": "concert.html",
      "badge": "Concert",
      "position": "bottom center",
      "scale": 1.3
    },
    {
      "id": "event",
      "title": "Event Photography",
      "titleEn": "Event Photography",
      "description": "Complete coverage of events, launches, and corporate gatherings.",
      "cover": "../assets/images/event/Lulu (1).webp",
      "pageUrl": "event.html",
      "badge": "Event"
    },
    {
      "id": "sports",
      "title": "Sports Photography",
      "titleEn": "Sports Photography",
      "description": "Freezing decisive moments to convey the speed and power of competition.",
      "cover": "../assets/images/sports/WDragons0526 (1).webp",
      "pageUrl": "sports.html",
      "badge": "Sports",
      "position": "bottom center",
      "scale": 1.2
    },
    {
      "id": "graduation",
      "title": "Graduation Photography",
      "titleEn": "Graduation Photography",
      "description": "Campus portraits and group photos that preserve a milestone in youth.",
      "cover": "../assets/images/graduation/NYCU (6).webp",
      "pageUrl": "graduation.html",
      "badge": "Graduation"
    },
    {
      "id": "landscape",
      "title": "Landscape Photography",
      "titleEn": "Landscape Photography",
      "description": "Natural vistas, dramatic mountains, waterscapes, and cities.",
      "cover": "../assets/images/landscape/landscape1.webp",
      "pageUrl": "landscape.html",
      "badge": "Landscape"
    }
  ],
  "galleries": {
    "commercial": [
      {
        "id": "comm-1",
        "title": "Gaston Luga Spläsh Utility Backpack 16, Latte",
        "client": "Gaston Luga",
        "year": "2025",
        "cover": "../assets/images/commercial/Gastonluga2 (10).webp",
        "position": "center 65%",
        "links": [
          {
            "label": "Official Brand Website",
            "url": "https://gastonluga.com/tw"
          },
          {
            "label": "Instagram Post",
            "url": "https://www.instagram.com/p/DTDKdk0EnQE/?img_index=1"
          }
        ],
        "photos": [
          "../assets/images/commercial/Gastonluga2 (1).webp",
          "../assets/images/commercial/Gastonluga2 (2).webp",
          "../assets/images/commercial/Gastonluga2 (3).webp",
          "../assets/images/commercial/Gastonluga2 (4).webp",
          "../assets/images/commercial/Gastonluga2 (5).webp",
          "../assets/images/commercial/Gastonluga2 (6).webp",
          "../assets/images/commercial/Gastonluga2 (7).webp",
          "../assets/images/commercial/Gastonluga2 (8).webp",
          "../assets/images/commercial/Gastonluga2 (9).webp",
          "../assets/images/commercial/Gastonluga2 (10).webp"
        ],
        "description": "Clean Nordic minimalism pairs a natural latte palette with restrained shadows, highlighting generous storage and refined craftsmanship."
      },
      {
        "id": "comm-2",
        "title": "Gaston Luga Spläsh 2.0-16, Sage",
        "client": "Gaston Luga",
        "year": "2026",
        "cover": "../assets/images/commercial/Gastonluga3 (1).webp",
        "position": "center center",
        "links": [
          {
            "label": "Official Brand Website",
            "url": "https://gastonluga.com/tw"
          },
          {
            "label": "Instagram Post",
            "url": "https://www.instagram.com/p/DVF_g4PE7zV/?img_index=1"
          }
        ],
        "photos": [
          "../assets/images/commercial/Gastonluga3 (1).webp",
          "../assets/images/commercial/Gastonluga3 (2).webp",
          "../assets/images/commercial/Gastonluga3 (3).webp",
          "../assets/images/commercial/Gastonluga3 (4).webp",
          "../assets/images/commercial/Gastonluga3 (5).webp",
          "../assets/images/commercial/Gastonluga3 (6).webp",
          "../assets/images/commercial/Gastonluga3 (7).webp",
          "../assets/images/commercial/Gastonluga3 (8).webp",
          "../assets/images/commercial/Gastonluga3 (9).webp",
          "../assets/images/commercial/Gastonluga3 (10).webp"
        ],
        "description": "An urban bag balancing function and style, with sage green and matte-black details that feel versatile, understated, and practical."
      },
      {
        "id": "comm-3",
        "title": "NTUT Colaz Classic Varsity Jacket",
        "client": "Colaz",
        "year": "2025",
        "cover": "../assets/images/commercial/NtutColaz (1).webp",
        "position": "center 25%",
        "links": [
          {
            "label": "Instagram Post",
            "url": "https://www.instagram.com/p/DRUP44EkvxO/?igsh=Z25xcWlmd2d2OXdo"
          }
        ],
        "photos": [
          "../assets/images/commercial/NtutColaz (1).webp",
          "../assets/images/commercial/NtutColaz (2).webp",
          "../assets/images/commercial/NtutColaz (3).webp",
          "../assets/images/commercial/NtutColaz (4).webp",
          "../assets/images/commercial/NtutColaz (5).webp",
          "../assets/images/commercial/NtutColaz (6).webp",
          "../assets/images/commercial/NtutColaz (7).webp",
          "../assets/images/commercial/NtutColaz (8).webp"
        ],
        "description": "NTUT Baseball Team × NTUT Colaz"
      },
      {
        "id": "comm-4",
        "title": "HOKKI No. 3 Perfume",
        "client": "Hokki",
        "year": "2025",
        "cover": "../assets/images/commercial/Hokki (3).webp",
        "position": "center center",
        "links": [
          {
            "label": "Official Brand Website",
            "url": "https://hokki.shoplineapp.com/"
          },
          {
            "label": "Instagram Post",
            "url": "https://www.instagram.com/p/DRtAixbEgbt/?img_index=1"
          }
        ],
        "photos": [
          "../assets/images/commercial/Hokki (1).webp",
          "../assets/images/commercial/Hokki (2).webp",
          "../assets/images/commercial/Hokki (3).webp",
          "../assets/images/commercial/Hokki (4).webp",
          "../assets/images/commercial/Hokki (5).webp",
          "../assets/images/commercial/Hokki (6).webp"
        ],
        "description": "A minimalist fragrance study in deep, subdued tones."
      },
      {
        "id": "comm-7",
        "title": "LIGHTZIP 27–32L Lightweight Roll-Top Backpack",
        "client": "PNGL",
        "year": "2025",
        "cover": "../assets/images/commercial/PNGL (3).webp",
        "position": "center 20%",
        "links": [
          {
            "label": "Instagram Post",
            "url": "https://www.instagram.com/p/DJloNuMpnxU/?img_index=1"
          }
        ],
        "photos": [
          "../assets/images/commercial/PNGL (1).webp",
          "../assets/images/commercial/PNGL (2).webp",
          "../assets/images/commercial/PNGL (3).webp",
          "../assets/images/commercial/PNGL (4).webp",
          "../assets/images/commercial/PNGL (5).webp"
        ],
        "description": "Technical performance for everyday use: ultralight and water-resistant."
      },
      {
        "id": "comm-8",
        "title": "20-40mm f/2.8 Di III VXD",
        "client": "Tamron",
        "year": "2025",
        "cover": "../assets/images/commercial/TamronA062 (1).webp",
        "position": "50% 0%",
        "links": [
          {
            "label": "Instagram Post",
            "url": "https://www.instagram.com/p/DNmro31hpW_/?img_index=1"
          }
        ],
        "photos": [
          "../assets/images/commercial/TamronA062 (1).webp",
          "../assets/images/commercial/TamronA062 (2).webp",
          "../assets/images/commercial/TamronA062 (3).webp"
        ],
        "description": "Lens Review"
      },
      {
        "id": "comm-9",
        "title": "25-200mm f/2.8-5.6 DiIII VXD G2",
        "client": "Tamron",
        "year": "2026",
        "cover": "../assets/images/commercial/TamronA075 (2).webp",
        "links": [
          {
            "label": "Instagram Post",
            "url": "https://www.instagram.com/p/DaT-NJVGcDO/?img_index=1"
          }
        ],
        "photos": [
          "../assets/images/commercial/TamronA075 (1).webp",
          "../assets/images/commercial/TamronA075 (2).webp",
          "../assets/images/commercial/TamronA075 (3).webp",
          "../assets/images/commercial/TamronA075 (4).webp",
          "../assets/images/commercial/TamronA075 (5).webp",
          "../assets/images/commercial/TamronA075 (6).webp"
        ],
        "description": "Lens Review"
      },
      {
        "id": "comm-10",
        "title": "Pentax 17 Film Camera",
        "client": "PENTAX",
        "year": "2024",
        "cover": "../assets/images/commercial/PENTAX17 (1).webp",
        "links": [
          {
            "label": "Instagram Post",
            "url": "https://www.instagram.com/p/DDEi4Tmv7TO/?img_index=1"
          }
        ],
        "photos": [
          "../assets/images/commercial/PENTAX17 (1).webp",
          "../assets/images/commercial/PENTAX17 (2).webp",
          "../assets/images/commercial/PENTAX17 (3).webp",
          "../assets/images/commercial/PENTAX17 (4).webp",
          "../assets/images/commercial/PENTAX17 (5).webp",
          "../assets/images/commercial/PENTAX17 (6).webp",
          "../assets/images/commercial/PENTAX17 (7).webp",
          "../assets/images/commercial/PENTAX17 (8).webp",
          "../assets/images/commercial/PENTAX17 (9).webp",
          "../assets/images/commercial/PENTAX17 (10).webp"
        ],
        "description": "Gear Review"
      }
    ],
    "portrait": [
      {
        "id": "port-2",
        "title": "Showa Romance — Zixic",
        "client": "Zixic",
        "year": "2025",
        "cover": "../assets/images/portrait/Zixic (6).webp",
        "position": "10% 65%",
        "links": [
          {
            "label": "Instagram Post",
            "url": "https://www.instagram.com/p/DPwUtZOjo0c/?img_index=1"
          }
        ],
        "photos": [
          "../assets/images/portrait/Zixic (1).webp",
          "../assets/images/portrait/Zixic (2).webp",
          "../assets/images/portrait/Zixic (3).webp",
          "../assets/images/portrait/Zixic (4).webp",
          "../assets/images/portrait/Zixic (5).webp",
          "../assets/images/portrait/Zixic (6).webp",
          "../assets/images/portrait/Zixic (7).webp",
          "../assets/images/portrait/Zixic (8).webp",
          "../assets/images/portrait/Zixic (9).webp",
          "../assets/images/portrait/Zixic (10).webp",
          "../assets/images/portrait/Zixic (11).webp",
          "../assets/images/portrait/Zixic (12).webp",
          "../assets/images/portrait/Zixic (13).webp"
        ],
        "description": "An afternoon on a Showa-era street corner."
      },
      {
        "id": "port-3",
        "title": "Taiwanese Sentiment",
        "client": "Farah",
        "year": "2026",
        "cover": "../assets/images/portrait/Farah (2).webp",
        "position": "center 65%",
        "photos": [
          "../assets/images/portrait/Farah (1).webp",
          "../assets/images/portrait/Farah (2).webp",
          "../assets/images/portrait/Farah (3).webp",
          "../assets/images/portrait/Farah (4).webp",
          "../assets/images/portrait/Farah (5).webp",
          "../assets/images/portrait/Farah (6).webp",
          "../assets/images/portrait/Farah (7).webp",
          "../assets/images/portrait/Farah (8).webp"
        ],
        "description": "A story of light and shadow through Taiwan's old lanes."
      },
      {
        "id": "port-4",
        "title": "Military Dependents' Village Portraits",
        "client": "陳小羊",
        "year": "2025",
        "cover": "../assets/images/portrait/陳小羊 (9).webp",
        "photos": [
          "../assets/images/portrait/陳小羊 (1).webp",
          "../assets/images/portrait/陳小羊 (2).webp",
          "../assets/images/portrait/陳小羊 (3).webp",
          "../assets/images/portrait/陳小羊 (4).webp",
          "../assets/images/portrait/陳小羊 (5).webp",
          "../assets/images/portrait/陳小羊 (6).webp",
          "../assets/images/portrait/陳小羊 (7).webp",
          "../assets/images/portrait/陳小羊 (8).webp",
          "../assets/images/portrait/陳小羊 (9).webp",
          "../assets/images/portrait/陳小羊 (10).webp"
        ],
        "description": "Memories of a village where time seems to turn back."
      },
      {
        "id": "port-5",
        "title": "Who We Became, and the Youth We Shared",
        "client": "みに",
        "year": "2025",
        "cover": "../assets/images/portrait/Mini (2).webp",
        "position": "center 60%",
        "photos": [
          "../assets/images/portrait/Mini (1).webp",
          "../assets/images/portrait/Mini (2).webp",
          "../assets/images/portrait/Mini (3).webp",
          "../assets/images/portrait/Mini (4).webp",
          "../assets/images/portrait/Mini (5).webp",
          "../assets/images/portrait/Mini (6).webp",
          "../assets/images/portrait/Mini (7).webp",
          "../assets/images/portrait/Mini (8).webp"
        ],
        "description": "In uniform, we meet our younger selves again."
      },
      {
        "id": "port-6",
        "title": "A Walk Through Time on Dihua Street",
        "client": "Peggy",
        "year": "2025",
        "cover": "../assets/images/portrait/Peggy (1).webp",
        "position": "55% 90%",
        "photos": [
          "../assets/images/portrait/Peggy (1).webp",
          "../assets/images/portrait/Peggy (2).webp",
          "../assets/images/portrait/Peggy (3).webp",
          "../assets/images/portrait/Peggy (4).webp",
          "../assets/images/portrait/Peggy (5).webp",
          "../assets/images/portrait/Peggy (6).webp",
          "../assets/images/portrait/Peggy (7).webp",
          "../assets/images/portrait/Peggy (8).webp",
          "../assets/images/portrait/Peggy (9).webp",
          "../assets/images/portrait/Peggy (10).webp"
        ],
        "description": "Searching for old-city memories in traces left by time."
      },
      {
        "id": "port-7",
        "title": "Hanfu Beneath Taigang Cherry Blossoms",
        "client": "飄逸",
        "year": "2025",
        "cover": "../assets/images/portrait/飄逸 (3).webp",
        "position": "60% 50%",
        "photos": [
          "../assets/images/portrait/飄逸 (1).webp",
          "../assets/images/portrait/飄逸 (2).webp",
          "../assets/images/portrait/飄逸 (3).webp"
        ],
        "description": "A distinctly Eastern sense of romance."
      },
      {
        "id": "port-8",
        "title": "Christmas Family Portraits",
        "client": "Christmas",
        "year": "2024",
        "cover": "../assets/images/portrait/CH1218 (2).webp",
        "position": "50% 50%",
        "photos": [
          "../assets/images/portrait/CH1218 (4).webp",
          "../assets/images/portrait/CH1218 (5).webp",
          "../assets/images/portrait/CH1218 (3).webp",
          "../assets/images/portrait/CH1218 (2).webp",
          "../assets/images/portrait/CH1218 (1).webp"
        ],
        "description": "Warm moments that light up a winter night."
      },
      {
        "id": "port-9",
        "title": "Everyday Joys in the City",
        "client": "Passerby",
        "year": "2024-2025",
        "cover": "../assets/images/portrait/passerby (3).webp",
        "position": "30% 70%",
        "photos": [
          "../assets/images/portrait/passerby (3).webp",
          "../assets/images/portrait/passerby (9).webp",
          "../assets/images/portrait/passerby (7).webp",
          "../assets/images/portrait/passerby (10).webp",
          "../assets/images/portrait/passerby (8).webp",
          "../assets/images/portrait/passerby (2).webp"
        ],
        "description": "An everyday scene whose meaning belongs only to us."
      },
      {
        "id": "port-10",
        "title": "Faces of the Street",
        "client": "Passerby",
        "year": "2025",
        "cover": "../assets/images/portrait/passerby (4).webp",
        "position": "25% 70%",
        "photos": [
          "../assets/images/portrait/passerby (1).webp",
          "../assets/images/portrait/passerby (4).webp",
          "../assets/images/portrait/passerby (5).webp",
          "../assets/images/portrait/passerby (6).webp"
        ],
        "description": "Candid, honest moments held still amid the city's rush."
      }
    ],
    "concert": [
      {
        "id": "conc-1",
        "title": "Johnson Health Tech 50th Anniversary Charity Concert",
        "client": "Taipei Dome",
        "year": "2026",
        "cover": "../assets/images/concert/911 (1).webp",
        "position": "center center",
        "photos": [
          "../assets/images/concert/911 (1).webp",
          "../assets/images/concert/911 (2).webp",
          "../assets/images/concert/911 (3).webp",
          "../assets/images/concert/911 (4).webp",
          "../assets/images/concert/911 (5).webp",
          "../assets/images/concert/911 (6).webp",
          "../assets/images/concert/911 (7).webp"
        ],
        "description": "feat. Nine One One"
      },
      {
        "id": "conc-2",
        "title": "Johnson Health Tech 50th Anniversary Charity Concert",
        "client": "Taipei Dome",
        "year": "2026",
        "cover": "../assets/images/concert/ALin (2).webp",
        "position": "center center",
        "photos": [
          "../assets/images/concert/ALin (1).webp",
          "../assets/images/concert/ALin (2).webp",
          "../assets/images/concert/ALin (3).webp",
          "../assets/images/concert/ALin (4).webp",
          "../assets/images/concert/ALin (5).webp",
          "../assets/images/concert/ALin (6).webp",
          "../assets/images/concert/ALin (7).webp",
          "../assets/images/concert/ALin (8).webp"
        ],
        "description": "feat. A-Lin"
      },
      {
        "id": "conc-3",
        "title": "Johnson Health Tech 50th Anniversary Charity Concert",
        "client": "Taipei Dome",
        "year": "2026",
        "cover": "../assets/images/concert/EricChou (4).webp",
        "position": "bottom center",
        "scale": 1.3,
        "photos": [
          "../assets/images/concert/EricChou (1).webp",
          "../assets/images/concert/EricChou (2).webp",
          "../assets/images/concert/EricChou (3).webp",
          "../assets/images/concert/EricChou (4).webp",
          "../assets/images/concert/EricChou (5).webp",
          "../assets/images/concert/EricChou (6).webp"
        ],
        "description": "feat. Eric Chou"
      },
      {
        "id": "conc-4",
        "title": "Johnson Health Tech 50th Anniversary Charity Concert",
        "client": "Taipei Dome",
        "year": "2026",
        "cover": "../assets/images/concert/CrowdLu (8).webp",
        "position": "35% 60%",
        "photos": [
          "../assets/images/concert/CrowdLu (1).webp",
          "../assets/images/concert/CrowdLu (2).webp",
          "../assets/images/concert/CrowdLu (3).webp",
          "../assets/images/concert/CrowdLu (4).webp",
          "../assets/images/concert/CrowdLu (5).webp",
          "../assets/images/concert/CrowdLu (6).webp",
          "../assets/images/concert/CrowdLu (7).webp",
          "../assets/images/concert/CrowdLu (8).webp"
        ],
        "description": "feat. Crowd Lu"
      },
      {
        "id": "conc-5",
        "title": "Johnson Health Tech 50th Anniversary Charity Concert",
        "client": "Taipei Dome",
        "year": "2026",
        "cover": "../assets/images/concert/AccuseFive (2).webp",
        "position": "center center",
        "photos": [
          "../assets/images/concert/AccuseFive (1).webp",
          "../assets/images/concert/AccuseFive (2).webp",
          "../assets/images/concert/AccuseFive (3).webp",
          "../assets/images/concert/AccuseFive (4).webp",
          "../assets/images/concert/AccuseFive (5).webp",
          "../assets/images/concert/AccuseFive (6).webp",
          "../assets/images/concert/AccuseFive (7).webp",
          "../assets/images/concert/AccuseFive (8).webp"
        ],
        "description": "feat. Accusefive"
      },
      {
        "id": "conc-6",
        "title": "2025 茉ひる ASIA TOUR『SeRendipity』in TAIPEI",
        "client": "Legacy Tera",
        "year": "2025",
        "cover": "../assets/images/concert/Mahiru (1).webp",
        "position": "bottom center",
        "scale": 1.1,
        "photos": [
          "../assets/images/concert/Mahiru (1).webp",
          "../assets/images/concert/Mahiru (2).webp",
          "../assets/images/concert/Mahiru (3).webp",
          "../assets/images/concert/Mahiru (4).webp",
          "../assets/images/concert/Mahiru (5).webp",
          "../assets/images/concert/Mahiru (6).webp",
          "../assets/images/concert/Mahiru (7).webp",
          "../assets/images/concert/Mahiru (8).webp",
          "../assets/images/concert/Mahiru (9).webp",
          "../assets/images/concert/Mahiru (10).webp"
        ],
        "description": "May 31, 2025 | feat. Rinzo, Patrick Brasca"
      },
      {
        "id": "conc-7",
        "title": "2025 茉ひる ASIA TOUR 『SeRendipity』",
        "client": "MAHIRU",
        "year": "2025",
        "cover": "../assets/images/concert/MahiruGoods (1).webp",
        "photos": [
          "../assets/images/concert/MahiruGoods (1).webp",
          "../assets/images/concert/MahiruGoods (2).webp",
          "../assets/images/concert/MahiruGoods (3).webp"
        ],
        "description": "Hong Kong · Bangkok · Osaka · Tokyo · Kaohsiung · Taipei | Tour Merchandise"
      },
      {
        "id": "conc-8",
        "title": "Pika Chiu 2024 Christmas Eve Pop-Up Performance",
        "client": "Pika Chiu",
        "year": "2024",
        "cover": "../assets/images/concert/PikaChiu1224 (1).webp",
        "position": "50% 90%",
        "scale": 1,
        "photos": [
          "../assets/images/concert/PikaChiu1224 (1).webp",
          "../assets/images/concert/PikaChiu1224 (2).webp",
          "../assets/images/concert/PikaChiu1224 (3).webp",
          "../assets/images/concert/PikaChiu1224 (4).webp",
          "../assets/images/concert/PikaChiu1224 (5).webp",
          "../assets/images/concert/PikaChiu1224 (6).webp",
          "../assets/images/concert/PikaChiu1224 (7).webp",
          "../assets/images/concert/PikaChiu1224 (8).webp",
          "../assets/images/concert/PikaChiu1224 (9).webp",
          "../assets/images/concert/PikaChiu1224 (10).webp"
        ],
        "description": "Eslite Spectrum Wuchang, Ximending"
      }
    ],
    "event": [
      {
        "id": "ev-1",
        "title": "Johnson Health Tech 50th Anniversary Charity Concert",
        "client": "Taipei Dome",
        "year": "2026",
        "cover": "../assets/images/event/Lulu (2).webp",
        "position": "40% 85%",
        "scale": 1.2,
        "links": [
          {
            "label": "Lulu Instagram Post",
            "url": "https://www.instagram.com/p/DTyASBCEj_b/"
          }
        ],
        "photos": [
          "../assets/images/event/Lulu (1).webp",
          "../assets/images/event/Lulu (2).webp",
          "../assets/images/event/Lulu (3).webp",
          "../assets/images/event/Lulu (4).webp",
          "../assets/images/event/Lulu (5).webp",
          "../assets/images/event/Lulu (6).webp",
          "../assets/images/event/Lulu (7).webp",
          "../assets/images/event/Lulu (8).webp"
        ],
        "description": "feat. Hank Chen and Lulu"
      },
      {
        "id": "ev-2",
        "title": "NTUT 114th Anniversary",
        "client": "NTUT",
        "year": "2025",
        "cover": "../assets/images/event/NTUT114 (3).webp",
        "links": [
          {
            "label": "Commercial Times",
            "url": "https://www.ctee.com.tw/news/20251101700632-431204"
          },
          {
            "label": "Liberty Times",
            "url": "https://news.ltn.com.tw/news/Taipei/breakingnews/5231061"
          },
          {
            "label": "Economic Daily News",
            "url": "https://money.udn.com/money/story/5723/9111589"
          },
          {
            "label": "Central News Agency",
            "url": "https://www.cna.com.tw/news/ahel/202511010121.aspx"
          },
          {
            "label": "NTUT News",
            "url": "https://news.ntut.edu.tw/p/406-1000-149442,r11.php?Lang=zh-tw"
          },
          {
            "label": "NOWNEWS",
            "url": "https://www.nownews.com/news/6749187"
          },
          {
            "label": "Yahoo Taiwan",
            "url": "https://tw.news.yahoo.com/%E7%8E%8B%E4%B8%96%E5%A0%85%EF%BC%9A%E5%BE%9E%E6%94%BF20%E5%B9%B4%E4%BE%86%E6%9C%80%E5%85%89%E6%A6%AE%E7%9A%84%E4%B8%80%E5%A4%A9%EF%BC%81%E7%8D%B2%E9%A0%92%E5%8C%97%E7%A7%91%E5%A4%A7%E5%90%8D%E8%AD%BD%E5%8D%9A%E5%A3%AB-%E5%9B%9E%E6%86%B6%E5%B9%B4%E5%B0%91%E8%88%8A%E6%9B%B8%E6%94%A4%E6%84%9F%E5%8B%95-072253911.html"
          }
        ],
        "photos": [
          "../assets/images/event/NTUT114 (1).webp",
          "../assets/images/event/NTUT114 (2).webp",
          "../assets/images/event/NTUT114 (3).webp",
          "../assets/images/event/NTUT114 (4).webp",
          "../assets/images/event/NTUT114 (5).webp",
          "../assets/images/event/NTUT114 (6).webp",
          "../assets/images/event/NTUT114 (7).webp",
          "../assets/images/event/NTUT114 (8).webp",
          "../assets/images/event/NTUT114 (9).webp",
          "../assets/images/event/NTUT114 (10).webp",
          "../assets/images/event/NTUT114 (11).webp",
          "../assets/images/event/NTUT114 (12).webp",
          "../assets/images/event/NTUT114 (13).webp",
          "../assets/images/event/NTUT114 (14).webp",
          "../assets/images/event/NTUT114 (15).webp"
        ],
        "description": "Honoring distinguished alumni; honorary doctorates awarded to Yen Chih-Fa, Wang Shih-Chien, and Lin Tien-Mao."
      },
      {
        "id": "ev-3",
        "title": "Woven Upon a Blank Canvas",
        "client": "AEUST",
        "year": "2026",
        "cover": "../assets/images/event/EspaceLibre (1).webp",
        "position": "50% 35%",
        "scale": 1.4,
        "photos": [
          "../assets/images/event/EspaceLibre (1).webp",
          "../assets/images/event/EspaceLibre (2).webp",
          "../assets/images/event/EspaceLibre (3).webp",
          "../assets/images/event/EspaceLibre (4).webp",
          "../assets/images/event/EspaceLibre (5).webp",
          "../assets/images/event/EspaceLibre (6).webp",
          "../assets/images/event/EspaceLibre (7).webp",
          "../assets/images/event/EspaceLibre (8).webp",
          "../assets/images/event/EspaceLibre (9).webp",
          "../assets/images/event/EspaceLibre (10).webp",
          "../assets/images/event/EspaceLibre (11).webp",
          "../assets/images/event/EspaceLibre (12).webp",
          "../assets/images/event/EspaceLibre (13).webp",
          "../assets/images/event/EspaceLibre (14).webp",
          "../assets/images/event/EspaceLibre (15).webp"
        ],
        "description": "12th Graduation Exhibition, Department of Materials and Textiles, Asia Eastern University of Science and Technology"
      },
      {
        "id": "ev-4",
        "title": "LiFUNd 3rd Dream Launch",
        "client": "LiFUNd",
        "year": "2026",
        "cover": "../assets/images/event/1.webp",
        "links": [
          {
            "label": "Economic Daily News",
            "url": "https://money.udn.com/money/story/5635/9386900"
          }
        ],
        "photos": [
          "../assets/images/event/1.webp",
          "../assets/images/event/2.webp",
          "../assets/images/event/3.webp",
          "../assets/images/event/4.webp",
          "../assets/images/event/5.webp"
        ],
        "description": "2026.03.06"
      },
      {
        "id": "ev-5",
        "title": "SITCON 2026 Student Computing Conference",
        "client": "SITCON",
        "year": "2026",
        "cover": "../assets/images/event/10.webp",
        "position": "40% 70%",
        "photos": [
          "../assets/images/event/6.webp",
          "../assets/images/event/7.webp",
          "../assets/images/event/8.webp",
          "../assets/images/event/9.webp",
          "../assets/images/event/10.webp"
        ],
        "description": "Academia Sinica"
      },
      {
        "id": "ev-6",
        "title": "2026 Threads’ Party",
        "client": "Treads",
        "year": "2026",
        "cover": "../assets/images/event/15.webp",
        "photos": [
          "../assets/images/event/11.webp",
          "../assets/images/event/12.webp",
          "../assets/images/event/13.webp",
          "../assets/images/event/14.webp",
          "../assets/images/event/15.webp"
        ],
        "description": "First American-Style Graduation Prom & Spring Gala"
      },
      {
        "id": "ev-7",
        "title": "CyberCube",
        "client": "CyberCube",
        "year": "2026",
        "cover": "../assets/images/event/16.webp",
        "photos": [
          "../assets/images/event/16.webp",
          "../assets/images/event/17.webp",
          "../assets/images/event/18.webp",
          "../assets/images/event/19.webp",
          "../assets/images/event/20.webp"
        ],
        "description": "2026 Taipei Senior High School Education Expo"
      },
      {
        "id": "ev-8",
        "title": "Asia’s Got Talent Cyr Wheel Show — Yang Shih-Hao",
        "client": "Chimei Museum",
        "year": "2025",
        "cover": "../assets/images/event/22.webp",
        "position": "50% 60%",
        "photos": [
          "../assets/images/event/21.webp",
          "../assets/images/event/22.webp",
          "../assets/images/event/23.webp",
          "../assets/images/event/24.webp",
          "../assets/images/event/25.webp"
        ],
        "description": "Dance to the Extreme X The One Ballroom Gala by Hsu Yao-Chung Dance Studio"
      },
      {
        "id": "ev-9",
        "title": "Nine One One × Yang Shih-Hao",
        "client": "Taipei Dome",
        "year": "2026",
        "cover": "../assets/images/event/ShihhaoDome (1).webp",
        "photos": [
          "../assets/images/event/ShihhaoDome (1).webp",
          "../assets/images/event/ShihhaoDome (2).webp",
          "../assets/images/event/ShihhaoDome (3).webp",
          "../assets/images/event/ShihhaoDome (4).webp",
          "../assets/images/event/ShihhaoDome (5).webp",
          "../assets/images/event/ShihhaoDome (6).webp",
          "../assets/images/event/ShihhaoDome (7).webp",
          "../assets/images/event/ShihhaoDome (8).webp"
        ],
        "description": "Johnson Health Tech 50th Anniversary Charity Concert"
      },
      {
        "id": "ev-10",
        "title": "Circus Gate 2025 Annual Production: Carnival Ball",
        "client": "CIRCUS GATE",
        "year": "2025",
        "cover": "../assets/images/event/28.webp",
        "position": "60% 50%",
        "photos": [
          "../assets/images/event/26.webp",
          "../assets/images/event/27.webp",
          "../assets/images/event/28.webp",
          "../assets/images/event/29.webp",
          "../assets/images/event/30.webp"
        ],
        "description": "Eslite Performance Hall"
      },
      {
        "id": "ev-11",
        "title": "Patikol: Returning to the Nest — Torik Tribal Music & Dance Theatre",
        "client": "NTUT Aliyan",
        "year": "2025",
        "cover": "../assets/images/event/31.webp",
        "position": "50% 90%",
        "scale": 1.2,
        "photos": [
          "../assets/images/event/31.webp",
          "../assets/images/event/32.webp",
          "../assets/images/event/33.webp",
          "../assets/images/event/34.webp",
          "../assets/images/event/35.webp"
        ],
        "description": "NTUT Aliyan Indigenous Culture Society"
      },
      {
        "id": "ev-12",
        "title": "NTUT OIA 2025 Fall International Student Midterm Gathering",
        "client": "NTUT OIA",
        "year": "2025",
        "cover": "../assets/images/event/38.webp",
        "photos": [
          "../assets/images/event/36.webp",
          "../assets/images/event/37.webp",
          "../assets/images/event/38.webp",
          "../assets/images/event/39.webp",
          "../assets/images/event/40.webp"
        ],
        "description": "2025.10.29"
      },
      {
        "id": "ev-13",
        "title": "Green Power Life Festival",
        "client": "TFG X Taipei 101",
        "year": "2025",
        "cover": "../assets/images/event/42.webp",
        "position": "70% 50%",
        "photos": [
          "../assets/images/event/41.webp",
          "../assets/images/event/42.webp",
          "../assets/images/event/43.webp",
          "../assets/images/event/44.webp",
          "../assets/images/event/45.webp"
        ],
        "description": "Taipei 101 × Taipei First Girls High School"
      },
      {
        "id": "ev-14",
        "title": "2025 North Coast Shimmering Night — Tides & Fire",
        "client": "NTPC",
        "year": "2025",
        "cover": "../assets/images/event/50.webp",
        "photos": [
          "../assets/images/event/46.webp",
          "../assets/images/event/47.webp",
          "../assets/images/event/48.webp",
          "../assets/images/event/49.webp",
          "../assets/images/event/50.webp"
        ],
        "description": "2025.08.24"
      },
      {
        "id": "ev-15",
        "title": "2024 Computex Taipei",
        "client": "Computex",
        "year": "2024",
        "cover": "../assets/images/event/53.webp",
        "photos": [
          "../assets/images/event/51.webp",
          "../assets/images/event/52.webp",
          "../assets/images/event/53.webp",
          "../assets/images/event/54.webp",
          "../assets/images/event/55.webp"
        ],
        "description": "COMPUTEX Taipei"
      },
      {
        "id": "ev-16",
        "title": "Year of the Dragon Pilgrimage from Toufen Yongzhen Temple to Taipei Chihe Temple",
        "client": "TOUFEN",
        "year": "2024",
        "cover": "../assets/images/event/20241208 (5).webp",
        "photos": [
          "../assets/images/event/20241208 (1).webp",
          "../assets/images/event/20241208 (2).webp",
          "../assets/images/event/20241208 (3).webp",
          "../assets/images/event/20241208 (4).webp",
          "../assets/images/event/20241208 (5).webp",
          "../assets/images/event/20241208 (6).webp",
          "../assets/images/event/20241208 (7).webp",
          "../assets/images/event/20241208 (8).webp",
          "../assets/images/event/20241208 (9).webp",
          "../assets/images/event/20241208 (10).webp",
          "../assets/images/event/20241208 (11).webp",
          "../assets/images/event/20241208 (12).webp",
          "../assets/images/event/20241208 (13).webp",
          "../assets/images/event/20241208 (14).webp"
        ],
        "description": "2024.12.08"
      },
      {
        "id": "ev-17",
        "title": "2024 Miaoli Hakka Arts Association Dragon Boat Festival Rice-Dumpling Workshop & Energy-Saving Campaign",
        "client": "TOUFEN",
        "year": "2024",
        "cover": "../assets/images/event/20240608 (5).webp",
        "position": "0% 5%",
        "photos": [
          "../assets/images/event/20240608 (1).webp",
          "../assets/images/event/20240608 (2).webp",
          "../assets/images/event/20240608 (3).webp",
          "../assets/images/event/20240608 (4).webp",
          "../assets/images/event/20240608 (5).webp",
          "../assets/images/event/20240608 (6).webp",
          "../assets/images/event/20240608 (7).webp",
          "../assets/images/event/20240608 (8).webp",
          "../assets/images/event/20240608 (9).webp"
        ],
        "description": "Documenting the rice-dumpling preparation process."
      },
      {
        "id": "ev-18",
        "title": "2026 Ghost Festival Celebration | Handmade Hakka Newborn Rice Cakes",
        "client": "TOUFEN",
        "year": "2025",
        "cover": "../assets/images/event/20250830 (5).webp",
        "photos": [
          "../assets/images/event/20250830 (1).webp",
          "../assets/images/event/20250830 (2).webp",
          "../assets/images/event/20250830 (3).webp",
          "../assets/images/event/20250830 (4).webp",
          "../assets/images/event/20250830 (5).webp",
          "../assets/images/event/20250830 (6).webp"
        ],
        "description": "Toufen Yongzhen Temple | Zhongyuan Pudu Ceremony"
      }
    ],
    "sports": [
      {
        "id": "sp-1",
        "title": "LG Twins × Wei Chuan Dragons Collaboration Day",
        "client": "Taipei Dome",
        "year": "2026",
        "cover": "../assets/images/sports/WDragons0526 (1).webp",
        "position": "50% 85%",
        "photos": [
          "../assets/images/sports/WDragons0526 (1).webp",
          "../assets/images/sports/WDragons0526 (2).webp",
          "../assets/images/sports/WDragons0526 (3).webp",
          "../assets/images/sports/WDragons0526 (4).webp",
          "../assets/images/sports/WDragons0526 (5).webp",
          "../assets/images/sports/WDragons0526 (6).webp",
          "../assets/images/sports/WDragons0526 (7).webp",
          "../assets/images/sports/WDragons0526 (8).webp",
          "../assets/images/sports/WDragons0526 (9).webp",
          "../assets/images/sports/WDragons0526 (10).webp",
          "../assets/images/sports/WDragons0526 (11).webp",
          "../assets/images/sports/WDragons0526 (12).webp",
          "../assets/images/sports/WDragons0526 (13).webp",
          "../assets/images/sports/WDragons0526 (14).webp",
          "../assets/images/sports/WDragons0526 (15).webp",
          "../assets/images/sports/WDragons0526 (16).webp",
          "../assets/images/sports/WDragons0526 (17).webp",
          "../assets/images/sports/WDragons0526 (18).webp"
        ],
        "description": "2026.05.26"
      },
      {
        "id": "sp-2",
        "title": "P. LEAGUE+ Taipei Fubon Braves 2025–26 Home Opener",
        "client": "Taipei Heping Basketball Gymnasium",
        "year": "2025",
        "cover": "../assets/images/sports/FubonBraves1109 (9).webp",
        "position": "bottom center",
        "photos": [
          "../assets/images/sports/FubonBraves1109 (1).webp",
          "../assets/images/sports/FubonBraves1109 (2).webp",
          "../assets/images/sports/FubonBraves1109 (3).webp",
          "../assets/images/sports/FubonBraves1109 (4).webp",
          "../assets/images/sports/FubonBraves1109 (5).webp",
          "../assets/images/sports/FubonBraves1109 (6).webp",
          "../assets/images/sports/FubonBraves1109 (7).webp",
          "../assets/images/sports/FubonBraves1109 (8).webp",
          "../assets/images/sports/FubonBraves1109 (9).webp",
          "../assets/images/sports/FubonBraves1109 (10).webp"
        ],
        "description": "2025.11.09"
      },
      {
        "id": "sp-3",
        "title": "CPBL Season 35 Regular-Season Game — Sep. 15",
        "client": "Taipei Dome",
        "year": "2024",
        "cover": "../assets/images/sports/WDragons (1).webp",
        "position": "60% 60%",
        "photos": [
          "../assets/images/sports/WDragons (1).webp",
          "../assets/images/sports/WDragons (2).webp",
          "../assets/images/sports/WDragons (3).webp",
          "../assets/images/sports/WDragons (4).webp",
          "../assets/images/sports/WDragons (5).webp",
          "../assets/images/sports/WDragons (6).webp",
          "../assets/images/sports/WDragons (7).webp",
          "../assets/images/sports/WDragons (8).webp"
        ],
        "description": "2024.09.15"
      },
      {
        "id": "sp-4",
        "title": "2025 Taipei Student Baseball Fall League",
        "client": "Yingfeng Riverside Baseball Field",
        "year": "2025",
        "cover": "../assets/images/sports/NtutBaseball0930 (1).webp",
        "position": "50% 70%",
        "links": [
          {
            "label": "NTUT Baseball Instagram Post",
            "url": "https://www.instagram.com/p/DPTwKx_ktBt/?img_index=1"
          }
        ],
        "photos": [
          "../assets/images/sports/NtutBaseball0930 (1).webp",
          "../assets/images/sports/NtutBaseball0930 (2).webp",
          "../assets/images/sports/NtutBaseball0930 (3).webp",
          "../assets/images/sports/NtutBaseball0930 (4).webp",
          "../assets/images/sports/NtutBaseball0930 (5).webp",
          "../assets/images/sports/NtutBaseball0930 (6).webp",
          "../assets/images/sports/NtutBaseball0930 (7).webp",
          "../assets/images/sports/NtutBaseball0930 (8).webp",
          "../assets/images/sports/NtutBaseball0930 (9).webp",
          "../assets/images/sports/NtutBaseball0930 (10).webp",
          "../assets/images/sports/NtutBaseball0930 (11).webp",
          "../assets/images/sports/NtutBaseball0930 (12).webp",
          "../assets/images/sports/NtutBaseball0930 (13).webp",
          "../assets/images/sports/NtutBaseball0930 (14).webp",
          "../assets/images/sports/NtutBaseball0930 (15).webp",
          "../assets/images/sports/NtutBaseball0930 (16).webp",
          "../assets/images/sports/NtutBaseball0930 (17).webp",
          "../assets/images/sports/NtutBaseball0930 (18).webp",
          "../assets/images/sports/NtutBaseball0930 (19).webp"
        ],
        "description": "2025.10.02"
      },
      {
        "id": "sp-5",
        "title": "Giljegiljaw Kungkuan",
        "client": "Taipei Dome",
        "year": "2024",
        "cover": "../assets/images/sports/Giljegiljaw (1).webp",
        "position": "50% 50%",
        "links": [
          {
            "label": "Giljegiljaw Kungkuan Instagram Post",
            "url": "https://www.instagram.com/p/DADMdyUS6-u/"
          }
        ],
        "photos": [
          "../assets/images/sports/Giljegiljaw (1).webp",
          "../assets/images/sports/Giljegiljaw (2).webp",
          "../assets/images/sports/Giljegiljaw (3).webp"
        ],
        "description": "2024.09.15"
      },
      {
        "id": "sp-6",
        "title": "Enderson Daniel Franco",
        "client": "Xinzhuang Baseball Stadium",
        "year": "2025",
        "cover": "../assets/images/sports/Franco.webp",
        "position": "50% 60%",
        "links": [
          {
            "label": "Enderson Franco Instagram Post",
            "url": "https://www.instagram.com/p/DJHPCBzynVJ/"
          }
        ],
        "photos": [
          "../assets/images/sports/Franco.webp"
        ],
        "description": "2025.04.22"
      },
      {
        "id": "sp-8",
        "title": "2026 National Intercollegiate Athletic Games — Northern Badminton Qualifier",
        "client": "Taipei Gymnasium",
        "year": "2026",
        "cover": "../assets/images/sports/NtutBadminton (3).webp",
        "position": "60% 50%",
        "links": [
          {
            "label": "NTUT Badminton Instagram Post",
            "url": "https://www.instagram.com/p/DW6O8WdFECu/?img_index=9"
          }
        ],
        "photos": [
          "../assets/images/sports/NtutBadminton (1).webp",
          "../assets/images/sports/NtutBadminton (2).webp",
          "../assets/images/sports/NtutBadminton (3).webp"
        ],
        "description": "2026.03.25"
      },
      {
        "id": "sp-9",
        "title": "2024 Rising Star RG International Invitational",
        "client": "Rising Star RG",
        "year": "2024",
        "cover": "../assets/images/sports/20240705 (7).webp",
        "photos": [
          "../assets/images/sports/20240705 (1).webp",
          "../assets/images/sports/20240705 (2).webp",
          "../assets/images/sports/20240705 (3).webp",
          "../assets/images/sports/20240705 (4).webp",
          "../assets/images/sports/20240705 (5).webp",
          "../assets/images/sports/20240705 (6).webp",
          "../assets/images/sports/20240705 (7).webp"
        ],
        "description": "2024.07.05"
      }
    ],
    "graduation": [
      {
        "id": "grad-1",
        "title": "National Yang Ming Chiao Tung University",
        "client": "NYCU",
        "year": "2025",
        "cover": "../assets/images/graduation/NYCU (1).webp",
        "position": "35% 50%",
        "photos": [
          "../assets/images/graduation/NYCU (1).webp",
          "../assets/images/graduation/NYCU (2).webp",
          "../assets/images/graduation/NYCU (3).webp",
          "../assets/images/graduation/NYCU (4).webp",
          "../assets/images/graduation/NYCU (5).webp",
          "../assets/images/graduation/NYCU (6).webp"
        ],
        "description": "Doctoral Graduation Portraits"
      },
      {
        "id": "grad-2",
        "title": "National Taipei University of Technology",
        "client": "NTUT",
        "year": "2025",
        "cover": "../assets/images/graduation/NTUT (4).webp",
        "position": "50% 60%",
        "photos": [
          "../assets/images/graduation/NTUT (1).webp",
          "../assets/images/graduation/NTUT (2).webp",
          "../assets/images/graduation/NTUT (3).webp",
          "../assets/images/graduation/NTUT (4).webp",
          "../assets/images/graduation/NTUT (5).webp",
          "../assets/images/graduation/NTUT (6).webp",
          "../assets/images/graduation/NTUT (7).webp",
          "../assets/images/graduation/NTUT (8).webp"
        ],
        "description": "Master’s Graduation Portraits"
      },
      {
        "id": "grad-3",
        "title": "National Taipei University of Nursing and Health Sciences",
        "client": "NTUNHS",
        "year": "2025",
        "cover": "../assets/images/graduation/NTUNHS (7).webp",
        "position": "50% 80%",
        "photos": [
          "../assets/images/graduation/NTUNHS (1).webp",
          "../assets/images/graduation/NTUNHS (2).webp",
          "../assets/images/graduation/NTUNHS (3).webp",
          "../assets/images/graduation/NTUNHS (4).webp",
          "../assets/images/graduation/NTUNHS (5).webp",
          "../assets/images/graduation/NTUNHS (6).webp",
          "../assets/images/graduation/NTUNHS (7).webp",
          "../assets/images/graduation/NTUNHS (8).webp"
        ],
        "description": "Undergraduate Graduation Portraits"
      }
    ],
    "landscape": [
      {
        "id": "land26",
        "title": "Before the Final Closure: A Century in the Making",
        "client": "Danjiang Bridge",
        "year": "2026",
        "cover": "../assets/images/landscape/landscape1.webp",
        "position": "60% 60%",
        "scale": 1.5,
        "links": [
          {
            "label": "Instagram Post",
            "url": "https://www.instagram.com/p/DYCL2foGb-e/?img_index=1"
          }
        ],
        "photos": [
          "../assets/images/landscape/landscape1.webp"
        ],
        "description": "At the Tamsui River estuary, witnessing a world-class landmark emerge from concept into reality."
      },
      {
        "id": "land-25",
        "title": "Midsummer: Clamor and Stillness",
        "client": "Dadaocheng Fireworks",
        "year": "2026",
        "cover": "../assets/images/landscape/landscape (1).webp",
        "position": "50% 50%",
        "scale": 1,
        "links": [
          {
            "label": "Instagram Post",
            "url": "https://www.instagram.com/p/DbqMEVsAeG0/"
          }
        ],
        "photos": [
          "../assets/images/landscape/landscape (1).webp"
        ],
        "description": "From an old-city rooftop, city lights and fireworks bloom together."
      },
      {
        "id": "land-24",
        "title": "Tide Time at the Far East",
        "client": "Magang Fishing Village",
        "year": "2026",
        "cover": "../assets/images/landscape/landscape (2).webp",
        "position": "50% 50%",
        "scale": 1,
        "links": [
          {
            "label": "Instagram Post",
            "url": "https://www.instagram.com/p/Da4SD_FmVwc/?img_index=1"
          }
        ],
        "photos": [
          "../assets/images/landscape/landscape (2).webp",
          "../assets/images/landscape/landscape (3).webp",
          "../assets/images/landscape/landscape (4).webp"
        ],
        "description": "Stone houses and wave-cut platforms preserve the quietest years on Taiwan’s eastern edge."
      },
      {
        "id": "land-23",
        "title": "Where Windmills Meet Dusk",
        "client": "Itoshima Kuroiso Coast",
        "year": "2025",
        "cover": "../assets/images/landscape/landscape (5).webp",
        "position": "50% 50%",
        "scale": 1,
        "links": [
          {
            "label": "Instagram Post",
            "url": "https://www.instagram.com/p/DVGMI28kx7l/?img_index=1"
          }
        ],
        "photos": [
          "../assets/images/landscape/landscape (5).webp",
          "../assets/images/landscape/landscape (6).webp",
          "../assets/images/landscape/landscape (7).webp",
          "../assets/images/landscape/landscape (8).webp",
          "../assets/images/landscape/landscape (9).webp",
          "../assets/images/landscape/landscape (10).webp"
        ],
        "description": "Against layered mountains, a silhouette turns while listening to the tide."
      },
      {
        "id": "land-22",
        "title": "Finding My Small Self in a Vast World",
        "client": "Aso",
        "year": "2025",
        "cover": "../assets/images/landscape/landscape (11).webp",
        "position": "50% 50%",
        "scale": 1,
        "links": [
          {
            "label": "Instagram Post",
            "url": "https://www.instagram.com/p/DWdqAQ5GZnk/?img_index=1"
          }
        ],
        "photos": [
          "../assets/images/landscape/landscape (11).webp",
          "../assets/images/landscape/landscape (12).webp",
          "../assets/images/landscape/landscape (13).webp",
          "../assets/images/landscape/landscape (14).webp",
          "../assets/images/landscape/landscape (15).webp"
        ],
        "description": "Walking the folds of golden grassland, feeling the volcano’s vast heartbeat."
      },
      {
        "id": "land-21",
        "title": "An Everyday Southern Coast",
        "client": "Aoshima",
        "year": "2025",
        "cover": "../assets/images/landscape/landscape (16).webp",
        "position": "50% 50%",
        "scale": 1,
        "links": [
          {
            "label": "Instagram Post",
            "url": "https://www.instagram.com/p/DTg7ahdk6bq/?img_index=1"
          }
        ],
        "photos": [
          "../assets/images/landscape/landscape (16).webp"
        ],
        "description": "Where sunlight and breeze settle, ordinary coastal life is held still."
      },
      {
        "id": "land-20",
        "title": "When Light Touches the Sea",
        "client": "Hyuga Cape",
        "year": "2025",
        "cover": "../assets/images/landscape/landscape (17).webp",
        "position": "50% 50%",
        "scale": 1,
        "links": [
          {
            "label": "Instagram Post",
            "url": "https://www.instagram.com/p/DR2Dn8EE7yH/?img_index=1"
          }
        ],
        "photos": [
          "../assets/images/landscape/landscape (17).webp",
          "../assets/images/landscape/landscape (18).webp",
          "../assets/images/landscape/landscape (19).webp",
          "../assets/images/landscape/landscape (20).webp",
          "../assets/images/landscape/landscape (21).webp",
          "../assets/images/landscape/landscape (22).webp",
          "../assets/images/landscape/landscape (23).webp",
          "../assets/images/landscape/landscape (24).webp"
        ],
        "description": "Silver grass sways in the wind, catching glints of light from the blue sea."
      },
      {
        "id": "land-19",
        "title": "Blessings of Time and the Deities",
        "client": "Kato Shrine",
        "year": "2025",
        "cover": "../assets/images/landscape/landscape (25).webp",
        "position": "50% 50%",
        "scale": 1,
        "links": [
          {
            "label": "Official Kumamoto City Post",
            "url": "https://www.instagram.com/p/DU9r74YD2oA/?img_index=1"
          }
        ],
        "photos": [
          "../assets/images/landscape/landscape (25).webp",
          "../assets/images/landscape/landscape (26).webp",
          "../assets/images/landscape/landscape (27).webp",
          "../assets/images/landscape/landscape (28).webp",
          "../assets/images/landscape/landscape (29).webp",
          "../assets/images/landscape/landscape (30).webp"
        ],
        "description": "Ginkgo leaves and a wooden shrine frame the solemn vows of a Shinto wedding."
      },
      {
        "id": "land-18",
        "title": "The Horizon of Childhood",
        "client": "Qingtiangang",
        "year": "2025",
        "cover": "../assets/images/landscape/landscape (31).webp",
        "position": "50% 50%",
        "scale": 1.2,
        "links": [
          {
            "label": "Instagram Post",
            "url": "https://www.instagram.com/p/DOVsSC4k1bE/?img_index=1"
          }
        ],
        "photos": [
          "../assets/images/landscape/landscape (31).webp",
          "../assets/images/landscape/landscape (32).webp",
          "../assets/images/landscape/landscape (33).webp",
          "../assets/images/landscape/landscape (34).webp",
          "../assets/images/landscape/landscape (35).webp"
        ],
        "description": "Beside a breezy wooden fence, childhood runs free in its purest joy."
      },
      {
        "id": "land-17",
        "title": "Homeward Into Dusk",
        "client": "Qingtiangang",
        "year": "2025",
        "cover": "../assets/images/landscape/landscape (36).webp",
        "position": "50% 50%",
        "scale": 1.2,
        "links": [
          {
            "label": "Instagram Post",
            "url": "https://www.instagram.com/p/DPRcXKnEwv0/?img_index=1"
          }
        ],
        "photos": [
          "../assets/images/landscape/landscape (36).webp",
          "../assets/images/landscape/landscape (37).webp",
          "../assets/images/landscape/landscape (38).webp",
          "../assets/images/landscape/landscape (39).webp",
          "../assets/images/landscape/landscape (40).webp",
          "../assets/images/landscape/landscape (41).webp"
        ],
        "description": "Under a pink afterglow, watching a distant plane and birds returning home."
      },
      {
        "id": "land-16",
        "title": "A Symphony of Coexistence",
        "client": "Qingtiangang",
        "year": "2025",
        "cover": "../assets/images/landscape/landscape (42).webp",
        "position": "50% 50%",
        "scale": 1.2,
        "links": [
          {
            "label": "Instagram Post",
            "url": "https://www.instagram.com/p/DOqbzSukxJq/?img_index=1"
          }
        ],
        "photos": [
          "../assets/images/landscape/landscape (42).webp",
          "../assets/images/landscape/landscape (43).webp",
          "../assets/images/landscape/landscape (44).webp",
          "../assets/images/landscape/landscape (45).webp",
          "../assets/images/landscape/landscape (46).webp",
          "../assets/images/landscape/landscape (47).webp"
        ],
        "description": "Water buffalo and egrets share the grassland in nature’s quiet balance."
      },
      {
        "id": "land-15",
        "title": "Childhood Memories Between the Tides",
        "client": "Laomei",
        "year": "2025",
        "cover": "../assets/images/landscape/landscape (48).webp",
        "position": "50% 50%",
        "scale": 1,
        "links": [
          {
            "label": "Instagram Post",
            "url": "https://www.instagram.com/p/DPYsaWekx0h/?img_index=1"
          }
        ],
        "photos": [
          "../assets/images/landscape/landscape (48).webp",
          "../assets/images/landscape/landscape (49).webp",
          "../assets/images/landscape/landscape (50).webp"
        ],
        "description": "On a green wave-cut platform, children splash and catch crabs in unguarded joy."
      },
      {
        "id": "land-14",
        "title": "The Geometric City from Above",
        "client": "Urban Geometry",
        "year": "2026",
        "cover": "../assets/images/landscape/landscape (51).webp",
        "position": "50% 50%",
        "scale": 1,
        "links": [
          {
            "label": "Instagram Post",
            "url": "https://www.instagram.com/p/DVp3LzlGS4t/"
          }
        ],
        "photos": [
          "../assets/images/landscape/landscape (51).webp"
        ],
        "description": "An aerial view reveals streets and alleys as parallel lines of everyday life."
      },
      {
        "id": "land-13",
        "title": "A Solitary Figure in the Autumn Wind",
        "client": "Lengshuikeng",
        "year": "2025",
        "cover": "../assets/images/landscape/landscape (52).webp",
        "position": "50% 50%",
        "scale": 1,
        "links": [
          {
            "label": "Instagram Post",
            "url": "https://www.instagram.com/p/DQkq2Llk3O5/?img_index=1"
          }
        ],
        "photos": [
          "../assets/images/landscape/landscape (52).webp",
          "../assets/images/landscape/landscape (53).webp",
          "../assets/images/landscape/landscape (54).webp",
          "../assets/images/landscape/landscape (55).webp",
          "../assets/images/landscape/landscape (56).webp"
        ],
        "description": "Following the steps into silver grass, unexpectedly meeting the whole of autumn."
      },
      {
        "id": "land-12",
        "title": "Festival Bustle and the Years of an Old Street",
        "client": "Dihua Street New Year Market",
        "year": "2025",
        "cover": "../assets/images/landscape/landscape (57).webp",
        "position": "50% 50%",
        "scale": 1,
        "links": [
          {
            "label": "Instagram Post",
            "url": "https://www.instagram.com/p/DUp_axzE2T6/?img_index=1"
          }
        ],
        "photos": [
          "../assets/images/landscape/landscape (57).webp",
          "../assets/images/landscape/landscape (58).webp",
          "../assets/images/landscape/landscape (59).webp",
          "../assets/images/landscape/landscape (60).webp",
          "../assets/images/landscape/landscape (61).webp",
          "../assets/images/landscape/landscape (62).webp",
          "../assets/images/landscape/landscape (63).webp",
          "../assets/images/landscape/landscape (64).webp",
          "../assets/images/landscape/landscape (65).webp",
          "../assets/images/landscape/landscape (66).webp"
        ],
        "description": "Red lanterns and dense crowds bring the old quarter’s festive spirit to life."
      },
      {
        "id": "land-11",
        "title": "Veins in the Night",
        "client": "National Highway",
        "year": "2025",
        "cover": "../assets/images/landscape/landscape (67).webp",
        "position": "50% 50%",
        "scale": 1,
        "links": [
          {
            "label": "Instagram Post",
            "url": "https://www.instagram.com/p/DN1kb2LBhkD/"
          }
        ],
        "photos": [
          "../assets/images/landscape/landscape (67).webp"
        ],
        "description": "Light trails cut through the quiet night, tracing a city that never stops breathing."
      },
      {
        "id": "land-10",
        "title": "A Ridgeline Through the Mist",
        "client": "Keelung Mountain",
        "year": "2025",
        "cover": "../assets/images/landscape/landscape (68).webp",
        "position": "50% 50%",
        "scale": 1,
        "links": [
          {
            "label": "Instagram Post",
            "url": "https://www.instagram.com/p/DMFLMjKhfAW/?img_index=1"
          }
        ],
        "photos": [
          "../assets/images/landscape/landscape (68).webp"
        ],
        "description": "Climbing stone steps to the summit, searching for the wind between green mountains and sea."
      },
      {
        "id": "land-9",
        "title": "Night Falls and the Mountain Town Lights Up",
        "client": "Jiufen",
        "year": "2025",
        "cover": "../assets/images/landscape/landscape (69).webp",
        "position": "50% 50%",
        "scale": 1,
        "links": [
          {
            "label": "Instagram Post",
            "url": "https://www.instagram.com/p/DLmSPiwhtVz/?img_index=1"
          }
        ],
        "photos": [
          "../assets/images/landscape/landscape (69).webp"
        ],
        "description": "Soft light kindles red lanterns as teahouses layer time beneath the fading sun."
      },
      {
        "id": "land-8",
        "title": "Everyday Life Along the Sacred Tree Approach",
        "client": "Kengun Shrine",
        "year": "2024",
        "cover": "../assets/images/landscape/landscape (70).webp",
        "position": "50% 50%",
        "scale": 1,
        "links": [
          {
            "label": "Instagram Post",
            "url": "https://www.instagram.com/p/DKj9Eg5Bv9Z/"
          }
        ],
        "photos": [
          "../assets/images/landscape/landscape (70).webp"
        ],
        "description": "Greenery covers the old shrine as a solitary walk meets the solemn calm of morning."
      },
      {
        "id": "land-7",
        "title": "A Green Galaxy in the Valley",
        "client": "Jinping Creek",
        "year": "2025",
        "cover": "../assets/images/landscape/landscape (71).webp",
        "position": "50% 50%",
        "scale": 1,
        "links": [
          {
            "label": "Instagram Post",
            "url": "https://www.instagram.com/p/DLITEgpBBgD/"
          }
        ],
        "photos": [
          "../assets/images/landscape/landscape (71).webp"
        ],
        "description": "As night falls, fireflies weave between a clear stream and the dark forest."
      },
      {
        "id": "land-6",
        "title": "Distant Ridges in Ink Wash",
        "client": "Jianshi",
        "year": "2025",
        "cover": "../assets/images/landscape/landscape (72).webp",
        "position": "50% 50%",
        "scale": 1,
        "links": [
          {
            "label": "Instagram Post",
            "url": "https://www.instagram.com/p/DJtfuj9hZH6/?img_index=1"
          }
        ],
        "photos": [
          "../assets/images/landscape/landscape (72).webp",
          "../assets/images/landscape/landscape (73).webp",
          "../assets/images/landscape/landscape (74).webp",
          "../assets/images/landscape/landscape (75).webp",
          "../assets/images/landscape/landscape (76).webp"
        ],
        "description": "Monochrome tones carve rugged ridges beneath a soft veil of mist."
      },
      {
        "id": "land-5",
        "title": "The Sun’s Descending Path",
        "client": "Manhattanhenge",
        "year": "2025",
        "cover": "../assets/images/landscape/landscape (77).webp",
        "position": "50% 50%",
        "scale": 1,
        "links": [
          {
            "label": "Instagram Post",
            "url": "https://www.instagram.com/p/DJJlsShBbE_/?img_index=1"
          }
        ],
        "photos": [
          "../assets/images/landscape/landscape (77).webp"
        ],
        "description": "The blazing sun descends along the skyline, bathing the dense city in warm gold."
      },
      {
        "id": "land-4",
        "title": "A Life Shaped by the Sea",
        "client": "Jinshan",
        "year": "2025",
        "cover": "../assets/images/landscape/landscape (78).webp",
        "position": "50% 50%",
        "scale": 1,
        "links": [
          {
            "label": "Instagram Post",
            "url": "https://www.instagram.com/p/DIqz6uLBAbj/?img_index=1"
          }
        ],
        "photos": [
          "../assets/images/landscape/landscape (78).webp",
          "../assets/images/landscape/landscape (79).webp",
          "../assets/images/landscape/landscape (80).webp",
          "../assets/images/landscape/landscape (81).webp",
          "../assets/images/landscape/landscape (82).webp"
        ],
        "description": "An old motorcycle and anglers on the seawall portray the unhurried life of Taiwan’s north coast."
      },
      {
        "id": "land-3",
        "title": "Light and Flight Paths Through the Clouds",
        "client": "Sunset",
        "year": "2025",
        "cover": "../assets/images/landscape/landscape (83).webp",
        "position": "50% 50%",
        "scale": 1.2,
        "links": [
          {
            "label": "Instagram Post",
            "url": "https://www.instagram.com/p/DIQx_9GJcn_/?img_index=1"
          }
        ],
        "photos": [
          "../assets/images/landscape/landscape (83).webp"
        ],
        "description": "Sunbeams break through evening clouds as a tiny aircraft heads toward the coming night."
      },
      {
        "id": "land-2",
        "title": "The Turning Rings of the Cosmos",
        "client": "Star Trails",
        "year": "2025",
        "cover": "../assets/images/landscape/landscape (84).webp",
        "position": "50% 50%",
        "scale": 1,
        "links": [
          {
            "label": "Instagram Post",
            "url": "https://www.instagram.com/p/DGsJRsOJGjf/?img_index=1"
          }
        ],
        "photos": [
          "../assets/images/landscape/landscape (84).webp"
        ],
        "description": "Time turns quietly in the night, etching star trails above the ridge."
      },
      {
        "id": "land-1",
        "title": "Firefly Glow Along a Forest Path",
        "client": "Shiding",
        "year": "2026",
        "cover": "../assets/images/landscape/landscape (85).webp",
        "position": "50% 50%",
        "scale": 1,
        "links": [
          {
            "label": "Instagram Post",
            "url": "https://www.instagram.com/p/DW_f7LEGaPN/?img_index=1"
          }
        ],
        "photos": [
          "../assets/images/landscape/landscape (85).webp",
          "../assets/images/landscape/landscape (86).webp"
        ],
        "description": "Along a quiet trail, yellow-green fireflies kindle small lights in the forest night."
      }
    ]
  },
  "workerApiEndpoint": "https://weipic-api.weipic2023.workers.dev/",
  "clientGalleries": []
};
